project:
  type: website

website:
  title: "ISSS626"
  navbar:
    left: 
      - text: "Hands-on Exercise"
        menu:
         - text: "Hands-on Exercise 1-1"
           href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex1-1.html"
         - text: "Hands-on Exercise 1-2"
           href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex1-2.html"
         - text: "Hands-on Exercise 2-1 & 2-2"
           href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex2-1&2-2.html"
         - text: "Hands-on Exercise 3"
           href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex3.html"
         - text: "Hands-on Exercise 4"
           href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex4.html"
         - text: "Hands-on Exercise 5-1"
           href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex5-1.html"
         - text: "Hands-on Exercise 5-2"
           href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex5-2.html"
         - text: "Hands-on Exercise 6"
           href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex6.html"
         - text: "Hands-on Exercise 7"
           href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex7.html"
         - text: "Hands-on Exercise 8"
           href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex8.html"
         - text: "Hands-on Exercise 9"
           href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex9.html"
      - text: "In-class Exercise"
        menu:
         - text: "In-class Exercise 3a"
           href: "Inclass_Ex/In_class_Ex3/In-class_Ex03a.html"
         - text: "In-class Exercise 3b"
           href: "Inclass_Ex/In_class_Ex3/In-class_Ex03b.html"
         - text: "In-class Exercise 4"
           href: "Inclass_Ex/In_class_Ex4/In-class_Ex04.html"
         - text: "In-class Exercise 5"
           href: "Inclass_Ex/In_class_Ex5/In-class_Ex05.html"
         - text: "In-class Exercise 6"
           href: "Inclass_Ex/In_class_Ex6/In-class_Ex06.html"
         - text: "In-class Exercise 7"
           href: "Inclass_Ex/In_class_Ex7/In-class_Ex07.html"
         - text: "In-class Exercise 8"
           href: "Inclass_Ex/In_class_Ex8/In-class_Ex08.html"
      - text: "Take Home Exercise"
        menu:
         - text: "Take Home Exercise 1"
           href: "Take_Home_Ex/Take_Home_Ex1/Take_Home_Ex1.html"
         - text: "Take Home Exercise 2"
           href: "Take_Home_Ex/Take_Home_Ex2/Take_Home_Ex2.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: sandstone
    backgroundcolor: '#ADD8E6'
    light: cosmo
    toc: true
    smooth-scroll: true
    code-line-numbers: true
    code-block-bg: true
    code-block-border-left: "#FFA500"
    highlight-style: gruvbox
    code-links:
      - text: GitHub Repo
        icon: file-code
        href: https://github.com/Sathvika-7284/ISSS626-geo

editor: visual
