project:
  type: website

website:
  title: "ISSS626"
  navbar: 
    left:
      - menu: 
        - text: Hands-on Exercise
        - text: In-class Exercise
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

