<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sathvika Subramanian">
<meta name="dcterms.date" content="2025-10-18">

<title>In class Exercise 7 – ISSS626</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">ISSS626</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex1-1.html">
 <span class="dropdown-text">Hands-on Exercise 1-1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex1-2.html">
 <span class="dropdown-text">Hands-on Exercise 1-2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex2-1&amp;2-2.html">
 <span class="dropdown-text">Hands-on Exercise 2-1 &amp; 2-2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex3.html">
 <span class="dropdown-text">Hands-on Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex4.html">
 <span class="dropdown-text">Hands-on Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex5-1.html">
 <span class="dropdown-text">Hands-on Exercise 5-1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex5-2.html">
 <span class="dropdown-text">Hands-on Exercise 5-2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex6.html">
 <span class="dropdown-text">Hands-on Exercise 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex7.html">
 <span class="dropdown-text">Hands-on Exercise 7</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-class Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="../../Inclass_Ex/In_class_Ex3/In-class_Ex03a.html">
 <span class="dropdown-text">In-class Exercise 3a</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Inclass_Ex/In_class_Ex3/In-class_Ex03b.html">
 <span class="dropdown-text">In-class Exercise 3b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Inclass_Ex/In_class_Ex4/In-class_Ex04.html">
 <span class="dropdown-text">In-class Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Inclass_Ex/In_class_Ex5/In-class_Ex05.html">
 <span class="dropdown-text">In-class Exercise 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Inclass_Ex/In_class_Ex6/In-class_Ex06.html">
 <span class="dropdown-text">In-class Exercise 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Inclass_Ex/In_class_Ex7/In-class_Ex07.html">
 <span class="dropdown-text">In-class Exercise 7</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take Home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../Take_Home_Ex/Take_Home_Ex1/Take_Home_Ex1.html">
 <span class="dropdown-text">Take Home Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take_Home_Ex/Take_Home_Ex2/Take_Home_Ex2.html">
 <span class="dropdown-text">Take Home Exercise 2</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#calibrating-hedonic-pricing-model-for-private-highrise-property-with-gwr-method" id="toc-calibrating-hedonic-pricing-model-for-private-highrise-property-with-gwr-method" class="nav-link active" data-scroll-target="#calibrating-hedonic-pricing-model-for-private-highrise-property-with-gwr-method">Calibrating Hedonic Pricing Model for Private Highrise Property with GWR Method</a></li>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link" data-scroll-target="#getting-started">1.Getting Started</a></li>
  <li><a href="#geospatial-data-wrangling" id="toc-geospatial-data-wrangling" class="nav-link" data-scroll-target="#geospatial-data-wrangling">2. Geospatial Data Wrangling</a>
  <ul class="collapse">
  <li><a href="#importing-geospatial-data" id="toc-importing-geospatial-data" class="nav-link" data-scroll-target="#importing-geospatial-data">2.1 Importing geospatial data</a></li>
  <li><a href="#updating-crs-information" id="toc-updating-crs-information" class="nav-link" data-scroll-target="#updating-crs-information">2.2 Updating CRS information</a></li>
  </ul></li>
  <li><a href="#aspatial-data-wrangling" id="toc-aspatial-data-wrangling" class="nav-link" data-scroll-target="#aspatial-data-wrangling">3. Aspatial Data Wrangling</a>
  <ul class="collapse">
  <li><a href="#importing-the-aspatial-data" id="toc-importing-the-aspatial-data" class="nav-link" data-scroll-target="#importing-the-aspatial-data">3.1 Importing the aspatial data</a></li>
  <li><a href="#converting-aspatial-data-frame-into-a-sf-object" id="toc-converting-aspatial-data-frame-into-a-sf-object" class="nav-link" data-scroll-target="#converting-aspatial-data-frame-into-a-sf-object">3.2 Converting aspatial data frame into a sf object</a></li>
  </ul></li>
  <li><a href="#exploratory-data-analysis-eda" id="toc-exploratory-data-analysis-eda" class="nav-link" data-scroll-target="#exploratory-data-analysis-eda">4. Exploratory Data Analysis (EDA)</a>
  <ul class="collapse">
  <li><a href="#eda-using-statistical-graphics" id="toc-eda-using-statistical-graphics" class="nav-link" data-scroll-target="#eda-using-statistical-graphics">4.1 EDA using statistical graphics</a></li>
  <li><a href="#multiple-histogram-plots-distribution-of-variables" id="toc-multiple-histogram-plots-distribution-of-variables" class="nav-link" data-scroll-target="#multiple-histogram-plots-distribution-of-variables">4.2 Multiple Histogram Plots distribution of variables</a></li>
  <li><a href="#drawing-statistical-point-map" id="toc-drawing-statistical-point-map" class="nav-link" data-scroll-target="#drawing-statistical-point-map">4.3 Drawing Statistical Point Map</a></li>
  </ul></li>
  <li><a href="#hedonic-pricing-modelling-in-r" id="toc-hedonic-pricing-modelling-in-r" class="nav-link" data-scroll-target="#hedonic-pricing-modelling-in-r">5. Hedonic Pricing Modelling in R</a>
  <ul class="collapse">
  <li><a href="#simple-linear-regression-method" id="toc-simple-linear-regression-method" class="nav-link" data-scroll-target="#simple-linear-regression-method">5.1 Simple Linear Regression Method</a></li>
  <li><a href="#multiple-linear-regression-method" id="toc-multiple-linear-regression-method" class="nav-link" data-scroll-target="#multiple-linear-regression-method">5.2 Multiple Linear Regression Method</a>
  <ul class="collapse">
  <li><a href="#visualising-the-relationships-of-the-independent-variables" id="toc-visualising-the-relationships-of-the-independent-variables" class="nav-link" data-scroll-target="#visualising-the-relationships-of-the-independent-variables">5.2.1 Visualising the relationships of the independent variables</a></li>
  </ul></li>
  <li><a href="#building-a-hedonic-pricing-model-using-multiple-linear-regression-method" id="toc-building-a-hedonic-pricing-model-using-multiple-linear-regression-method" class="nav-link" data-scroll-target="#building-a-hedonic-pricing-model-using-multiple-linear-regression-method">5.3 Building a hedonic pricing model using multiple linear regression method</a></li>
  <li><a href="#revising-the-model" id="toc-revising-the-model" class="nav-link" data-scroll-target="#revising-the-model">5.4 Revising the model</a></li>
  <li><a href="#preparing-publication-quality-table-gtsummary-method" id="toc-preparing-publication-quality-table-gtsummary-method" class="nav-link" data-scroll-target="#preparing-publication-quality-table-gtsummary-method">5.5 Preparing Publication Quality Table: gtsummary method</a></li>
  <li><a href="#regression-diagnostics" id="toc-regression-diagnostics" class="nav-link" data-scroll-target="#regression-diagnostics">5.6 Regression Diagnostics</a>
  <ul class="collapse">
  <li><a href="#multicollinearity-test" id="toc-multicollinearity-test" class="nav-link" data-scroll-target="#multicollinearity-test">5.6.1 Multicollinearity test</a></li>
  <li><a href="#test-for-non-linearity" id="toc-test-for-non-linearity" class="nav-link" data-scroll-target="#test-for-non-linearity">5.6.2 Test for Non-Linearity</a></li>
  <li><a href="#test-for-normality-assumption" id="toc-test-for-normality-assumption" class="nav-link" data-scroll-target="#test-for-normality-assumption">5.6.3 Test for Normality Assumption</a></li>
  <li><a href="#testing-for-spatial-autocorrelation" id="toc-testing-for-spatial-autocorrelation" class="nav-link" data-scroll-target="#testing-for-spatial-autocorrelation">5.6.4 Testing for Spatial Autocorrelation</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#building-hedonic-pricing-models-using-gwmodel" id="toc-building-hedonic-pricing-models-using-gwmodel" class="nav-link" data-scroll-target="#building-hedonic-pricing-models-using-gwmodel">6. Building Hedonic Pricing Models using GWmodel</a>
  <ul class="collapse">
  <li><a href="#building-fixed-bandwidth-gwr-model" id="toc-building-fixed-bandwidth-gwr-model" class="nav-link" data-scroll-target="#building-fixed-bandwidth-gwr-model">6.1 Building Fixed Bandwidth GWR Model</a>
  <ul class="collapse">
  <li><a href="#computing-fixed-bandwith" id="toc-computing-fixed-bandwith" class="nav-link" data-scroll-target="#computing-fixed-bandwith">6.1.1 Computing fixed bandwith</a></li>
  <li><a href="#gwmodel-method---fixed-bandwith" id="toc-gwmodel-method---fixed-bandwith" class="nav-link" data-scroll-target="#gwmodel-method---fixed-bandwith">6.1.2 GWModel method - fixed bandwith</a></li>
  </ul></li>
  <li><a href="#building-adaptive-bandwidth-gwr-model" id="toc-building-adaptive-bandwidth-gwr-model" class="nav-link" data-scroll-target="#building-adaptive-bandwidth-gwr-model">6.2 Building Adaptive Bandwidth GWR Model</a>
  <ul class="collapse">
  <li><a href="#computing-the-adaptive-bandwidth" id="toc-computing-the-adaptive-bandwidth" class="nav-link" data-scroll-target="#computing-the-adaptive-bandwidth">6.2.1 Computing the adaptive bandwidth</a></li>
  <li><a href="#constructing-the-adaptive-bandwidth-gwr-model" id="toc-constructing-the-adaptive-bandwidth-gwr-model" class="nav-link" data-scroll-target="#constructing-the-adaptive-bandwidth-gwr-model">6.2.2 Constructing the adaptive bandwidth gwr model</a></li>
  </ul></li>
  <li><a href="#converting-sdf-into-sf-data.frame" id="toc-converting-sdf-into-sf-data.frame" class="nav-link" data-scroll-target="#converting-sdf-into-sf-data.frame">6.3 Converting SDF into sf data.frame</a></li>
  <li><a href="#visualising-local-r2" id="toc-visualising-local-r2" class="nav-link" data-scroll-target="#visualising-local-r2">6.4 Visualising local R2</a></li>
  <li><a href="#thematic-mapping" id="toc-thematic-mapping" class="nav-link" data-scroll-target="#thematic-mapping">6.5 Thematic Mapping</a></li>
  <li><a href="#analyzing-r²-distribution-in-jurong-east-planning-area" id="toc-analyzing-r²-distribution-in-jurong-east-planning-area" class="nav-link" data-scroll-target="#analyzing-r²-distribution-in-jurong-east-planning-area">Analyzing R² Distribution in Jurong East Planning Area</a></li>
  </ul></li>
  </ul>
<div class="quarto-code-links"><h2>Code Links</h2><ul><li><a href="https://github.com/Sathvika-7284/ISSS626-geo"><i class="bi bi-file-code"></i>GitHub Repo</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">In class Exercise 7</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sathvika Subramanian </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 18, 2025</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">October 18, 2025</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="calibrating-hedonic-pricing-model-for-private-highrise-property-with-gwr-method" class="level1">
<h1>Calibrating Hedonic Pricing Model for Private Highrise Property with GWR Method</h1>
</section>
<section id="getting-started" class="level1">
<h1>1.Getting Started</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(olsrr, corrplot, ggpubr, </span>
<span id="cb1-2"><a href="#cb1-2"></a>               sf, sfdep, GWmodel, tmap, </span>
<span id="cb1-3"><a href="#cb1-3"></a>               tidyverse, gtsummary,</span>
<span id="cb1-4"><a href="#cb1-4"></a>               performance, RColorBrewer,qqplotr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="geospatial-data-wrangling" class="level1">
<h1>2. Geospatial Data Wrangling</h1>
<section id="importing-geospatial-data" class="level2">
<h2 class="anchored" data-anchor-id="importing-geospatial-data">2.1 Importing geospatial data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a>mpsz <span class="ot">=</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geospatial"</span>, </span>
<span id="cb2-2"><a href="#cb2-2"></a>               <span class="at">layer =</span> <span class="st">"MP14_SUBZONE_WEB_PL"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `MP14_SUBZONE_WEB_PL' from data source 
  `C:\Sathvika-7284\ISSS626-geo\Inclass_Ex\In_class_Ex7\data\geospatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 323 features and 15 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33
Projected CRS: SVY21</code></pre>
</div>
</div>
</section>
<section id="updating-crs-information" class="level2">
<h2 class="anchored" data-anchor-id="updating-crs-information">2.2 Updating CRS information</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a>mpsz_svy21 <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(mpsz, <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a><span class="fu">st_crs</span>(mpsz_svy21)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:3414 
  wkt:
PROJCRS["SVY21 / Singapore TM",
    BASEGEOGCRS["SVY21",
        DATUM["SVY21",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4757]],
    CONVERSION["Singapore Transverse Mercator",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",1.36666666666667,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",103.833333333333,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",1,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",28001.642,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",38744.572,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["northing (N)",north,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["easting (E)",east,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Cadastre, engineering survey, topographic mapping."],
        AREA["Singapore - onshore and offshore."],
        BBOX[1.13,103.59,1.47,104.07]],
    ID["EPSG",3414]]</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="fu">st_bbox</span>(mpsz_svy21)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     xmin      ymin      xmax      ymax 
 2667.538 15748.721 56396.440 50256.334 </code></pre>
</div>
</div>
</section>
</section>
<section id="aspatial-data-wrangling" class="level1">
<h1>3. Aspatial Data Wrangling</h1>
<section id="importing-the-aspatial-data" class="level2">
<h2 class="anchored" data-anchor-id="importing-the-aspatial-data">3.1 Importing the aspatial data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a>condo_resale <span class="ot">=</span> <span class="fu">read_csv</span>(</span>
<span id="cb9-2"><a href="#cb9-2"></a>  <span class="st">"data/aspatial/Condo_resale_2015.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="fu">glimpse</span>(condo_resale)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,436
Columns: 23
$ LATITUDE             &lt;dbl&gt; 1.287145, 1.328698, 1.313727, 1.308563, 1.321437,…
$ LONGITUDE            &lt;dbl&gt; 103.7802, 103.8123, 103.7971, 103.8247, 103.9505,…
$ POSTCODE             &lt;dbl&gt; 118635, 288420, 267833, 258380, 467169, 466472, 3…
$ SELLING_PRICE        &lt;dbl&gt; 3000000, 3880000, 3325000, 4250000, 1400000, 1320…
$ AREA_SQM             &lt;dbl&gt; 309, 290, 248, 127, 145, 139, 218, 141, 165, 168,…
$ AGE                  &lt;dbl&gt; 30, 32, 33, 7, 28, 22, 24, 24, 27, 31, 17, 22, 6,…
$ PROX_CBD             &lt;dbl&gt; 7.941259, 6.609797, 6.898000, 4.038861, 11.783402…
$ PROX_CHILDCARE       &lt;dbl&gt; 0.16597932, 0.28027246, 0.42922669, 0.39473543, 0…
$ PROX_ELDERLYCARE     &lt;dbl&gt; 2.5198118, 1.9333338, 0.5021395, 1.9910316, 1.121…
$ PROX_URA_GROWTH_AREA &lt;dbl&gt; 6.618741, 7.505109, 6.463887, 4.906512, 6.410632,…
$ PROX_HAWKER_MARKET   &lt;dbl&gt; 1.76542207, 0.54507614, 0.37789301, 1.68259969, 0…
$ PROX_KINDERGARTEN    &lt;dbl&gt; 0.05835552, 0.61592412, 0.14120309, 0.38200076, 0…
$ PROX_MRT             &lt;dbl&gt; 0.5607188, 0.6584461, 0.3053433, 0.6910183, 0.528…
$ PROX_PARK            &lt;dbl&gt; 1.1710446, 0.1992269, 0.2779886, 0.9832843, 0.116…
$ PROX_PRIMARY_SCH     &lt;dbl&gt; 1.6340256, 0.9747834, 1.4715016, 1.4546324, 0.709…
$ PROX_TOP_PRIMARY_SCH &lt;dbl&gt; 3.3273195, 0.9747834, 1.4715016, 2.3006394, 0.709…
$ PROX_SHOPPING_MALL   &lt;dbl&gt; 2.2102717, 2.9374279, 1.2256850, 0.3525671, 1.307…
$ PROX_SUPERMARKET     &lt;dbl&gt; 0.9103958, 0.5900617, 0.4135583, 0.4162219, 0.581…
$ PROX_BUS_STOP        &lt;dbl&gt; 0.10336166, 0.28673408, 0.28504777, 0.29872340, 0…
$ NO_Of_UNITS          &lt;dbl&gt; 18, 20, 27, 30, 30, 31, 32, 32, 32, 32, 34, 34, 3…
$ FAMILY_FRIENDLY      &lt;dbl&gt; 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0…
$ FREEHOLD             &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1…
$ LEASEHOLD_99YR       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a><span class="fu">head</span>(condo_resale<span class="sc">$</span>LONGITUDE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 103.7802 103.8123 103.7971 103.8247 103.9505 103.9386</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a><span class="fu">head</span>(condo_resale<span class="sc">$</span>LATITUDE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.287145 1.328698 1.313727 1.308563 1.321437 1.314198</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a><span class="fu">summary</span>(condo_resale)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    LATITUDE       LONGITUDE        POSTCODE      SELLING_PRICE     
 Min.   :1.240   Min.   :103.7   Min.   : 18965   Min.   :  540000  
 1st Qu.:1.309   1st Qu.:103.8   1st Qu.:259849   1st Qu.: 1100000  
 Median :1.328   Median :103.8   Median :469298   Median : 1383222  
 Mean   :1.334   Mean   :103.8   Mean   :440439   Mean   : 1751211  
 3rd Qu.:1.357   3rd Qu.:103.9   3rd Qu.:589486   3rd Qu.: 1950000  
 Max.   :1.454   Max.   :104.0   Max.   :828833   Max.   :18000000  
    AREA_SQM          AGE           PROX_CBD       PROX_CHILDCARE    
 Min.   : 34.0   Min.   : 0.00   Min.   : 0.3869   Min.   :0.004927  
 1st Qu.:103.0   1st Qu.: 5.00   1st Qu.: 5.5574   1st Qu.:0.174481  
 Median :121.0   Median :11.00   Median : 9.3567   Median :0.258135  
 Mean   :136.5   Mean   :12.14   Mean   : 9.3254   Mean   :0.326313  
 3rd Qu.:156.0   3rd Qu.:18.00   3rd Qu.:12.6661   3rd Qu.:0.368293  
 Max.   :619.0   Max.   :37.00   Max.   :19.1804   Max.   :3.465726  
 PROX_ELDERLYCARE  PROX_URA_GROWTH_AREA PROX_HAWKER_MARKET PROX_KINDERGARTEN 
 Min.   :0.05451   Min.   :0.2145       Min.   :0.05182    Min.   :0.004927  
 1st Qu.:0.61254   1st Qu.:3.1643       1st Qu.:0.55245    1st Qu.:0.276345  
 Median :0.94179   Median :4.6186       Median :0.90842    Median :0.413385  
 Mean   :1.05351   Mean   :4.5981       Mean   :1.27987    Mean   :0.458903  
 3rd Qu.:1.35122   3rd Qu.:5.7550       3rd Qu.:1.68578    3rd Qu.:0.578474  
 Max.   :3.94916   Max.   :9.1554       Max.   :5.37435    Max.   :2.229045  
    PROX_MRT         PROX_PARK       PROX_PRIMARY_SCH  PROX_TOP_PRIMARY_SCH
 Min.   :0.05278   Min.   :0.02906   Min.   :0.07711   Min.   :0.07711     
 1st Qu.:0.34646   1st Qu.:0.26211   1st Qu.:0.44024   1st Qu.:1.34451     
 Median :0.57430   Median :0.39926   Median :0.63505   Median :1.88213     
 Mean   :0.67316   Mean   :0.49802   Mean   :0.75471   Mean   :2.27347     
 3rd Qu.:0.84844   3rd Qu.:0.65592   3rd Qu.:0.95104   3rd Qu.:2.90954     
 Max.   :3.48037   Max.   :2.16105   Max.   :3.92899   Max.   :6.74819     
 PROX_SHOPPING_MALL PROX_SUPERMARKET PROX_BUS_STOP       NO_Of_UNITS    
 Min.   :0.0000     Min.   :0.0000   Min.   :0.001595   Min.   :  18.0  
 1st Qu.:0.5258     1st Qu.:0.3695   1st Qu.:0.098356   1st Qu.: 188.8  
 Median :0.9357     Median :0.5687   Median :0.151710   Median : 360.0  
 Mean   :1.0455     Mean   :0.6141   Mean   :0.193974   Mean   : 409.2  
 3rd Qu.:1.3994     3rd Qu.:0.7862   3rd Qu.:0.220466   3rd Qu.: 590.0  
 Max.   :3.4774     Max.   :2.2441   Max.   :2.476639   Max.   :1703.0  
 FAMILY_FRIENDLY     FREEHOLD      LEASEHOLD_99YR  
 Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  
 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000  
 Median :0.0000   Median :0.0000   Median :0.0000  
 Mean   :0.4868   Mean   :0.4227   Mean   :0.4882  
 3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000  
 Max.   :1.0000   Max.   :1.0000   Max.   :1.0000  </code></pre>
</div>
</div>
</section>
<section id="converting-aspatial-data-frame-into-a-sf-object" class="level2">
<h2 class="anchored" data-anchor-id="converting-aspatial-data-frame-into-a-sf-object">3.2 Converting aspatial data frame into a sf object</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a>condo_resale.sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(condo_resale,</span>
<span id="cb18-2"><a href="#cb18-2"></a>                            <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"LONGITUDE"</span>, <span class="st">"LATITUDE"</span>),</span>
<span id="cb18-3"><a href="#cb18-3"></a>                            <span class="at">crs=</span><span class="dv">4326</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-4"><a href="#cb18-4"></a>  <span class="fu">st_transform</span>(<span class="at">crs=</span><span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a><span class="fu">head</span>(condo_resale.sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 21 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 22085.12 ymin: 29951.54 xmax: 41042.56 ymax: 34546.2
Projected CRS: SVY21 / Singapore TM
# A tibble: 6 × 22
  POSTCODE SELLING_PRICE AREA_SQM   AGE PROX_CBD PROX_CHILDCARE PROX_ELDERLYCARE
     &lt;dbl&gt;         &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;          &lt;dbl&gt;            &lt;dbl&gt;
1   118635       3000000      309    30     7.94          0.166            2.52 
2   288420       3880000      290    32     6.61          0.280            1.93 
3   267833       3325000      248    33     6.90          0.429            0.502
4   258380       4250000      127     7     4.04          0.395            1.99 
5   467169       1400000      145    28    11.8           0.119            1.12 
6   466472       1320000      139    22    10.3           0.125            0.789
# ℹ 15 more variables: PROX_URA_GROWTH_AREA &lt;dbl&gt;, PROX_HAWKER_MARKET &lt;dbl&gt;,
#   PROX_KINDERGARTEN &lt;dbl&gt;, PROX_MRT &lt;dbl&gt;, PROX_PARK &lt;dbl&gt;,
#   PROX_PRIMARY_SCH &lt;dbl&gt;, PROX_TOP_PRIMARY_SCH &lt;dbl&gt;,
#   PROX_SHOPPING_MALL &lt;dbl&gt;, PROX_SUPERMARKET &lt;dbl&gt;, PROX_BUS_STOP &lt;dbl&gt;,
#   NO_Of_UNITS &lt;dbl&gt;, FAMILY_FRIENDLY &lt;dbl&gt;, FREEHOLD &lt;dbl&gt;,
#   LEASEHOLD_99YR &lt;dbl&gt;, geometry &lt;POINT [m]&gt;</code></pre>
</div>
</div>
</section>
</section>
<section id="exploratory-data-analysis-eda" class="level1">
<h1>4. Exploratory Data Analysis (EDA)</h1>
<section id="eda-using-statistical-graphics" class="level2">
<h2 class="anchored" data-anchor-id="eda-using-statistical-graphics">4.1 EDA using statistical graphics</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>condo_resale.sf, </span>
<span id="cb21-2"><a href="#cb21-2"></a>       <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">SELLING_PRICE</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, </span>
<span id="cb21-4"><a href="#cb21-4"></a>                 <span class="at">color=</span><span class="st">"black"</span>, </span>
<span id="cb21-5"><a href="#cb21-5"></a>                 <span class="at">fill=</span><span class="st">"light blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="In-class_Ex07_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a>condo_resale.sf <span class="ot">&lt;-</span> condo_resale.sf <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">LOG_SELLING_PRICE</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">log</span>(SELLING_PRICE))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>condo_resale.sf, </span>
<span id="cb23-2"><a href="#cb23-2"></a>       <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">LOG_SELLING_PRICE</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, </span>
<span id="cb23-4"><a href="#cb23-4"></a>                 <span class="at">color=</span><span class="st">"black"</span>, </span>
<span id="cb23-5"><a href="#cb23-5"></a>                 <span class="at">fill=</span><span class="st">"light blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="In-class_Ex07_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="multiple-histogram-plots-distribution-of-variables" class="level2">
<h2 class="anchored" data-anchor-id="multiple-histogram-plots-distribution-of-variables">4.2 Multiple Histogram Plots distribution of variables</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a>AREA_SQM <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>condo_resale.sf, </span>
<span id="cb24-2"><a href="#cb24-2"></a>                   <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">AREA_SQM</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, </span>
<span id="cb24-4"><a href="#cb24-4"></a>                 <span class="at">color=</span><span class="st">"black"</span>, </span>
<span id="cb24-5"><a href="#cb24-5"></a>                 <span class="at">fill=</span><span class="st">"light blue"</span>)</span>
<span id="cb24-6"><a href="#cb24-6"></a></span>
<span id="cb24-7"><a href="#cb24-7"></a>AGE <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>condo_resale.sf, </span>
<span id="cb24-8"><a href="#cb24-8"></a>              <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">AGE</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb24-9"><a href="#cb24-9"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, </span>
<span id="cb24-10"><a href="#cb24-10"></a>                 <span class="at">color=</span><span class="st">"black"</span>, </span>
<span id="cb24-11"><a href="#cb24-11"></a>                 <span class="at">fill=</span><span class="st">"light blue"</span>)</span>
<span id="cb24-12"><a href="#cb24-12"></a></span>
<span id="cb24-13"><a href="#cb24-13"></a>PROX_CBD <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>condo_resale.sf, </span>
<span id="cb24-14"><a href="#cb24-14"></a>                   <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">PROX_CBD</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb24-15"><a href="#cb24-15"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, </span>
<span id="cb24-16"><a href="#cb24-16"></a>                 <span class="at">color=</span><span class="st">"black"</span>, </span>
<span id="cb24-17"><a href="#cb24-17"></a>                 <span class="at">fill=</span><span class="st">"light blue"</span>)</span>
<span id="cb24-18"><a href="#cb24-18"></a></span>
<span id="cb24-19"><a href="#cb24-19"></a>PROX_CHILDCARE <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>condo_resale.sf, </span>
<span id="cb24-20"><a href="#cb24-20"></a>                         <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">PROX_CHILDCARE</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb24-21"><a href="#cb24-21"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, </span>
<span id="cb24-22"><a href="#cb24-22"></a>                 <span class="at">color=</span><span class="st">"black"</span>, </span>
<span id="cb24-23"><a href="#cb24-23"></a>                 <span class="at">fill=</span><span class="st">"light blue"</span>)</span>
<span id="cb24-24"><a href="#cb24-24"></a></span>
<span id="cb24-25"><a href="#cb24-25"></a>PROX_ELDERLYCARE <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>condo_resale.sf, </span>
<span id="cb24-26"><a href="#cb24-26"></a>                           <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">PROX_ELDERLYCARE</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb24-27"><a href="#cb24-27"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, </span>
<span id="cb24-28"><a href="#cb24-28"></a>                 <span class="at">color=</span><span class="st">"black"</span>, </span>
<span id="cb24-29"><a href="#cb24-29"></a>                 <span class="at">fill=</span><span class="st">"light blue"</span>)</span>
<span id="cb24-30"><a href="#cb24-30"></a></span>
<span id="cb24-31"><a href="#cb24-31"></a>PROX_URA_GROWTH_AREA <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>condo_resale.sf, </span>
<span id="cb24-32"><a href="#cb24-32"></a>                               <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">PROX_URA_GROWTH_AREA</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb24-33"><a href="#cb24-33"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, </span>
<span id="cb24-34"><a href="#cb24-34"></a>                 <span class="at">color=</span><span class="st">"black"</span>, </span>
<span id="cb24-35"><a href="#cb24-35"></a>                 <span class="at">fill=</span><span class="st">"light blue"</span>)</span>
<span id="cb24-36"><a href="#cb24-36"></a></span>
<span id="cb24-37"><a href="#cb24-37"></a>PROX_HAWKER_MARKET <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>condo_resale.sf, </span>
<span id="cb24-38"><a href="#cb24-38"></a>                             <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">PROX_HAWKER_MARKET</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb24-39"><a href="#cb24-39"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, </span>
<span id="cb24-40"><a href="#cb24-40"></a>                 <span class="at">color=</span><span class="st">"black"</span>, </span>
<span id="cb24-41"><a href="#cb24-41"></a>                 <span class="at">fill=</span><span class="st">"light blue"</span>)</span>
<span id="cb24-42"><a href="#cb24-42"></a></span>
<span id="cb24-43"><a href="#cb24-43"></a>PROX_KINDERGARTEN <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>condo_resale.sf, </span>
<span id="cb24-44"><a href="#cb24-44"></a>                            <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">PROX_KINDERGARTEN</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb24-45"><a href="#cb24-45"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, </span>
<span id="cb24-46"><a href="#cb24-46"></a>                 <span class="at">color=</span><span class="st">"black"</span>, </span>
<span id="cb24-47"><a href="#cb24-47"></a>                 <span class="at">fill=</span><span class="st">"light blue"</span>)</span>
<span id="cb24-48"><a href="#cb24-48"></a></span>
<span id="cb24-49"><a href="#cb24-49"></a>PROX_MRT <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>condo_resale.sf, </span>
<span id="cb24-50"><a href="#cb24-50"></a>                   <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">PROX_MRT</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb24-51"><a href="#cb24-51"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, </span>
<span id="cb24-52"><a href="#cb24-52"></a>                 <span class="at">color=</span><span class="st">"black"</span>, </span>
<span id="cb24-53"><a href="#cb24-53"></a>                 <span class="at">fill=</span><span class="st">"light blue"</span>)</span>
<span id="cb24-54"><a href="#cb24-54"></a></span>
<span id="cb24-55"><a href="#cb24-55"></a>PROX_PARK <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>condo_resale.sf, </span>
<span id="cb24-56"><a href="#cb24-56"></a>                    <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">PROX_PARK</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb24-57"><a href="#cb24-57"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, </span>
<span id="cb24-58"><a href="#cb24-58"></a>                 <span class="at">color=</span><span class="st">"black"</span>, </span>
<span id="cb24-59"><a href="#cb24-59"></a>                 <span class="at">fill=</span><span class="st">"light blue"</span>)</span>
<span id="cb24-60"><a href="#cb24-60"></a></span>
<span id="cb24-61"><a href="#cb24-61"></a>PROX_PRIMARY_SCH <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>condo_resale.sf, </span>
<span id="cb24-62"><a href="#cb24-62"></a>                           <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">PROX_PRIMARY_SCH</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb24-63"><a href="#cb24-63"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, </span>
<span id="cb24-64"><a href="#cb24-64"></a>                 <span class="at">color=</span><span class="st">"black"</span>, </span>
<span id="cb24-65"><a href="#cb24-65"></a>                 <span class="at">fill=</span><span class="st">"light blue"</span>)</span>
<span id="cb24-66"><a href="#cb24-66"></a></span>
<span id="cb24-67"><a href="#cb24-67"></a>PROX_TOP_PRIMARY_SCH <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>condo_resale.sf, </span>
<span id="cb24-68"><a href="#cb24-68"></a>                               <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">PROX_TOP_PRIMARY_SCH</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb24-69"><a href="#cb24-69"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, </span>
<span id="cb24-70"><a href="#cb24-70"></a>                 <span class="at">color=</span><span class="st">"black"</span>, </span>
<span id="cb24-71"><a href="#cb24-71"></a>                 <span class="at">fill=</span><span class="st">"light blue"</span>)</span>
<span id="cb24-72"><a href="#cb24-72"></a></span>
<span id="cb24-73"><a href="#cb24-73"></a><span class="fu">ggarrange</span>(AREA_SQM, AGE, PROX_CBD, PROX_CHILDCARE, </span>
<span id="cb24-74"><a href="#cb24-74"></a>          PROX_ELDERLYCARE, PROX_URA_GROWTH_AREA,</span>
<span id="cb24-75"><a href="#cb24-75"></a>          PROX_HAWKER_MARKET, PROX_KINDERGARTEN, PROX_MRT,</span>
<span id="cb24-76"><a href="#cb24-76"></a>          PROX_PARK, PROX_PRIMARY_SCH, PROX_TOP_PRIMARY_SCH,  </span>
<span id="cb24-77"><a href="#cb24-77"></a>          <span class="at">ncol =</span> <span class="dv">3</span>, <span class="at">nrow =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="In-class_Ex07_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="drawing-statistical-point-map" class="level2">
<h2 class="anchored" data-anchor-id="drawing-statistical-point-map">4.3 Drawing Statistical Point Map</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="fu">tm_shape</span>(mpsz_svy21)<span class="sc">+</span></span>
<span id="cb26-2"><a href="#cb26-2"></a>  <span class="fu">tm_polygons</span>() <span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3"></a><span class="fu">tm_shape</span>(condo_resale.sf) <span class="sc">+</span>  </span>
<span id="cb26-4"><a href="#cb26-4"></a>  <span class="fu">tm_dots</span>(<span class="at">fill =</span> <span class="st">"SELLING_PRICE"</span>,</span>
<span id="cb26-5"><a href="#cb26-5"></a>          <span class="at">fill_alpha =</span> <span class="fl">0.6</span>,</span>
<span id="cb26-6"><a href="#cb26-6"></a>          <span class="at">size =</span> <span class="fl">0.5</span>,</span>
<span id="cb26-7"><a href="#cb26-7"></a>          <span class="at">fill.scale =</span> <span class="fu">tm_scale_intervals</span>(</span>
<span id="cb26-8"><a href="#cb26-8"></a>            <span class="at">style=</span><span class="st">"quantile"</span>)) <span class="sc">+</span></span>
<span id="cb26-9"><a href="#cb26-9"></a>  <span class="fu">tm_view</span>(<span class="at">set_zoom_limits =</span> <span class="fu">c</span>(<span class="dv">11</span>,<span class="dv">14</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="In-class_Ex07_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="hedonic-pricing-modelling-in-r" class="level1">
<h1>5. Hedonic Pricing Modelling in R</h1>
<section id="simple-linear-regression-method" class="level2">
<h2 class="anchored" data-anchor-id="simple-linear-regression-method">5.1 Simple Linear Regression Method</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a>condo.slr <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula=</span>SELLING_PRICE <span class="sc">~</span> AREA_SQM, </span>
<span id="cb28-2"><a href="#cb28-2"></a>                <span class="at">data =</span> condo_resale.sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a><span class="fu">summary</span>(condo.slr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = SELLING_PRICE ~ AREA_SQM, data = condo_resale.sf)

Residuals:
     Min       1Q   Median       3Q      Max 
-3695815  -391764   -87517   258900 13503875 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -258121.1    63517.2  -4.064 5.09e-05 ***
AREA_SQM      14719.0      428.1  34.381  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 942700 on 1434 degrees of freedom
Multiple R-squared:  0.4518,    Adjusted R-squared:  0.4515 
F-statistic:  1182 on 1 and 1434 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>condo_resale.sf,  </span>
<span id="cb31-2"><a href="#cb31-2"></a>       <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">AREA_SQM</span><span class="st">`</span>, <span class="at">y=</span><span class="st">`</span><span class="at">SELLING_PRICE</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="In-class_Ex07_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="multiple-linear-regression-method" class="level2">
<h2 class="anchored" data-anchor-id="multiple-linear-regression-method">5.2 Multiple Linear Regression Method</h2>
<section id="visualising-the-relationships-of-the-independent-variables" class="level3">
<h3 class="anchored" data-anchor-id="visualising-the-relationships-of-the-independent-variables">5.2.1 Visualising the relationships of the independent variables</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1"></a><span class="fu">corrplot</span>(<span class="fu">cor</span>(condo_resale[, <span class="dv">5</span><span class="sc">:</span><span class="dv">23</span>]), </span>
<span id="cb32-2"><a href="#cb32-2"></a>         <span class="at">diag =</span> <span class="cn">FALSE</span>, </span>
<span id="cb32-3"><a href="#cb32-3"></a>         <span class="at">order =</span> <span class="st">"AOE"</span>,</span>
<span id="cb32-4"><a href="#cb32-4"></a>         <span class="at">tl.pos =</span> <span class="st">"td"</span>, </span>
<span id="cb32-5"><a href="#cb32-5"></a>         <span class="at">tl.cex =</span> <span class="fl">0.5</span>, </span>
<span id="cb32-6"><a href="#cb32-6"></a>         <span class="at">method =</span> <span class="st">"number"</span>, </span>
<span id="cb32-7"><a href="#cb32-7"></a>         <span class="at">type =</span> <span class="st">"upper"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="In-class_Ex07_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="building-a-hedonic-pricing-model-using-multiple-linear-regression-method" class="level2">
<h2 class="anchored" data-anchor-id="building-a-hedonic-pricing-model-using-multiple-linear-regression-method">5.3 Building a hedonic pricing model using multiple linear regression method</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a>condo.mlr <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb33-2"><a href="#cb33-2"></a>  <span class="at">formula =</span> SELLING_PRICE <span class="sc">~</span> AREA_SQM <span class="sc">+</span> AGE  <span class="sc">+</span> </span>
<span id="cb33-3"><a href="#cb33-3"></a>    PROX_CBD <span class="sc">+</span> PROX_CHILDCARE <span class="sc">+</span> PROX_ELDERLYCARE <span class="sc">+</span></span>
<span id="cb33-4"><a href="#cb33-4"></a>    PROX_URA_GROWTH_AREA <span class="sc">+</span> PROX_HAWKER_MARKET   <span class="sc">+</span></span>
<span id="cb33-5"><a href="#cb33-5"></a>    PROX_KINDERGARTEN   <span class="sc">+</span> PROX_MRT  <span class="sc">+</span> PROX_PARK <span class="sc">+</span></span>
<span id="cb33-6"><a href="#cb33-6"></a>    PROX_PRIMARY_SCH <span class="sc">+</span> PROX_TOP_PRIMARY_SCH <span class="sc">+</span></span>
<span id="cb33-7"><a href="#cb33-7"></a>    PROX_SHOPPING_MALL  <span class="sc">+</span> PROX_SUPERMARKET <span class="sc">+</span> </span>
<span id="cb33-8"><a href="#cb33-8"></a>    PROX_BUS_STOP   <span class="sc">+</span> NO_Of_UNITS <span class="sc">+</span> </span>
<span id="cb33-9"><a href="#cb33-9"></a>    FAMILY_FRIENDLY <span class="sc">+</span> FREEHOLD, </span>
<span id="cb33-10"><a href="#cb33-10"></a>  <span class="at">data=</span>condo_resale.sf)</span>
<span id="cb33-11"><a href="#cb33-11"></a><span class="fu">summary</span>(condo.mlr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = SELLING_PRICE ~ AREA_SQM + AGE + PROX_CBD + PROX_CHILDCARE + 
    PROX_ELDERLYCARE + PROX_URA_GROWTH_AREA + PROX_HAWKER_MARKET + 
    PROX_KINDERGARTEN + PROX_MRT + PROX_PARK + PROX_PRIMARY_SCH + 
    PROX_TOP_PRIMARY_SCH + PROX_SHOPPING_MALL + PROX_SUPERMARKET + 
    PROX_BUS_STOP + NO_Of_UNITS + FAMILY_FRIENDLY + FREEHOLD, 
    data = condo_resale.sf)

Residuals:
     Min       1Q   Median       3Q      Max 
-3475964  -293923   -23069   241043 12260381 

Coefficients:
                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           481728.40  121441.01   3.967 7.65e-05 ***
AREA_SQM               12708.32     369.59  34.385  &lt; 2e-16 ***
AGE                   -24440.82    2763.16  -8.845  &lt; 2e-16 ***
PROX_CBD              -78669.78    6768.97 -11.622  &lt; 2e-16 ***
PROX_CHILDCARE       -351617.91  109467.25  -3.212  0.00135 ** 
PROX_ELDERLYCARE      171029.42   42110.51   4.061 5.14e-05 ***
PROX_URA_GROWTH_AREA   38474.53   12523.57   3.072  0.00217 ** 
PROX_HAWKER_MARKET     23746.10   29299.76   0.810  0.41782    
PROX_KINDERGARTEN     147468.99   82668.87   1.784  0.07466 .  
PROX_MRT             -314599.68   57947.44  -5.429 6.66e-08 ***
PROX_PARK             563280.50   66551.68   8.464  &lt; 2e-16 ***
PROX_PRIMARY_SCH      180186.08   65237.95   2.762  0.00582 ** 
PROX_TOP_PRIMARY_SCH    2280.04   20410.43   0.112  0.91107    
PROX_SHOPPING_MALL   -206604.06   42840.60  -4.823 1.57e-06 ***
PROX_SUPERMARKET      -44991.80   77082.64  -0.584  0.55953    
PROX_BUS_STOP         683121.35  138353.28   4.938 8.85e-07 ***
NO_Of_UNITS             -231.18      89.03  -2.597  0.00951 ** 
FAMILY_FRIENDLY       140340.77   47020.55   2.985  0.00289 ** 
FREEHOLD              359913.01   49220.22   7.312 4.38e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 755800 on 1417 degrees of freedom
Multiple R-squared:  0.6518,    Adjusted R-squared:  0.6474 
F-statistic: 147.4 on 18 and 1417 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="revising-the-model" class="level2">
<h2 class="anchored" data-anchor-id="revising-the-model">5.4 Revising the model</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1"></a>condo.mlr1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb35-2"><a href="#cb35-2"></a>  <span class="at">formula =</span> SELLING_PRICE <span class="sc">~</span> AREA_SQM <span class="sc">+</span> AGE <span class="sc">+</span> </span>
<span id="cb35-3"><a href="#cb35-3"></a>    PROX_CBD <span class="sc">+</span> PROX_CHILDCARE <span class="sc">+</span> PROX_MRT <span class="sc">+</span></span>
<span id="cb35-4"><a href="#cb35-4"></a>    PROX_ELDERLYCARE    <span class="sc">+</span> PROX_URA_GROWTH_AREA <span class="sc">+</span></span>
<span id="cb35-5"><a href="#cb35-5"></a>    PROX_PARK   <span class="sc">+</span> PROX_PRIMARY_SCH <span class="sc">+</span> </span>
<span id="cb35-6"><a href="#cb35-6"></a>    PROX_SHOPPING_MALL  <span class="sc">+</span> PROX_BUS_STOP <span class="sc">+</span> </span>
<span id="cb35-7"><a href="#cb35-7"></a>    NO_Of_UNITS <span class="sc">+</span> FAMILY_FRIENDLY <span class="sc">+</span> FREEHOLD,</span>
<span id="cb35-8"><a href="#cb35-8"></a>  <span class="at">data=</span>condo_resale.sf)</span>
<span id="cb35-9"><a href="#cb35-9"></a><span class="fu">summary</span>(condo.mlr1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = SELLING_PRICE ~ AREA_SQM + AGE + PROX_CBD + PROX_CHILDCARE + 
    PROX_MRT + PROX_ELDERLYCARE + PROX_URA_GROWTH_AREA + PROX_PARK + 
    PROX_PRIMARY_SCH + PROX_SHOPPING_MALL + PROX_BUS_STOP + NO_Of_UNITS + 
    FAMILY_FRIENDLY + FREEHOLD, data = condo_resale.sf)

Residuals:
     Min       1Q   Median       3Q      Max 
-3470778  -298119   -23481   248917 12234210 

Coefficients:
                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           527633.22  108183.22   4.877 1.20e-06 ***
AREA_SQM               12777.52     367.48  34.771  &lt; 2e-16 ***
AGE                   -24687.74    2754.84  -8.962  &lt; 2e-16 ***
PROX_CBD              -77131.32    5763.12 -13.384  &lt; 2e-16 ***
PROX_CHILDCARE       -318472.75  107959.51  -2.950 0.003231 ** 
PROX_MRT             -294745.11   56916.37  -5.179 2.56e-07 ***
PROX_ELDERLYCARE      185575.62   39901.86   4.651 3.61e-06 ***
PROX_URA_GROWTH_AREA   39163.25   11754.83   3.332 0.000885 ***
PROX_PARK             570504.81   65507.03   8.709  &lt; 2e-16 ***
PROX_PRIMARY_SCH      159856.14   60234.60   2.654 0.008046 ** 
PROX_SHOPPING_MALL   -220947.25   36561.83  -6.043 1.93e-09 ***
PROX_BUS_STOP         682482.22  134513.24   5.074 4.42e-07 ***
NO_Of_UNITS             -245.48      87.95  -2.791 0.005321 ** 
FAMILY_FRIENDLY       146307.58   46893.02   3.120 0.001845 ** 
FREEHOLD              350599.81   48506.48   7.228 7.98e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 756000 on 1421 degrees of freedom
Multiple R-squared:  0.6507,    Adjusted R-squared:  0.6472 
F-statistic: 189.1 on 14 and 1421 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="preparing-publication-quality-table-gtsummary-method" class="level2">
<h2 class="anchored" data-anchor-id="preparing-publication-quality-table-gtsummary-method">5.5 Preparing Publication Quality Table: gtsummary method</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1"></a><span class="fu">tbl_regression</span>(condo.mlr1, <span class="at">intercept =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="addfkdinlm" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#addfkdinlm table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#addfkdinlm thead, #addfkdinlm tbody, #addfkdinlm tfoot, #addfkdinlm tr, #addfkdinlm td, #addfkdinlm th {
  border-style: none;
}

#addfkdinlm p {
  margin: 0;
  padding: 0;
}

#addfkdinlm .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#addfkdinlm .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#addfkdinlm .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#addfkdinlm .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#addfkdinlm .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#addfkdinlm .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#addfkdinlm .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#addfkdinlm .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#addfkdinlm .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#addfkdinlm .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#addfkdinlm .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#addfkdinlm .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#addfkdinlm .gt_spanner_row {
  border-bottom-style: hidden;
}

#addfkdinlm .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#addfkdinlm .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#addfkdinlm .gt_from_md > :first-child {
  margin-top: 0;
}

#addfkdinlm .gt_from_md > :last-child {
  margin-bottom: 0;
}

#addfkdinlm .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#addfkdinlm .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#addfkdinlm .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#addfkdinlm .gt_row_group_first td {
  border-top-width: 2px;
}

#addfkdinlm .gt_row_group_first th {
  border-top-width: 2px;
}

#addfkdinlm .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#addfkdinlm .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#addfkdinlm .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#addfkdinlm .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#addfkdinlm .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#addfkdinlm .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#addfkdinlm .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#addfkdinlm .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#addfkdinlm .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#addfkdinlm .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#addfkdinlm .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#addfkdinlm .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#addfkdinlm .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#addfkdinlm .gt_left {
  text-align: left;
}

#addfkdinlm .gt_center {
  text-align: center;
}

#addfkdinlm .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#addfkdinlm .gt_font_normal {
  font-weight: normal;
}

#addfkdinlm .gt_font_bold {
  font-weight: bold;
}

#addfkdinlm .gt_font_italic {
  font-style: italic;
}

#addfkdinlm .gt_super {
  font-size: 65%;
}

#addfkdinlm .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#addfkdinlm .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#addfkdinlm .gt_indent_1 {
  text-indent: 5px;
}

#addfkdinlm .gt_indent_2 {
  text-indent: 10px;
}

#addfkdinlm .gt_indent_3 {
  text-indent: 15px;
}

#addfkdinlm .gt_indent_4 {
  text-indent: 20px;
}

#addfkdinlm .gt_indent_5 {
  text-indent: 25px;
}

#addfkdinlm .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#addfkdinlm div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="header gt_col_headings">
<th id="label" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"><strong>Characteristic</strong></th>
<th id="estimate" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>Beta</strong></th>
<th id="conf.low" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>95% CI</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
<th id="p.value" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>p-value</strong></th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="label">(Intercept)</td>
<td class="gt_row gt_center" headers="estimate">527,633</td>
<td class="gt_row gt_center" headers="conf.low">315,417, 739,849</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">AREA_SQM</td>
<td class="gt_row gt_center" headers="estimate">12,778</td>
<td class="gt_row gt_center" headers="conf.low">12,057, 13,498</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">AGE</td>
<td class="gt_row gt_center" headers="estimate">-24,688</td>
<td class="gt_row gt_center" headers="conf.low">-30,092, -19,284</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">PROX_CBD</td>
<td class="gt_row gt_center" headers="estimate">-77,131</td>
<td class="gt_row gt_center" headers="conf.low">-88,436, -65,826</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">PROX_CHILDCARE</td>
<td class="gt_row gt_center" headers="estimate">-318,473</td>
<td class="gt_row gt_center" headers="conf.low">-530,250, -106,696</td>
<td class="gt_row gt_center" headers="p.value">0.003</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">PROX_MRT</td>
<td class="gt_row gt_center" headers="estimate">-294,745</td>
<td class="gt_row gt_center" headers="conf.low">-406,394, -183,096</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">PROX_ELDERLYCARE</td>
<td class="gt_row gt_center" headers="estimate">185,576</td>
<td class="gt_row gt_center" headers="conf.low">107,303, 263,849</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">PROX_URA_GROWTH_AREA</td>
<td class="gt_row gt_center" headers="estimate">39,163</td>
<td class="gt_row gt_center" headers="conf.low">16,105, 62,222</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">PROX_PARK</td>
<td class="gt_row gt_center" headers="estimate">570,505</td>
<td class="gt_row gt_center" headers="conf.low">442,004, 699,006</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">PROX_PRIMARY_SCH</td>
<td class="gt_row gt_center" headers="estimate">159,856</td>
<td class="gt_row gt_center" headers="conf.low">41,698, 278,014</td>
<td class="gt_row gt_center" headers="p.value">0.008</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">PROX_SHOPPING_MALL</td>
<td class="gt_row gt_center" headers="estimate">-220,947</td>
<td class="gt_row gt_center" headers="conf.low">-292,668, -149,226</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">PROX_BUS_STOP</td>
<td class="gt_row gt_center" headers="estimate">682,482</td>
<td class="gt_row gt_center" headers="conf.low">418,616, 946,348</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">NO_Of_UNITS</td>
<td class="gt_row gt_center" headers="estimate">-245</td>
<td class="gt_row gt_center" headers="conf.low">-418, -73</td>
<td class="gt_row gt_center" headers="p.value">0.005</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">FAMILY_FRIENDLY</td>
<td class="gt_row gt_center" headers="estimate">146,308</td>
<td class="gt_row gt_center" headers="conf.low">54,321, 238,295</td>
<td class="gt_row gt_center" headers="p.value">0.002</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">FREEHOLD</td>
<td class="gt_row gt_center" headers="estimate">350,600</td>
<td class="gt_row gt_center" headers="conf.low">255,448, 445,752</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
</tbody><tfoot class="gt_footnotes">
<tr class="even">
<td colspan="4" class="gt_footnote"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span> CI = Confidence Interval</td>
</tr>
</tfoot>

</table>

</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1"></a><span class="fu">tbl_regression</span>(condo.mlr1, </span>
<span id="cb38-2"><a href="#cb38-2"></a>               <span class="at">intercept =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb38-3"><a href="#cb38-3"></a>  <span class="fu">add_glance_source_note</span>(</span>
<span id="cb38-4"><a href="#cb38-4"></a>    <span class="at">label =</span> <span class="fu">list</span>(sigma <span class="sc">~</span> <span class="st">"\U03C3"</span>),</span>
<span id="cb38-5"><a href="#cb38-5"></a>    <span class="at">include =</span> <span class="fu">c</span>(r.squared, adj.r.squared, </span>
<span id="cb38-6"><a href="#cb38-6"></a>                AIC, statistic,</span>
<span id="cb38-7"><a href="#cb38-7"></a>                p.value, sigma))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="hcybprzrdu" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#hcybprzrdu table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#hcybprzrdu thead, #hcybprzrdu tbody, #hcybprzrdu tfoot, #hcybprzrdu tr, #hcybprzrdu td, #hcybprzrdu th {
  border-style: none;
}

#hcybprzrdu p {
  margin: 0;
  padding: 0;
}

#hcybprzrdu .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#hcybprzrdu .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#hcybprzrdu .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#hcybprzrdu .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#hcybprzrdu .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hcybprzrdu .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hcybprzrdu .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hcybprzrdu .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#hcybprzrdu .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#hcybprzrdu .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#hcybprzrdu .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#hcybprzrdu .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#hcybprzrdu .gt_spanner_row {
  border-bottom-style: hidden;
}

#hcybprzrdu .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#hcybprzrdu .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#hcybprzrdu .gt_from_md > :first-child {
  margin-top: 0;
}

#hcybprzrdu .gt_from_md > :last-child {
  margin-bottom: 0;
}

#hcybprzrdu .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#hcybprzrdu .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#hcybprzrdu .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#hcybprzrdu .gt_row_group_first td {
  border-top-width: 2px;
}

#hcybprzrdu .gt_row_group_first th {
  border-top-width: 2px;
}

#hcybprzrdu .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hcybprzrdu .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#hcybprzrdu .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#hcybprzrdu .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hcybprzrdu .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hcybprzrdu .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#hcybprzrdu .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#hcybprzrdu .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#hcybprzrdu .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hcybprzrdu .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hcybprzrdu .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hcybprzrdu .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hcybprzrdu .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hcybprzrdu .gt_left {
  text-align: left;
}

#hcybprzrdu .gt_center {
  text-align: center;
}

#hcybprzrdu .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#hcybprzrdu .gt_font_normal {
  font-weight: normal;
}

#hcybprzrdu .gt_font_bold {
  font-weight: bold;
}

#hcybprzrdu .gt_font_italic {
  font-style: italic;
}

#hcybprzrdu .gt_super {
  font-size: 65%;
}

#hcybprzrdu .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#hcybprzrdu .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#hcybprzrdu .gt_indent_1 {
  text-indent: 5px;
}

#hcybprzrdu .gt_indent_2 {
  text-indent: 10px;
}

#hcybprzrdu .gt_indent_3 {
  text-indent: 15px;
}

#hcybprzrdu .gt_indent_4 {
  text-indent: 20px;
}

#hcybprzrdu .gt_indent_5 {
  text-indent: 25px;
}

#hcybprzrdu .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#hcybprzrdu div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="label"><span data-qmd-base64="PHN0cm9uZz5DaGFyYWN0ZXJpc3RpYzwvc3Ryb25nPg=="><span class="gt_from_md"><strong>Characteristic</strong></span></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="estimate"><span data-qmd-base64="PHN0cm9uZz5CZXRhPC9zdHJvbmc+"><span class="gt_from_md"><strong>Beta</strong></span></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="conf.low"><span data-qmd-base64="PHN0cm9uZz45NSUgQ0k8L3N0cm9uZz4="><span class="gt_from_md"><strong>95% CI</strong></span></span><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="p.value"><span data-qmd-base64="PHN0cm9uZz5wLXZhbHVlPC9zdHJvbmc+"><span class="gt_from_md"><strong>p-value</strong></span></span></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">(Intercept)</td>
<td headers="estimate" class="gt_row gt_center">527,633</td>
<td headers="conf.low" class="gt_row gt_center">315,417, 739,849</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">AREA_SQM</td>
<td headers="estimate" class="gt_row gt_center">12,778</td>
<td headers="conf.low" class="gt_row gt_center">12,057, 13,498</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">AGE</td>
<td headers="estimate" class="gt_row gt_center">-24,688</td>
<td headers="conf.low" class="gt_row gt_center">-30,092, -19,284</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">PROX_CBD</td>
<td headers="estimate" class="gt_row gt_center">-77,131</td>
<td headers="conf.low" class="gt_row gt_center">-88,436, -65,826</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">PROX_CHILDCARE</td>
<td headers="estimate" class="gt_row gt_center">-318,473</td>
<td headers="conf.low" class="gt_row gt_center">-530,250, -106,696</td>
<td headers="p.value" class="gt_row gt_center">0.003</td></tr>
    <tr><td headers="label" class="gt_row gt_left">PROX_MRT</td>
<td headers="estimate" class="gt_row gt_center">-294,745</td>
<td headers="conf.low" class="gt_row gt_center">-406,394, -183,096</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">PROX_ELDERLYCARE</td>
<td headers="estimate" class="gt_row gt_center">185,576</td>
<td headers="conf.low" class="gt_row gt_center">107,303, 263,849</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">PROX_URA_GROWTH_AREA</td>
<td headers="estimate" class="gt_row gt_center">39,163</td>
<td headers="conf.low" class="gt_row gt_center">16,105, 62,222</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">PROX_PARK</td>
<td headers="estimate" class="gt_row gt_center">570,505</td>
<td headers="conf.low" class="gt_row gt_center">442,004, 699,006</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">PROX_PRIMARY_SCH</td>
<td headers="estimate" class="gt_row gt_center">159,856</td>
<td headers="conf.low" class="gt_row gt_center">41,698, 278,014</td>
<td headers="p.value" class="gt_row gt_center">0.008</td></tr>
    <tr><td headers="label" class="gt_row gt_left">PROX_SHOPPING_MALL</td>
<td headers="estimate" class="gt_row gt_center">-220,947</td>
<td headers="conf.low" class="gt_row gt_center">-292,668, -149,226</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">PROX_BUS_STOP</td>
<td headers="estimate" class="gt_row gt_center">682,482</td>
<td headers="conf.low" class="gt_row gt_center">418,616, 946,348</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">NO_Of_UNITS</td>
<td headers="estimate" class="gt_row gt_center">-245</td>
<td headers="conf.low" class="gt_row gt_center">-418, -73</td>
<td headers="p.value" class="gt_row gt_center">0.005</td></tr>
    <tr><td headers="label" class="gt_row gt_left">FAMILY_FRIENDLY</td>
<td headers="estimate" class="gt_row gt_center">146,308</td>
<td headers="conf.low" class="gt_row gt_center">54,321, 238,295</td>
<td headers="p.value" class="gt_row gt_center">0.002</td></tr>
    <tr><td headers="label" class="gt_row gt_left">FREEHOLD</td>
<td headers="estimate" class="gt_row gt_center">350,600</td>
<td headers="conf.low" class="gt_row gt_center">255,448, 445,752</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
  </tbody>
  <tfoot class="gt_sourcenotes">
    <tr>
      <td class="gt_sourcenote" colspan="4"><span data-qmd-base64="UsKyID0gMC42NTE7IEFkanVzdGVkIFLCsiA9IDAuNjQ3OyBBSUMgPSA0Miw5Njc7IFN0YXRpc3RpYyA9IDE4OTsgcC12YWx1ZSA9ICZsdDswLjAwMTsgz4MgPSA3NTUsOTU3"><span class="gt_from_md">R² = 0.651; Adjusted R² = 0.647; AIC = 42,967; Statistic = 189; p-value = &lt;0.001; σ = 755,957</span></span></td>
    </tr>
  </tfoot>
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="4"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span> <span data-qmd-base64="Q0kgPSBDb25maWRlbmNlIEludGVydmFs"><span class="gt_from_md">CI = Confidence Interval</span></span></td>
    </tr>
  </tfoot>
</table>
</div>
</div>
</div>
</section>
<section id="regression-diagnostics" class="level2">
<h2 class="anchored" data-anchor-id="regression-diagnostics">5.6 Regression Diagnostics</h2>
<section id="multicollinearity-test" class="level3">
<h3 class="anchored" data-anchor-id="multicollinearity-test">5.6.1 Multicollinearity test</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1"></a><span class="fu">check_collinearity</span>(condo.mlr1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Check for Multicollinearity

Low Correlation

                 Term  VIF   VIF 95% CI Increased SE Tolerance Tolerance 95% CI
             AREA_SQM 1.15 [1.09, 1.23]         1.07      0.87     [0.81, 0.92]
                  AGE 1.41 [1.33, 1.52]         1.19      0.71     [0.66, 0.75]
             PROX_CBD 1.57 [1.47, 1.69]         1.25      0.64     [0.59, 0.68]
       PROX_CHILDCARE 3.26 [3.00, 3.56]         1.81      0.31     [0.28, 0.33]
             PROX_MRT 1.91 [1.78, 2.07]         1.38      0.52     [0.48, 0.56]
     PROX_ELDERLYCARE 1.52 [1.42, 1.63]         1.23      0.66     [0.61, 0.70]
 PROX_URA_GROWTH_AREA 1.33 [1.26, 1.43]         1.15      0.75     [0.70, 0.80]
            PROX_PARK 1.21 [1.15, 1.29]         1.10      0.83     [0.77, 0.87]
     PROX_PRIMARY_SCH 2.21 [2.05, 2.40]         1.49      0.45     [0.42, 0.49]
   PROX_SHOPPING_MALL 1.48 [1.39, 1.60]         1.22      0.67     [0.63, 0.72]
        PROX_BUS_STOP 2.85 [2.62, 3.10]         1.69      0.35     [0.32, 0.38]
          NO_Of_UNITS 1.45 [1.36, 1.56]         1.20      0.69     [0.64, 0.73]
      FAMILY_FRIENDLY 1.38 [1.30, 1.48]         1.17      0.72     [0.67, 0.77]
             FREEHOLD 1.44 [1.36, 1.55]         1.20      0.69     [0.65, 0.74]</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1"></a>mlr.vif <span class="ot">&lt;-</span> <span class="fu">check_collinearity</span>(condo.mlr1)</span>
<span id="cb41-2"><a href="#cb41-2"></a><span class="fu">plot</span>(mlr.vif)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="In-class_Ex07_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="test-for-non-linearity" class="level3">
<h3 class="anchored" data-anchor-id="test-for-non-linearity">5.6.2 Test for Non-Linearity</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1"></a><span class="fu">check_model</span>(condo.mlr1,</span>
<span id="cb42-2"><a href="#cb42-2"></a>            <span class="at">check =</span> <span class="st">"linearity"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="In-class_Ex07_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="test-for-normality-assumption" class="level3">
<h3 class="anchored" data-anchor-id="test-for-normality-assumption">5.6.3 Test for Normality Assumption</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1"></a><span class="fu">check_normality</span>(condo.mlr1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Warning: Non-normality of residuals detected (p &lt; .001).</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1"></a><span class="fu">plot</span>(<span class="fu">check_normality</span>(condo.mlr1), </span>
<span id="cb45-2"><a href="#cb45-2"></a>     <span class="at">type =</span> <span class="st">"qq"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="In-class_Ex07_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1"></a><span class="fu">check_model</span>(condo.mlr1,</span>
<span id="cb46-2"><a href="#cb46-2"></a>            <span class="at">check=</span> <span class="st">"normality"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="In-class_Ex07_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="testing-for-spatial-autocorrelation" class="level3">
<h3 class="anchored" data-anchor-id="testing-for-spatial-autocorrelation">5.6.4 Testing for Spatial Autocorrelation</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1"></a>mlr.output <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(condo.mlr1<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1"></a>condo_resale.sf <span class="ot">&lt;-</span> <span class="fu">cbind</span>(condo_resale.sf, </span>
<span id="cb48-2"><a href="#cb48-2"></a>                        condo.mlr1<span class="sc">$</span>residuals) <span class="sc">%&gt;%</span></span>
<span id="cb48-3"><a href="#cb48-3"></a><span class="fu">rename</span>(<span class="st">`</span><span class="at">MLR_RES</span><span class="st">`</span> <span class="ot">=</span> <span class="st">`</span><span class="at">condo.mlr1.residuals</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1"></a><span class="fu">tm_shape</span>(mpsz_svy21) <span class="sc">+</span></span>
<span id="cb50-2"><a href="#cb50-2"></a>  <span class="fu">tm_polygons</span>(<span class="at">fill_alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb50-3"><a href="#cb50-3"></a><span class="fu">tm_shape</span>(condo_resale.sf) <span class="sc">+</span>  </span>
<span id="cb50-4"><a href="#cb50-4"></a>  <span class="fu">tm_dots</span>(</span>
<span id="cb50-5"><a href="#cb50-5"></a>    <span class="at">fill =</span> <span class="st">"MLR_RES"</span>,</span>
<span id="cb50-6"><a href="#cb50-6"></a>    <span class="at">size =</span> <span class="fl">0.7</span>,</span>
<span id="cb50-7"><a href="#cb50-7"></a>    <span class="at">col =</span> <span class="st">"black"</span>,</span>
<span id="cb50-8"><a href="#cb50-8"></a>    <span class="at">fill.scale =</span> <span class="fu">tm_scale</span>(</span>
<span id="cb50-9"><a href="#cb50-9"></a>      <span class="at">n =</span> <span class="dv">10</span>,</span>
<span id="cb50-10"><a href="#cb50-10"></a>      <span class="at">values =</span> <span class="fu">rev</span>(</span>
<span id="cb50-11"><a href="#cb50-11"></a>        <span class="fu">brewer.pal</span>(<span class="dv">11</span>, <span class="st">"RdBu"</span>)),</span>
<span id="cb50-12"><a href="#cb50-12"></a>      <span class="at">style =</span> <span class="st">"quantile"</span>,</span>
<span id="cb50-13"><a href="#cb50-13"></a>      <span class="at">midpoint =</span> <span class="cn">NA</span>),</span>
<span id="cb50-14"><a href="#cb50-14"></a>    <span class="at">fill.legend =</span> <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"Residuals"</span>)</span>
<span id="cb50-15"><a href="#cb50-15"></a>  ) <span class="sc">+</span> </span>
<span id="cb50-16"><a href="#cb50-16"></a>  <span class="fu">tm_title</span>(<span class="st">"LM Residuals (Quantile Classification)"</span>) <span class="sc">+</span></span>
<span id="cb50-17"><a href="#cb50-17"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.outside =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb50-18"><a href="#cb50-18"></a>  <span class="fu">tm_view</span>(<span class="at">set_zoom_limits =</span> <span class="fu">c</span>(<span class="dv">11</span>,<span class="dv">14</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="In-class_Ex07_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1"></a>condo_resale.sf <span class="ot">&lt;-</span> condo_resale.sf <span class="sc">%&gt;%</span> </span>
<span id="cb52-2"><a href="#cb52-2"></a>  <span class="fu">mutate</span>(</span>
<span id="cb52-3"><a href="#cb52-3"></a>    <span class="at">nb =</span> <span class="fu">st_dist_band</span>(</span>
<span id="cb52-4"><a href="#cb52-4"></a>      <span class="fu">st_geometry</span>(geometry), </span>
<span id="cb52-5"><a href="#cb52-5"></a>                 <span class="at">upper =</span> <span class="dv">1500</span>),</span>
<span id="cb52-6"><a href="#cb52-6"></a>    <span class="at">wt =</span> <span class="fu">st_weights</span>(</span>
<span id="cb52-7"><a href="#cb52-7"></a>      nb, <span class="at">style =</span> <span class="st">"W"</span>),</span>
<span id="cb52-8"><a href="#cb52-8"></a>    <span class="at">.before =</span> <span class="dv">1</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb53-2"><a href="#cb53-2"></a><span class="fu">global_moran_perm</span>(</span>
<span id="cb53-3"><a href="#cb53-3"></a>  condo_resale.sf<span class="sc">$</span>MLR_RES, </span>
<span id="cb53-4"><a href="#cb53-4"></a>  <span class="at">nb =</span> condo_resale.sf<span class="sc">$</span>nb, </span>
<span id="cb53-5"><a href="#cb53-5"></a>  <span class="at">wt =</span> condo_resale.sf<span class="sc">$</span>wt,</span>
<span id="cb53-6"><a href="#cb53-6"></a>  <span class="at">alternative =</span> <span class="st">"two.sided"</span>, </span>
<span id="cb53-7"><a href="#cb53-7"></a>  <span class="at">nsim =</span> <span class="dv">499</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Monte-Carlo simulation of Moran I

data:  x 
weights: listw  
number of simulations + 1: 500 

statistic = 0.14389, observed rank = 500, p-value &lt; 2.2e-16
alternative hypothesis: two.sided</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="building-hedonic-pricing-models-using-gwmodel" class="level1">
<h1>6. Building Hedonic Pricing Models using GWmodel</h1>
<section id="building-fixed-bandwidth-gwr-model" class="level2">
<h2 class="anchored" data-anchor-id="building-fixed-bandwidth-gwr-model">6.1 Building Fixed Bandwidth GWR Model</h2>
<section id="computing-fixed-bandwith" class="level3">
<h3 class="anchored" data-anchor-id="computing-fixed-bandwith">6.1.1 Computing fixed bandwith</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1"></a>bw.fixed <span class="ot">&lt;-</span> <span class="fu">bw.gwr</span>(</span>
<span id="cb55-2"><a href="#cb55-2"></a>  <span class="at">formula =</span> SELLING_PRICE <span class="sc">~</span> AREA_SQM <span class="sc">+</span> AGE  <span class="sc">+</span> </span>
<span id="cb55-3"><a href="#cb55-3"></a>    PROX_CBD <span class="sc">+</span> PROX_CHILDCARE <span class="sc">+</span> PROX_ELDERLYCARE    <span class="sc">+</span></span>
<span id="cb55-4"><a href="#cb55-4"></a>    PROX_URA_GROWTH_AREA <span class="sc">+</span> PROX_MRT <span class="sc">+</span> PROX_PARK <span class="sc">+</span> </span>
<span id="cb55-5"><a href="#cb55-5"></a>    PROX_PRIMARY_SCH <span class="sc">+</span> PROX_SHOPPING_MALL   <span class="sc">+</span> </span>
<span id="cb55-6"><a href="#cb55-6"></a>    PROX_BUS_STOP   <span class="sc">+</span> NO_Of_UNITS <span class="sc">+</span> FAMILY_FRIENDLY <span class="sc">+</span> </span>
<span id="cb55-7"><a href="#cb55-7"></a>    FREEHOLD, </span>
<span id="cb55-8"><a href="#cb55-8"></a>  <span class="at">data=</span>condo_resale.sf, </span>
<span id="cb55-9"><a href="#cb55-9"></a>  <span class="at">approach=</span><span class="st">"CV"</span>, </span>
<span id="cb55-10"><a href="#cb55-10"></a>  <span class="at">kernel=</span><span class="st">"gaussian"</span>, </span>
<span id="cb55-11"><a href="#cb55-11"></a>  <span class="at">adaptive=</span><span class="cn">FALSE</span>, </span>
<span id="cb55-12"><a href="#cb55-12"></a>  <span class="at">longlat=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Fixed bandwidth: 17660.96 CV score: 8.259118e+14 
Fixed bandwidth: 10917.26 CV score: 7.970454e+14 
Fixed bandwidth: 6749.419 CV score: 7.273273e+14 
Fixed bandwidth: 4173.553 CV score: 6.300006e+14 
Fixed bandwidth: 2581.58 CV score: 5.404958e+14 
Fixed bandwidth: 1597.687 CV score: 4.857515e+14 
Fixed bandwidth: 989.6077 CV score: 4.722431e+14 
Fixed bandwidth: 613.7939 CV score: 1.377823e+16 
Fixed bandwidth: 1221.873 CV score: 4.778717e+14 
Fixed bandwidth: 846.0596 CV score: 4.791629e+14 
Fixed bandwidth: 1078.325 CV score: 4.751406e+14 
Fixed bandwidth: 934.7772 CV score: 4.72518e+14 
Fixed bandwidth: 1023.495 CV score: 4.730305e+14 
Fixed bandwidth: 968.6643 CV score: 4.721317e+14 
Fixed bandwidth: 955.7206 CV score: 4.722072e+14 
Fixed bandwidth: 976.6639 CV score: 4.721387e+14 
Fixed bandwidth: 963.7202 CV score: 4.721484e+14 
Fixed bandwidth: 971.7199 CV score: 4.721293e+14 
Fixed bandwidth: 973.6083 CV score: 4.721309e+14 
Fixed bandwidth: 970.5527 CV score: 4.721295e+14 
Fixed bandwidth: 972.4412 CV score: 4.721296e+14 
Fixed bandwidth: 971.2741 CV score: 4.721292e+14 
Fixed bandwidth: 970.9985 CV score: 4.721293e+14 
Fixed bandwidth: 971.4443 CV score: 4.721292e+14 
Fixed bandwidth: 971.5496 CV score: 4.721293e+14 
Fixed bandwidth: 971.3793 CV score: 4.721292e+14 
Fixed bandwidth: 971.3391 CV score: 4.721292e+14 
Fixed bandwidth: 971.3143 CV score: 4.721292e+14 
Fixed bandwidth: 971.3545 CV score: 4.721292e+14 
Fixed bandwidth: 971.3296 CV score: 4.721292e+14 
Fixed bandwidth: 971.345 CV score: 4.721292e+14 
Fixed bandwidth: 971.3355 CV score: 4.721292e+14 
Fixed bandwidth: 971.3413 CV score: 4.721292e+14 
Fixed bandwidth: 971.3377 CV score: 4.721292e+14 
Fixed bandwidth: 971.34 CV score: 4.721292e+14 
Fixed bandwidth: 971.3405 CV score: 4.721292e+14 
Fixed bandwidth: 971.3408 CV score: 4.721292e+14 
Fixed bandwidth: 971.3403 CV score: 4.721292e+14 
Fixed bandwidth: 971.3406 CV score: 4.721292e+14 
Fixed bandwidth: 971.3404 CV score: 4.721292e+14 
Fixed bandwidth: 971.3405 CV score: 4.721292e+14 
Fixed bandwidth: 971.3405 CV score: 4.721292e+14 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1"></a>bw.fixed <span class="ot">&lt;-</span> <span class="fu">bw.gwr</span>(</span>
<span id="cb57-2"><a href="#cb57-2"></a>  <span class="at">formula =</span> SELLING_PRICE <span class="sc">~</span> AREA_SQM <span class="sc">+</span> AGE  <span class="sc">+</span> </span>
<span id="cb57-3"><a href="#cb57-3"></a>    PROX_CBD <span class="sc">+</span> PROX_CHILDCARE <span class="sc">+</span> PROX_ELDERLYCARE    <span class="sc">+</span></span>
<span id="cb57-4"><a href="#cb57-4"></a>    PROX_URA_GROWTH_AREA <span class="sc">+</span> PROX_MRT <span class="sc">+</span> PROX_PARK <span class="sc">+</span> </span>
<span id="cb57-5"><a href="#cb57-5"></a>    PROX_PRIMARY_SCH <span class="sc">+</span> PROX_SHOPPING_MALL   <span class="sc">+</span> </span>
<span id="cb57-6"><a href="#cb57-6"></a>    PROX_BUS_STOP   <span class="sc">+</span> NO_Of_UNITS <span class="sc">+</span> FAMILY_FRIENDLY <span class="sc">+</span> </span>
<span id="cb57-7"><a href="#cb57-7"></a>    FREEHOLD, </span>
<span id="cb57-8"><a href="#cb57-8"></a>  <span class="at">data=</span>condo_resale.sf, </span>
<span id="cb57-9"><a href="#cb57-9"></a>  <span class="at">approach=</span><span class="st">"AIC"</span>, </span>
<span id="cb57-10"><a href="#cb57-10"></a>  <span class="at">kernel=</span><span class="st">"gaussian"</span>, </span>
<span id="cb57-11"><a href="#cb57-11"></a>  <span class="at">adaptive=</span><span class="cn">FALSE</span>, </span>
<span id="cb57-12"><a href="#cb57-12"></a>  <span class="at">longlat=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Fixed bandwidth: 17660.96 AICc value: 42937.77 
Fixed bandwidth: 10917.26 AICc value: 42886.26 
Fixed bandwidth: 6749.419 AICc value: 42757.54 
Fixed bandwidth: 4173.553 AICc value: 42565.01 
Fixed bandwidth: 2581.58 AICc value: 42368.05 
Fixed bandwidth: 1597.687 AICc value: 42256.42 
Fixed bandwidth: 989.6077 AICc value: 42262.3 
Fixed bandwidth: 1973.501 AICc value: 42279.95 
Fixed bandwidth: 1365.421 AICc value: 42254.72 
Fixed bandwidth: 1221.873 AICc value: 42255.41 
Fixed bandwidth: 1454.139 AICc value: 42254.82 
Fixed bandwidth: 1310.591 AICc value: 42254.84 
Fixed bandwidth: 1399.309 AICc value: 42254.71 
Fixed bandwidth: 1420.252 AICc value: 42254.73 
Fixed bandwidth: 1386.365 AICc value: 42254.7 
Fixed bandwidth: 1378.365 AICc value: 42254.71 
Fixed bandwidth: 1391.309 AICc value: 42254.7 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1"></a>bw.fixed <span class="ot">&lt;-</span> <span class="fu">bw.gwr</span>(</span>
<span id="cb59-2"><a href="#cb59-2"></a>  <span class="at">formula =</span> SELLING_PRICE <span class="sc">~</span> AREA_SQM <span class="sc">+</span> AGE  <span class="sc">+</span> </span>
<span id="cb59-3"><a href="#cb59-3"></a>    PROX_CBD <span class="sc">+</span> PROX_CHILDCARE <span class="sc">+</span> PROX_ELDERLYCARE    <span class="sc">+</span></span>
<span id="cb59-4"><a href="#cb59-4"></a>    PROX_URA_GROWTH_AREA <span class="sc">+</span> PROX_MRT <span class="sc">+</span> PROX_PARK <span class="sc">+</span> </span>
<span id="cb59-5"><a href="#cb59-5"></a>    PROX_PRIMARY_SCH <span class="sc">+</span> PROX_SHOPPING_MALL   <span class="sc">+</span> </span>
<span id="cb59-6"><a href="#cb59-6"></a>    PROX_BUS_STOP   <span class="sc">+</span> NO_Of_UNITS <span class="sc">+</span> FAMILY_FRIENDLY <span class="sc">+</span> </span>
<span id="cb59-7"><a href="#cb59-7"></a>    FREEHOLD, </span>
<span id="cb59-8"><a href="#cb59-8"></a>  <span class="at">data=</span>condo_resale.sf, </span>
<span id="cb59-9"><a href="#cb59-9"></a>  <span class="at">approach=</span><span class="st">"BIC"</span>, </span>
<span id="cb59-10"><a href="#cb59-10"></a>  <span class="at">kernel=</span><span class="st">"gaussian"</span>, </span>
<span id="cb59-11"><a href="#cb59-11"></a>  <span class="at">adaptive=</span><span class="cn">FALSE</span>, </span>
<span id="cb59-12"><a href="#cb59-12"></a>  <span class="at">longlat=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Fixed bandwidth: 17660.96 BIC value: 41593.33 
Fixed bandwidth: 10917.26 BIC value: 41566.56 
Fixed bandwidth: 6749.419 BIC value: 41500.35 
Fixed bandwidth: 4173.553 BIC value: 41445.41 
Fixed bandwidth: 2581.58 BIC value: 41505.47 
Fixed bandwidth: 5157.446 BIC value: 41459.8 
Fixed bandwidth: 3565.473 BIC value: 41449.85 
Fixed bandwidth: 4549.367 BIC value: 41448.63 
Fixed bandwidth: 3941.287 BIC value: 41445.46 
Fixed bandwidth: 4317.101 BIC value: 41446.21 
Fixed bandwidth: 4084.835 BIC value: 41445.22 
Fixed bandwidth: 4030.005 BIC value: 41445.22 
Fixed bandwidth: 4118.722 BIC value: 41445.26 
Fixed bandwidth: 4063.892 BIC value: 41445.21 
Fixed bandwidth: 4050.948 BIC value: 41445.21 
Fixed bandwidth: 4071.891 BIC value: 41445.21 
Fixed bandwidth: 4058.948 BIC value: 41445.21 
Fixed bandwidth: 4066.947 BIC value: 41445.21 
Fixed bandwidth: 4062.003 BIC value: 41445.21 </code></pre>
</div>
</div>
</section>
<section id="gwmodel-method---fixed-bandwith" class="level3">
<h3 class="anchored" data-anchor-id="gwmodel-method---fixed-bandwith">6.1.2 GWModel method - fixed bandwith</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1"></a>gwr.fixed <span class="ot">&lt;-</span> <span class="fu">gwr.basic</span>(</span>
<span id="cb61-2"><a href="#cb61-2"></a>  <span class="at">formula =</span> SELLING_PRICE <span class="sc">~</span> AREA_SQM <span class="sc">+</span> AGE  <span class="sc">+</span> </span>
<span id="cb61-3"><a href="#cb61-3"></a>    PROX_CBD <span class="sc">+</span> PROX_CHILDCARE <span class="sc">+</span> PROX_ELDERLYCARE    <span class="sc">+</span></span>
<span id="cb61-4"><a href="#cb61-4"></a>    PROX_URA_GROWTH_AREA <span class="sc">+</span> PROX_MRT <span class="sc">+</span> PROX_PARK <span class="sc">+</span></span>
<span id="cb61-5"><a href="#cb61-5"></a>    PROX_PRIMARY_SCH <span class="sc">+</span> PROX_SHOPPING_MALL   <span class="sc">+</span> </span>
<span id="cb61-6"><a href="#cb61-6"></a>    PROX_BUS_STOP   <span class="sc">+</span> NO_Of_UNITS <span class="sc">+</span> FAMILY_FRIENDLY <span class="sc">+</span> </span>
<span id="cb61-7"><a href="#cb61-7"></a>    FREEHOLD, </span>
<span id="cb61-8"><a href="#cb61-8"></a>  <span class="at">data=</span>condo_resale.sf, </span>
<span id="cb61-9"><a href="#cb61-9"></a>  <span class="at">bw=</span>bw.fixed, </span>
<span id="cb61-10"><a href="#cb61-10"></a>  <span class="at">kernel =</span> <span class="st">'gaussian'</span>, </span>
<span id="cb61-11"><a href="#cb61-11"></a>  <span class="at">longlat =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1"></a>gwr.fixed</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   ***********************************************************************
   *                       Package   GWmodel                             *
   ***********************************************************************
   Program starts at: 2025-10-18 17:14:29.844247 
   Call:
   gwr.basic(formula = SELLING_PRICE ~ AREA_SQM + AGE + PROX_CBD + 
    PROX_CHILDCARE + PROX_ELDERLYCARE + PROX_URA_GROWTH_AREA + 
    PROX_MRT + PROX_PARK + PROX_PRIMARY_SCH + PROX_SHOPPING_MALL + 
    PROX_BUS_STOP + NO_Of_UNITS + FAMILY_FRIENDLY + FREEHOLD, 
    data = condo_resale.sf, bw = bw.fixed, kernel = "gaussian", 
    longlat = FALSE)

   Dependent (y) variable:  SELLING_PRICE
   Independent variables:  AREA_SQM AGE PROX_CBD PROX_CHILDCARE PROX_ELDERLYCARE PROX_URA_GROWTH_AREA PROX_MRT PROX_PARK PROX_PRIMARY_SCH PROX_SHOPPING_MALL PROX_BUS_STOP NO_Of_UNITS FAMILY_FRIENDLY FREEHOLD
   Number of data points: 1436
   ***********************************************************************
   *                    Results of Global Regression                     *
   ***********************************************************************

   Call:
    lm(formula = formula, data = data)

   Residuals:
     Min       1Q   Median       3Q      Max 
-3470778  -298119   -23481   248917 12234210 

   Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)    
   (Intercept)           527633.22  108183.22   4.877 1.20e-06 ***
   AREA_SQM               12777.52     367.48  34.771  &lt; 2e-16 ***
   AGE                   -24687.74    2754.84  -8.962  &lt; 2e-16 ***
   PROX_CBD              -77131.32    5763.12 -13.384  &lt; 2e-16 ***
   PROX_CHILDCARE       -318472.75  107959.51  -2.950 0.003231 ** 
   PROX_ELDERLYCARE      185575.62   39901.86   4.651 3.61e-06 ***
   PROX_URA_GROWTH_AREA   39163.25   11754.83   3.332 0.000885 ***
   PROX_MRT             -294745.11   56916.37  -5.179 2.56e-07 ***
   PROX_PARK             570504.81   65507.03   8.709  &lt; 2e-16 ***
   PROX_PRIMARY_SCH      159856.14   60234.60   2.654 0.008046 ** 
   PROX_SHOPPING_MALL   -220947.25   36561.83  -6.043 1.93e-09 ***
   PROX_BUS_STOP         682482.22  134513.24   5.074 4.42e-07 ***
   NO_Of_UNITS             -245.48      87.95  -2.791 0.005321 ** 
   FAMILY_FRIENDLY       146307.58   46893.02   3.120 0.001845 ** 
   FREEHOLD              350599.81   48506.48   7.228 7.98e-13 ***

   ---Significance stars
   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 
   Residual standard error: 756000 on 1421 degrees of freedom
   Multiple R-squared: 0.6507
   Adjusted R-squared: 0.6472 
   F-statistic: 189.1 on 14 and 1421 DF,  p-value: &lt; 2.2e-16 
   ***Extra Diagnostic information
   Residual sum of squares: 8.120609e+14
   Sigma(hat): 752522.9
   AIC:  42966.76
   AICc:  42967.14
   BIC:  41731.39
   ***********************************************************************
   *          Results of Geographically Weighted Regression              *
   ***********************************************************************

   *********************Model calibration information*********************
   Kernel function: gaussian 
   Fixed bandwidth: 4062.003 
   Regression points: the same locations as observations are used.
   Distance metric: Euclidean distance metric is used.

   ****************Summary of GWR coefficient estimates:******************
                               Min.     1st Qu.      Median     3rd Qu.
   Intercept             -53177.018  281529.345  880015.720 1370819.342
   AREA_SQM                4782.896    7711.152   12015.329   15634.498
   AGE                   -45640.381  -37497.344  -23025.827  -12442.350
   PROX_CBD             -131232.506 -105150.303  -91465.675  -72185.483
   PROX_CHILDCARE       -918543.637 -497289.624  -91262.832   25164.643
   PROX_ELDERLYCARE     -105874.439   75882.790  197613.698  287555.979
   PROX_URA_GROWTH_AREA  -58433.315  -14446.323   22865.285   66854.992
   PROX_MRT             -818742.856 -527888.506 -370736.000 -194231.914
   PROX_PARK            -147538.508  159980.396  493820.240  768741.542
   PROX_PRIMARY_SCH     -194486.524  -38433.509  176372.551  324480.299
   PROX_SHOPPING_MALL   -524492.230 -268138.078 -145438.042  -43047.002
   PROX_BUS_STOP          39694.313  354428.154  784663.633 1079425.882
   NO_Of_UNITS             -638.405    -510.445    -259.764     -47.244
   FAMILY_FRIENDLY       -62978.435   69588.845  154439.412  303570.142
   FREEHOLD               42267.156  202338.112  295430.145  406652.963
                              Max.
   Intercept            1805833.71
   AREA_SQM               16573.26
   AGE                    -4653.84
   PROX_CBD              -35186.70
   PROX_CHILDCARE        236120.38
   PROX_ELDERLYCARE      377837.54
   PROX_URA_GROWTH_AREA  105132.33
   PROX_MRT              -40558.75
   PROX_PARK             884432.31
   PROX_PRIMARY_SCH      541493.93
   PROX_SHOPPING_MALL    139775.01
   PROX_BUS_STOP        1366060.08
   NO_Of_UNITS              151.23
   FAMILY_FRIENDLY       411016.58
   FREEHOLD              544941.24
   ************************Diagnostic information*************************
   Number of data points: 1436 
   Effective number of parameters (2trace(S) - trace(S'S)): 82.88972 
   Effective degrees of freedom (n-2trace(S) + trace(S'S)): 1353.11 
   AICc (GWR book, Fotheringham, et al. 2002, p. 61, eq 2.33): 42553.96 
   AIC (GWR book, Fotheringham, et al. 2002,GWR p. 96, eq. 4.22): 42482.11 
   BIC (GWR book, Fotheringham, et al. 2002,GWR p. 61, eq. 2.34): 41445.21 
   Residual sum of squares: 5.668132e+14 
   R-square value:  0.7561723 
   Adjusted R-square value:  0.7412247 

   ***********************************************************************
   Program stops at: 2025-10-18 17:14:31.79288 </code></pre>
</div>
</div>
</section>
</section>
<section id="building-adaptive-bandwidth-gwr-model" class="level2">
<h2 class="anchored" data-anchor-id="building-adaptive-bandwidth-gwr-model">6.2 Building Adaptive Bandwidth GWR Model</h2>
<section id="computing-the-adaptive-bandwidth" class="level3">
<h3 class="anchored" data-anchor-id="computing-the-adaptive-bandwidth">6.2.1 Computing the adaptive bandwidth</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1"></a>bw.adaptive <span class="ot">&lt;-</span> <span class="fu">bw.gwr</span>(</span>
<span id="cb64-2"><a href="#cb64-2"></a>  <span class="at">formula =</span> SELLING_PRICE <span class="sc">~</span> AREA_SQM <span class="sc">+</span> AGE  <span class="sc">+</span> </span>
<span id="cb64-3"><a href="#cb64-3"></a>    PROX_CBD <span class="sc">+</span> PROX_CHILDCARE <span class="sc">+</span> PROX_ELDERLYCARE    <span class="sc">+</span></span>
<span id="cb64-4"><a href="#cb64-4"></a>    PROX_URA_GROWTH_AREA <span class="sc">+</span> PROX_MRT <span class="sc">+</span> PROX_PARK <span class="sc">+</span></span>
<span id="cb64-5"><a href="#cb64-5"></a>    PROX_PRIMARY_SCH <span class="sc">+</span> PROX_SHOPPING_MALL   <span class="sc">+</span> </span>
<span id="cb64-6"><a href="#cb64-6"></a>    PROX_BUS_STOP   <span class="sc">+</span> NO_Of_UNITS <span class="sc">+</span> </span>
<span id="cb64-7"><a href="#cb64-7"></a>    FAMILY_FRIENDLY <span class="sc">+</span> FREEHOLD, </span>
<span id="cb64-8"><a href="#cb64-8"></a>  <span class="at">data=</span>condo_resale.sf, </span>
<span id="cb64-9"><a href="#cb64-9"></a>  <span class="at">approach=</span><span class="st">"CV"</span>, </span>
<span id="cb64-10"><a href="#cb64-10"></a>  <span class="at">kernel=</span><span class="st">"gaussian"</span>, </span>
<span id="cb64-11"><a href="#cb64-11"></a>  <span class="at">adaptive=</span><span class="cn">TRUE</span>, </span>
<span id="cb64-12"><a href="#cb64-12"></a>  <span class="at">longlat=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Adaptive bandwidth: 895 CV score: 7.952401e+14 
Adaptive bandwidth: 561 CV score: 7.667364e+14 
Adaptive bandwidth: 354 CV score: 6.953454e+14 
Adaptive bandwidth: 226 CV score: 6.15223e+14 
Adaptive bandwidth: 147 CV score: 5.674373e+14 
Adaptive bandwidth: 98 CV score: 5.426745e+14 
Adaptive bandwidth: 68 CV score: 5.168117e+14 
Adaptive bandwidth: 49 CV score: 4.859631e+14 
Adaptive bandwidth: 37 CV score: 4.646518e+14 
Adaptive bandwidth: 30 CV score: 4.422088e+14 
Adaptive bandwidth: 25 CV score: 4.430816e+14 
Adaptive bandwidth: 32 CV score: 4.505602e+14 
Adaptive bandwidth: 27 CV score: 4.462172e+14 
Adaptive bandwidth: 30 CV score: 4.422088e+14 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1"></a>bw.adaptive <span class="ot">&lt;-</span> <span class="fu">bw.gwr</span>(</span>
<span id="cb66-2"><a href="#cb66-2"></a>  <span class="at">formula =</span> SELLING_PRICE <span class="sc">~</span> AREA_SQM <span class="sc">+</span> AGE  <span class="sc">+</span> </span>
<span id="cb66-3"><a href="#cb66-3"></a>    PROX_CBD <span class="sc">+</span> PROX_CHILDCARE <span class="sc">+</span> PROX_ELDERLYCARE    <span class="sc">+</span></span>
<span id="cb66-4"><a href="#cb66-4"></a>    PROX_URA_GROWTH_AREA <span class="sc">+</span> PROX_MRT <span class="sc">+</span> PROX_PARK <span class="sc">+</span></span>
<span id="cb66-5"><a href="#cb66-5"></a>    PROX_PRIMARY_SCH <span class="sc">+</span> PROX_SHOPPING_MALL   <span class="sc">+</span> </span>
<span id="cb66-6"><a href="#cb66-6"></a>    PROX_BUS_STOP   <span class="sc">+</span> NO_Of_UNITS <span class="sc">+</span> </span>
<span id="cb66-7"><a href="#cb66-7"></a>    FAMILY_FRIENDLY <span class="sc">+</span> FREEHOLD, </span>
<span id="cb66-8"><a href="#cb66-8"></a>  <span class="at">data=</span>condo_resale.sf, </span>
<span id="cb66-9"><a href="#cb66-9"></a>  <span class="at">approach=</span><span class="st">"AIC"</span>, </span>
<span id="cb66-10"><a href="#cb66-10"></a>  <span class="at">kernel=</span><span class="st">"gaussian"</span>, </span>
<span id="cb66-11"><a href="#cb66-11"></a>  <span class="at">adaptive=</span><span class="cn">TRUE</span>, </span>
<span id="cb66-12"><a href="#cb66-12"></a>  <span class="at">longlat=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Adaptive bandwidth (number of nearest neighbours): 895 AICc value: 42879.45 
Adaptive bandwidth (number of nearest neighbours): 561 AICc value: 42823.52 
Adaptive bandwidth (number of nearest neighbours): 354 AICc value: 42677.14 
Adaptive bandwidth (number of nearest neighbours): 226 AICc value: 42484.37 
Adaptive bandwidth (number of nearest neighbours): 147 AICc value: 42353.27 
Adaptive bandwidth (number of nearest neighbours): 98 AICc value: 42280.68 
Adaptive bandwidth (number of nearest neighbours): 68 AICc value: 42201.18 
Adaptive bandwidth (number of nearest neighbours): 49 AICc value: 42100.66 
Adaptive bandwidth (number of nearest neighbours): 37 AICc value: 42055.68 
Adaptive bandwidth (number of nearest neighbours): 30 AICc value: 41982.22 
Adaptive bandwidth (number of nearest neighbours): 25 AICc value: 42003.33 
Adaptive bandwidth (number of nearest neighbours): 32 AICc value: 42035.41 
Adaptive bandwidth (number of nearest neighbours): 27 AICc value: 41978.63 
Adaptive bandwidth (number of nearest neighbours): 27 AICc value: 41978.63 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1"></a>bw.adaptive <span class="ot">&lt;-</span> <span class="fu">bw.gwr</span>(</span>
<span id="cb68-2"><a href="#cb68-2"></a>  <span class="at">formula =</span> SELLING_PRICE <span class="sc">~</span> AREA_SQM <span class="sc">+</span> AGE  <span class="sc">+</span> </span>
<span id="cb68-3"><a href="#cb68-3"></a>    PROX_CBD <span class="sc">+</span> PROX_CHILDCARE <span class="sc">+</span> PROX_ELDERLYCARE    <span class="sc">+</span></span>
<span id="cb68-4"><a href="#cb68-4"></a>    PROX_URA_GROWTH_AREA <span class="sc">+</span> PROX_MRT <span class="sc">+</span> PROX_PARK <span class="sc">+</span></span>
<span id="cb68-5"><a href="#cb68-5"></a>    PROX_PRIMARY_SCH <span class="sc">+</span> PROX_SHOPPING_MALL   <span class="sc">+</span> </span>
<span id="cb68-6"><a href="#cb68-6"></a>    PROX_BUS_STOP   <span class="sc">+</span> NO_Of_UNITS <span class="sc">+</span> </span>
<span id="cb68-7"><a href="#cb68-7"></a>    FAMILY_FRIENDLY <span class="sc">+</span> FREEHOLD, </span>
<span id="cb68-8"><a href="#cb68-8"></a>  <span class="at">data=</span>condo_resale.sf, </span>
<span id="cb68-9"><a href="#cb68-9"></a>  <span class="at">approach=</span><span class="st">"BIC"</span>, </span>
<span id="cb68-10"><a href="#cb68-10"></a>  <span class="at">kernel=</span><span class="st">"gaussian"</span>, </span>
<span id="cb68-11"><a href="#cb68-11"></a>  <span class="at">adaptive=</span><span class="cn">TRUE</span>, </span>
<span id="cb68-12"><a href="#cb68-12"></a>  <span class="at">longlat=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Adaptive bandwidth (number of nearest neighbours): 895 BIC value: 41549.42 
Adaptive bandwidth (number of nearest neighbours): 561 BIC value: 41522.62 
Adaptive bandwidth (number of nearest neighbours): 354 BIC value: 41426.52 
Adaptive bandwidth (number of nearest neighbours): 226 BIC value: 41306.39 
Adaptive bandwidth (number of nearest neighbours): 147 BIC value: 41278.47 
Adaptive bandwidth (number of nearest neighbours): 98 BIC value: 41355.99 
Adaptive bandwidth (number of nearest neighbours): 177 BIC value: 41282.21 
Adaptive bandwidth (number of nearest neighbours): 128 BIC value: 41294.4 
Adaptive bandwidth (number of nearest neighbours): 158 BIC value: 41280.62 
Adaptive bandwidth (number of nearest neighbours): 139 BIC value: 41280.71 
Adaptive bandwidth (number of nearest neighbours): 151 BIC value: 41280.81 
Adaptive bandwidth (number of nearest neighbours): 143 BIC value: 41283.33 
Adaptive bandwidth (number of nearest neighbours): 147 BIC value: 41278.47 </code></pre>
</div>
</div>
</section>
<section id="constructing-the-adaptive-bandwidth-gwr-model" class="level3">
<h3 class="anchored" data-anchor-id="constructing-the-adaptive-bandwidth-gwr-model">6.2.2 Constructing the adaptive bandwidth gwr model</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1"></a>gwr.adaptive <span class="ot">&lt;-</span> <span class="fu">gwr.basic</span>(</span>
<span id="cb70-2"><a href="#cb70-2"></a>  <span class="at">formula =</span> SELLING_PRICE <span class="sc">~</span> AREA_SQM <span class="sc">+</span> AGE <span class="sc">+</span> </span>
<span id="cb70-3"><a href="#cb70-3"></a>    PROX_CBD <span class="sc">+</span> PROX_CHILDCARE <span class="sc">+</span> PROX_ELDERLYCARE <span class="sc">+</span></span>
<span id="cb70-4"><a href="#cb70-4"></a>    PROX_URA_GROWTH_AREA <span class="sc">+</span> PROX_MRT <span class="sc">+</span> PROX_PARK <span class="sc">+</span></span>
<span id="cb70-5"><a href="#cb70-5"></a>    PROX_PRIMARY_SCH <span class="sc">+</span> PROX_SHOPPING_MALL <span class="sc">+</span> PROX_BUS_STOP <span class="sc">+</span></span>
<span id="cb70-6"><a href="#cb70-6"></a>    NO_Of_UNITS <span class="sc">+</span> FAMILY_FRIENDLY <span class="sc">+</span> FREEHOLD,</span>
<span id="cb70-7"><a href="#cb70-7"></a>  <span class="at">data=</span>condo_resale.sf, </span>
<span id="cb70-8"><a href="#cb70-8"></a>  <span class="at">bw=</span>bw.adaptive, </span>
<span id="cb70-9"><a href="#cb70-9"></a>  <span class="at">kernel =</span> <span class="st">'gaussian'</span>, </span>
<span id="cb70-10"><a href="#cb70-10"></a>  <span class="at">adaptive=</span><span class="cn">TRUE</span>, </span>
<span id="cb70-11"><a href="#cb70-11"></a>  <span class="at">longlat =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1"></a>gwr.adaptive</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   ***********************************************************************
   *                       Package   GWmodel                             *
   ***********************************************************************
   Program starts at: 2025-10-18 17:15:22.383254 
   Call:
   gwr.basic(formula = SELLING_PRICE ~ AREA_SQM + AGE + PROX_CBD + 
    PROX_CHILDCARE + PROX_ELDERLYCARE + PROX_URA_GROWTH_AREA + 
    PROX_MRT + PROX_PARK + PROX_PRIMARY_SCH + PROX_SHOPPING_MALL + 
    PROX_BUS_STOP + NO_Of_UNITS + FAMILY_FRIENDLY + FREEHOLD, 
    data = condo_resale.sf, bw = bw.adaptive, kernel = "gaussian", 
    adaptive = TRUE, longlat = FALSE)

   Dependent (y) variable:  SELLING_PRICE
   Independent variables:  AREA_SQM AGE PROX_CBD PROX_CHILDCARE PROX_ELDERLYCARE PROX_URA_GROWTH_AREA PROX_MRT PROX_PARK PROX_PRIMARY_SCH PROX_SHOPPING_MALL PROX_BUS_STOP NO_Of_UNITS FAMILY_FRIENDLY FREEHOLD
   Number of data points: 1436
   ***********************************************************************
   *                    Results of Global Regression                     *
   ***********************************************************************

   Call:
    lm(formula = formula, data = data)

   Residuals:
     Min       1Q   Median       3Q      Max 
-3470778  -298119   -23481   248917 12234210 

   Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)    
   (Intercept)           527633.22  108183.22   4.877 1.20e-06 ***
   AREA_SQM               12777.52     367.48  34.771  &lt; 2e-16 ***
   AGE                   -24687.74    2754.84  -8.962  &lt; 2e-16 ***
   PROX_CBD              -77131.32    5763.12 -13.384  &lt; 2e-16 ***
   PROX_CHILDCARE       -318472.75  107959.51  -2.950 0.003231 ** 
   PROX_ELDERLYCARE      185575.62   39901.86   4.651 3.61e-06 ***
   PROX_URA_GROWTH_AREA   39163.25   11754.83   3.332 0.000885 ***
   PROX_MRT             -294745.11   56916.37  -5.179 2.56e-07 ***
   PROX_PARK             570504.81   65507.03   8.709  &lt; 2e-16 ***
   PROX_PRIMARY_SCH      159856.14   60234.60   2.654 0.008046 ** 
   PROX_SHOPPING_MALL   -220947.25   36561.83  -6.043 1.93e-09 ***
   PROX_BUS_STOP         682482.22  134513.24   5.074 4.42e-07 ***
   NO_Of_UNITS             -245.48      87.95  -2.791 0.005321 ** 
   FAMILY_FRIENDLY       146307.58   46893.02   3.120 0.001845 ** 
   FREEHOLD              350599.81   48506.48   7.228 7.98e-13 ***

   ---Significance stars
   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 
   Residual standard error: 756000 on 1421 degrees of freedom
   Multiple R-squared: 0.6507
   Adjusted R-squared: 0.6472 
   F-statistic: 189.1 on 14 and 1421 DF,  p-value: &lt; 2.2e-16 
   ***Extra Diagnostic information
   Residual sum of squares: 8.120609e+14
   Sigma(hat): 752522.9
   AIC:  42966.76
   AICc:  42967.14
   BIC:  41731.39
   ***********************************************************************
   *          Results of Geographically Weighted Regression              *
   ***********************************************************************

   *********************Model calibration information*********************
   Kernel function: gaussian 
   Adaptive bandwidth: 147 (number of nearest neighbours)
   Regression points: the same locations as observations are used.
   Distance metric: Euclidean distance metric is used.

   ****************Summary of GWR coefficient estimates:******************
                               Min.     1st Qu.      Median     3rd Qu.
   Intercept            -9.0930e+05  2.9000e+05  7.4952e+05  1.4368e+06
   AREA_SQM              4.8484e+03  7.9316e+03  1.2043e+04  1.5604e+04
   AGE                  -6.9805e+04 -3.9558e+04 -2.3204e+04 -1.0307e+04
   PROX_CBD             -2.5012e+05 -1.1125e+05 -9.1179e+04 -7.5267e+04
   PROX_CHILDCARE       -1.0638e+06 -3.1424e+05 -1.6611e+04  9.9726e+04
   PROX_ELDERLYCARE     -1.0512e+05  1.1387e+05  1.7661e+05  2.8105e+05
   PROX_URA_GROWTH_AREA -1.3688e+05 -1.6629e+04  3.1436e+04  7.1311e+04
   PROX_MRT             -1.6188e+06 -6.2991e+05 -3.5663e+05 -2.7298e+05
   PROX_PARK            -2.4102e+05  9.4328e+03  4.5910e+05  7.1345e+05
   PROX_PRIMARY_SCH     -1.9279e+05  2.8732e+04  1.4874e+05  3.3334e+05
   PROX_SHOPPING_MALL   -4.8662e+05 -2.5510e+05 -1.3863e+05 -1.2313e+04
   PROX_BUS_STOP        -3.7614e+04  2.8960e+05  7.2455e+05  1.1552e+06
   NO_Of_UNITS          -8.6929e+02 -4.6827e+02 -2.4796e+02 -7.1072e+01
   FAMILY_FRIENDLY      -1.1400e+04  6.3580e+04  1.2901e+05  3.0417e+05
   FREEHOLD              5.5328e+04  2.0819e+05  3.0825e+05  4.0026e+05
                              Max.
   Intercept            2559437.32
   AREA_SQM               17753.77
   AGE                    -4583.59
   PROX_CBD              -24210.29
   PROX_CHILDCARE        491634.42
   PROX_ELDERLYCARE      408110.11
   PROX_URA_GROWTH_AREA  282678.32
   PROX_MRT              -42428.11
   PROX_PARK             869914.38
   PROX_PRIMARY_SCH     1628158.01
   PROX_SHOPPING_MALL    132979.30
   PROX_BUS_STOP        3262113.43
   NO_Of_UNITS              268.59
   FAMILY_FRIENDLY       976625.77
   FREEHOLD              830532.49
   ************************Diagnostic information*************************
   Number of data points: 1436 
   Effective number of parameters (2trace(S) - trace(S'S)): 92.47833 
   Effective degrees of freedom (n-2trace(S) + trace(S'S)): 1343.522 
   AICc (GWR book, Fotheringham, et al. 2002, p. 61, eq 2.33): 42353.27 
   AIC (GWR book, Fotheringham, et al. 2002,GWR p. 96, eq. 4.22): 42273.34 
   BIC (GWR book, Fotheringham, et al. 2002,GWR p. 61, eq. 2.34): 41278.47 
   Residual sum of squares: 4.878365e+14 
   R-square value:  0.790146 
   Adjusted R-square value:  0.7756904 

   ***********************************************************************
   Program stops at: 2025-10-18 17:15:24.157756 </code></pre>
</div>
</div>
<ul>
<li>Fixed bandwidth (4062 m) assumes spatial processes vary uniformly — good for evenly spaced data, but may over-smooth dense urban areas.</li>
<li>Adaptive bandwidth (147 nearest neighbours) adjusts the window size depending on data density — smaller in dense areas, larger in sparse ones.</li>
<li>Both AIC and BIC results point to adaptive GWR (147 NN) as the best-performing and most realistic model for spatially heterogeneous housing data.</li>
</ul>
<p>Between fixed and adaptive bandwidth approaches, the adaptive GWR model using 147 nearest neighbours (BIC-selected) performed best. It achieved the lowest BIC (41278.47), higher R², and smaller residuals, indicating that local spatial variations in housing prices are better captured when the bandwidth adapts to data density. Therefore, the adaptive (BIC-based) approach represents the correct and optimal nearest-neighbour configuration for this pricing model.</p>
</section>
</section>
<section id="converting-sdf-into-sf-data.frame" class="level2">
<h2 class="anchored" data-anchor-id="converting-sdf-into-sf-data.frame">6.3 Converting SDF into sf data.frame</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1"></a>condo_resale.sf.adaptive <span class="ot">&lt;-</span></span>
<span id="cb73-2"><a href="#cb73-2"></a>  <span class="fu">st_as_sf</span>(gwr.adaptive<span class="sc">$</span>SDF) <span class="sc">%&gt;%</span></span>
<span id="cb73-3"><a href="#cb73-3"></a>  <span class="fu">st_transform</span>(<span class="at">crs=</span><span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1"></a><span class="fu">glimpse</span>(condo_resale.sf.adaptive)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,436
Columns: 52
$ Intercept               &lt;dbl&gt; 882486.7, 290126.6, 762198.0, -324250.4, 14305…
$ AREA_SQM                &lt;dbl&gt; 14191.900, 16520.276, 15351.762, 17448.807, 60…
$ AGE                     &lt;dbl&gt; -26635.424, -46734.827, -37492.117, -68060.842…
$ PROX_CBD                &lt;dbl&gt; -83598.91, -79953.53, -100097.21, -59865.84, -…
$ PROX_CHILDCARE          &lt;dbl&gt; -149160.2200, -24807.3116, 298809.4758, 296018…
$ PROX_ELDERLYCARE        &lt;dbl&gt; 106476.23, 314537.95, 266428.22, 325458.48, 13…
$ PROX_URA_GROWTH_AREA    &lt;dbl&gt; -35528.459, -65086.870, -106494.148, -41795.52…
$ PROX_MRT                &lt;dbl&gt; -356634.61, -804282.70, -639312.85, -1497751.4…
$ PROX_PARK               &lt;dbl&gt; 578680.22, 810906.05, 660302.23, 613782.83, -1…
$ PROX_PRIMARY_SCH        &lt;dbl&gt; 205590.319, 584054.935, 454049.928, 1183859.95…
$ PROX_SHOPPING_MALL      &lt;dbl&gt; -230134.792, -142567.378, -142656.086, -332052…
$ PROX_BUS_STOP           &lt;dbl&gt; 886508.0, 1313545.2, 1374644.7, 2760175.8, 289…
$ NO_Of_UNITS             &lt;dbl&gt; -545.41020, -591.15844, -671.30595, -676.49262…
$ FAMILY_FRIENDLY         &lt;dbl&gt; 239435.13, 458560.30, 450543.57, 839633.52, 52…
$ FREEHOLD                &lt;dbl&gt; 330841.66, 371572.01, 353790.24, 704445.59, 22…
$ y                       &lt;dbl&gt; 3000000, 3880000, 3325000, 4250000, 1400000, 1…
$ yhat                    &lt;dbl&gt; 4530852.6, 3688595.9, 3424534.4, 4415548.7, 14…
$ residual                &lt;dbl&gt; -1530852.55, 191404.07, -99534.41, -165548.74,…
$ CV_Score                &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ Stud_residual           &lt;dbl&gt; -2.73696354, 0.33009145, -0.17492358, -0.28549…
$ Intercept_SE            &lt;dbl&gt; 153159.7, 141182.3, 169637.3, 170343.2, 246354…
$ AREA_SQM_SE             &lt;dbl&gt; 410.2435, 426.4684, 434.1756, 492.0255, 680.34…
$ AGE_SE                  &lt;dbl&gt; 3376.742, 3432.861, 3556.053, 4611.327, 5340.5…
$ PROX_CBD_SE             &lt;dbl&gt; 8850.299, 9557.984, 10988.952, 16693.223, 3318…
$ PROX_CHILDCARE_SE       &lt;dbl&gt; 143065.5, 154669.8, 174407.4, 208856.5, 289010…
$ PROX_ELDERLYCARE_SE     &lt;dbl&gt; 55210.90, 53738.31, 57257.64, 71930.62, 103953…
$ PROX_URA_GROWTH_AREA_SE &lt;dbl&gt; 24456.83, 20320.78, 28721.74, 35000.51, 46549.…
$ PROX_MRT_SE             &lt;dbl&gt; 86685.95, 87813.34, 99123.30, 153791.23, 11386…
$ PROX_PARK_SE            &lt;dbl&gt; 86917.94, 94712.09, 103293.89, 118405.57, 1630…
$ PROX_PRIMARY_SCH_SE     &lt;dbl&gt; 74070.89, 73926.43, 80033.07, 104437.67, 14983…
$ PROX_SHOPPING_MALL_SE   &lt;dbl&gt; 53543.34, 48335.82, 57728.08, 75382.46, 83412.…
$ PROX_BUS_STOP_SE        &lt;dbl&gt; 175118.3, 219682.9, 233035.8, 303479.1, 397614…
$ NO_Of_UNITS_SE          &lt;dbl&gt; 115.0315, 120.5914, 134.6531, 154.6652, 159.35…
$ FAMILY_FRIENDLY_SE      &lt;dbl&gt; 63749.63, 63330.87, 68943.15, 84243.61, 89889.…
$ FREEHOLD_SE             &lt;dbl&gt; 60488.78, 58495.20, 64687.76, 85117.81, 106640…
$ Intercept_TV            &lt;dbl&gt; 5.761872, 2.054979, 4.493104, -1.903512, 5.806…
$ AREA_SQM_TV             &lt;dbl&gt; 34.593844, 38.737398, 35.358420, 35.463216, 8.…
$ AGE_TV                  &lt;dbl&gt; -7.887907, -13.613957, -10.543182, -14.759492,…
$ PROX_CBD_TV             &lt;dbl&gt; -9.445885, -8.365104, -9.108895, -3.586236, -3…
$ PROX_CHILDCARE_TV       &lt;dbl&gt; -1.0426006580, -0.1603888336, 1.7132839681, 1.…
$ PROX_ELDERLYCARE_TV     &lt;dbl&gt; 1.9285363, 5.8531418, 4.6531475, 4.5246167, 1.…
$ PROX_URA_GROWTH_AREA_TV &lt;dbl&gt; -1.45270116, -3.20297185, -3.70778827, -1.1941…
$ PROX_MRT_TV             &lt;dbl&gt; -4.1140992, -9.1590040, -6.4496729, -9.7388614…
$ PROX_PARK_TV            &lt;dbl&gt; 6.6577765, 8.5618012, 6.3924618, 5.1837329, -1…
$ PROX_PRIMARY_SCH_TV     &lt;dbl&gt; 2.77558853, 7.90048937, 5.67327875, 11.3355649…
$ PROX_SHOPPING_MALL_TV   &lt;dbl&gt; -4.29810305, -2.94951807, -2.47117312, -4.4049…
$ PROX_BUS_STOP_TV        &lt;dbl&gt; 5.0623369, 5.9792784, 5.8988574, 9.0951095, 0.…
$ NO_Of_UNITS_TV          &lt;dbl&gt; -4.7413979, -4.9021611, -4.9854476, -4.3739168…
$ FAMILY_FRIENDLY_TV      &lt;dbl&gt; 3.7558672, 7.2407072, 6.5350009, 9.9667328, 0.…
$ FREEHOLD_TV             &lt;dbl&gt; 5.4694716, 6.3521793, 5.4691990, 8.2761244, 2.…
$ Local_R2                &lt;dbl&gt; 0.6165668, 0.7738609, 0.7457216, 0.8053114, 0.…
$ geometry                &lt;POINT [m]&gt; POINT (22085.12 29951.54), POINT (25656.…</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1"></a><span class="fu">summary</span>(gwr.adaptive<span class="sc">$</span>SDF<span class="sc">$</span>yhat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
  -66495  1082525  1401799  1770312  2035795 13292193 </code></pre>
</div>
</div>
</section>
<section id="visualising-local-r2" class="level2">
<h2 class="anchored" data-anchor-id="visualising-local-r2">6.4 Visualising local R2</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb78-2"><a href="#cb78-2"></a><span class="fu">tm_shape</span>(mpsz_svy21)<span class="sc">+</span></span>
<span id="cb78-3"><a href="#cb78-3"></a>  <span class="fu">tm_polygons</span>(<span class="at">fill_alpha =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb78-4"><a href="#cb78-4"></a><span class="fu">tm_shape</span>(condo_resale.sf.adaptive) <span class="sc">+</span>  </span>
<span id="cb78-5"><a href="#cb78-5"></a>  <span class="fu">tm_dots</span>(<span class="at">col =</span> <span class="st">"Local_R2"</span>,</span>
<span id="cb78-6"><a href="#cb78-6"></a>          <span class="at">border.col =</span> <span class="st">"gray60"</span>,</span>
<span id="cb78-7"><a href="#cb78-7"></a>          <span class="at">border.lwd =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb78-8"><a href="#cb78-8"></a>  <span class="fu">tm_view</span>(<span class="at">set.zoom.limits =</span> <span class="fu">c</span>(<span class="dv">11</span>,<span class="dv">14</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="In-class_Ex07_files/figure-html/unnamed-chunk-54-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="thematic-mapping" class="level2">
<h2 class="anchored" data-anchor-id="thematic-mapping">6.5 Thematic Mapping</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1"></a><span class="co"># Filtering dataset for only Local R² values between 0.85 and 0.9</span></span>
<span id="cb80-2"><a href="#cb80-2"></a>condo_resale_filtered <span class="ot">&lt;-</span> condo_resale.sf.adaptive <span class="sc">%&gt;%</span></span>
<span id="cb80-3"><a href="#cb80-3"></a>  <span class="fu">filter</span>(Local_R2 <span class="sc">&gt;=</span> <span class="fl">0.85</span> <span class="sc">&amp;</span> Local_R2 <span class="sc">&lt;=</span> <span class="fl">0.9</span>)</span>
<span id="cb80-4"><a href="#cb80-4"></a></span>
<span id="cb80-5"><a href="#cb80-5"></a><span class="co"># Switching to static map mode</span></span>
<span id="cb80-6"><a href="#cb80-6"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb80-7"><a href="#cb80-7"></a></span>
<span id="cb80-8"><a href="#cb80-8"></a><span class="co"># Plotting</span></span>
<span id="cb80-9"><a href="#cb80-9"></a><span class="fu">tm_shape</span>(mpsz_svy21) <span class="sc">+</span></span>
<span id="cb80-10"><a href="#cb80-10"></a>  <span class="fu">tm_polygons</span>(<span class="at">fill =</span> <span class="st">"gray90"</span>, <span class="at">border.col =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb80-11"><a href="#cb80-11"></a><span class="fu">tm_shape</span>(condo_resale_filtered) <span class="sc">+</span></span>
<span id="cb80-12"><a href="#cb80-12"></a>  <span class="fu">tm_dots</span>(<span class="at">col =</span> <span class="st">"Local_R2"</span>,</span>
<span id="cb80-13"><a href="#cb80-13"></a>          <span class="at">size =</span> <span class="fl">0.08</span>,</span>
<span id="cb80-14"><a href="#cb80-14"></a>          <span class="at">border.col =</span> <span class="st">"gray50"</span>,</span>
<span id="cb80-15"><a href="#cb80-15"></a>          <span class="at">border.lwd =</span> <span class="fl">0.5</span>,</span>
<span id="cb80-16"><a href="#cb80-16"></a>          <span class="at">palette =</span> <span class="st">"-RdYlBu"</span>,</span>
<span id="cb80-17"><a href="#cb80-17"></a>          <span class="at">title =</span> <span class="st">"Local R² (0.85 – 0.9)"</span>) <span class="sc">+</span></span>
<span id="cb80-18"><a href="#cb80-18"></a>  <span class="fu">tm_compass</span>(<span class="at">type =</span> <span class="st">"8star"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb80-19"><a href="#cb80-19"></a>  <span class="fu">tm_scale_bar</span>() <span class="sc">+</span></span>
<span id="cb80-20"><a href="#cb80-20"></a>  <span class="fu">tm_credits</span>(<span class="st">"Source: URA MP 2019, Condo Resale Data, GWR Results"</span>,</span>
<span id="cb80-21"><a href="#cb80-21"></a>             <span class="at">position =</span> <span class="fu">c</span>(<span class="st">"left"</span>, <span class="st">"bottom"</span>)) <span class="sc">+</span></span>
<span id="cb80-22"><a href="#cb80-22"></a>  <span class="fu">tm_layout</span>(<span class="at">title =</span> <span class="st">"Spatial Cluster of High Local R² (0.85 – 0.9)"</span>,</span>
<span id="cb80-23"><a href="#cb80-23"></a>            <span class="at">legend.outside =</span> <span class="cn">TRUE</span>,</span>
<span id="cb80-24"><a href="#cb80-24"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>,</span>
<span id="cb80-25"><a href="#cb80-25"></a>            <span class="at">bg.color =</span> <span class="st">"white"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="In-class_Ex07_files/figure-html/unnamed-chunk-55-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="analyzing-r²-distribution-in-jurong-east-planning-area" class="level2">
<h2 class="anchored" data-anchor-id="analyzing-r²-distribution-in-jurong-east-planning-area">Analyzing R² Distribution in Jurong East Planning Area</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1"></a><span class="co"># Extracting Jurong East Data</span></span>
<span id="cb81-2"><a href="#cb81-2"></a></span>
<span id="cb81-3"><a href="#cb81-3"></a><span class="co"># Extract Jurong East planning area boundary</span></span>
<span id="cb81-4"><a href="#cb81-4"></a>JurongEast_boundary <span class="ot">&lt;-</span> mpsz_svy21 <span class="sc">%&gt;%</span></span>
<span id="cb81-5"><a href="#cb81-5"></a> <span class="fu">filter</span>(PLN_AREA_N <span class="sc">==</span> <span class="st">"JURONG EAST"</span>)</span>
<span id="cb81-6"><a href="#cb81-6"></a><span class="co"># Filter GWR results for Jurong East area</span></span>
<span id="cb81-7"><a href="#cb81-7"></a>JurongEast_gwr <span class="ot">&lt;-</span> condo_resale.sf.adaptive <span class="sc">%&gt;%</span></span>
<span id="cb81-8"><a href="#cb81-8"></a> <span class="fu">st_join</span>(JurongEast_boundary) <span class="sc">%&gt;%</span></span>
<span id="cb81-9"><a href="#cb81-9"></a> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(PLN_AREA_N))</span>
<span id="cb81-10"><a href="#cb81-10"></a><span class="co"># Checking the number of observations in Jurong East</span></span>
<span id="cb81-11"><a href="#cb81-11"></a><span class="fu">nrow</span>(JurongEast_gwr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15</code></pre>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1"></a><span class="co"># Summary Statistics of R² in Jurong East</span></span>
<span id="cb83-2"><a href="#cb83-2"></a><span class="co"># Summary of Local R² in Jurong East</span></span>
<span id="cb83-3"><a href="#cb83-3"></a>JurongEast_r2_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(JurongEast_gwr<span class="sc">$</span>Local_R2)</span>
<span id="cb83-4"><a href="#cb83-4"></a>JurongEast_r2_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.7247  0.7486  0.7624  0.7570  0.7679  0.7720 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1"></a><span class="co"># Additional statistics</span></span>
<span id="cb85-2"><a href="#cb85-2"></a>JurongEast_r2_stats <span class="ot">&lt;-</span> JurongEast_gwr <span class="sc">%&gt;%</span></span>
<span id="cb85-3"><a href="#cb85-3"></a> <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span></span>
<span id="cb85-4"><a href="#cb85-4"></a> <span class="fu">summarise</span>(</span>
<span id="cb85-5"><a href="#cb85-5"></a>   <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb85-6"><a href="#cb85-6"></a>   <span class="at">mean_r2 =</span> <span class="fu">mean</span>(Local_R2),</span>
<span id="cb85-7"><a href="#cb85-7"></a>   <span class="at">median_r2 =</span> <span class="fu">median</span>(Local_R2),</span>
<span id="cb85-8"><a href="#cb85-8"></a>   <span class="at">sd_r2 =</span> <span class="fu">sd</span>(Local_R2),</span>
<span id="cb85-9"><a href="#cb85-9"></a>   <span class="at">min_r2 =</span> <span class="fu">min</span>(Local_R2),</span>
<span id="cb85-10"><a href="#cb85-10"></a>   <span class="at">max_r2 =</span> <span class="fu">max</span>(Local_R2),</span>
<span id="cb85-11"><a href="#cb85-11"></a>   <span class="at">q1_r2 =</span> <span class="fu">quantile</span>(Local_R2, <span class="fl">0.25</span>),</span>
<span id="cb85-12"><a href="#cb85-12"></a>   <span class="at">q3_r2 =</span> <span class="fu">quantile</span>(Local_R2, <span class="fl">0.75</span>)</span>
<span id="cb85-13"><a href="#cb85-13"></a> )</span>
<span id="cb85-14"><a href="#cb85-14"></a>JurongEast_r2_stats</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   n   mean_r2 median_r2      sd_r2    min_r2    max_r2     q1_r2     q3_r2
1 15 0.7570286 0.7624288 0.01566552 0.7246578 0.7720285 0.7486432 0.7678689</code></pre>
</div>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1"></a><span class="co"># Visualizing R² Distribution in Jurong East</span></span>
<span id="cb87-2"><a href="#cb87-2"></a><span class="co"># Histogram of Local R² in Jurong East</span></span>
<span id="cb87-3"><a href="#cb87-3"></a><span class="fu">ggplot</span>(JurongEast_gwr, <span class="fu">aes</span>(<span class="at">x =</span> Local_R2)) <span class="sc">+</span></span>
<span id="cb87-4"><a href="#cb87-4"></a> <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">15</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb87-5"><a href="#cb87-5"></a> <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(Local_R2)), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb87-6"><a href="#cb87-6"></a> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Local R² in Jurong East Planning Area"</span>,</span>
<span id="cb87-7"><a href="#cb87-7"></a>      <span class="at">x =</span> <span class="st">"Local R²"</span>,</span>
<span id="cb87-8"><a href="#cb87-8"></a>      <span class="at">y =</span> <span class="st">"Frequency"</span>) <span class="sc">+</span></span>
<span id="cb87-9"><a href="#cb87-9"></a> <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="In-class_Ex07_files/figure-html/unnamed-chunk-56-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1"></a><span class="co"># Spatial Distribution of R² in Jurong East</span></span>
<span id="cb88-2"><a href="#cb88-2"></a><span class="co"># Map of Local R² in Jurong East</span></span>
<span id="cb88-3"><a href="#cb88-3"></a><span class="fu">tm_shape</span>(JurongEast_boundary) <span class="sc">+</span></span>
<span id="cb88-4"><a href="#cb88-4"></a> <span class="fu">tm_polygons</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">col =</span> <span class="st">"lightgray"</span>) <span class="sc">+</span></span>
<span id="cb88-5"><a href="#cb88-5"></a><span class="fu">tm_shape</span>(JurongEast_gwr) <span class="sc">+</span></span>
<span id="cb88-6"><a href="#cb88-6"></a> <span class="fu">tm_dots</span>(<span class="at">col =</span> <span class="st">"Local_R2"</span>,</span>
<span id="cb88-7"><a href="#cb88-7"></a>         <span class="at">palette =</span> <span class="st">"RdYlBu"</span>,</span>
<span id="cb88-8"><a href="#cb88-8"></a>         <span class="at">style =</span> <span class="st">"quantile"</span>,</span>
<span id="cb88-9"><a href="#cb88-9"></a>         <span class="at">size =</span> <span class="fl">0.8</span>,</span>
<span id="cb88-10"><a href="#cb88-10"></a>         <span class="at">title =</span> <span class="st">"Local R²"</span>) <span class="sc">+</span></span>
<span id="cb88-11"><a href="#cb88-11"></a> <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Local R² Distribution in Jurong East Planning Area"</span>,</span>
<span id="cb88-12"><a href="#cb88-12"></a>           <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="In-class_Ex07_files/figure-html/unnamed-chunk-56-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1"></a><span class="co"># Comparison with Overall R² Distribution</span></span>
<span id="cb89-2"><a href="#cb89-2"></a><span class="co"># Compare Jurong East with overall distribution</span></span>
<span id="cb89-3"><a href="#cb89-3"></a>overall_r2_stats <span class="ot">&lt;-</span> condo_resale.sf.adaptive <span class="sc">%&gt;%</span></span>
<span id="cb89-4"><a href="#cb89-4"></a> <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span></span>
<span id="cb89-5"><a href="#cb89-5"></a> <span class="fu">summarise</span>(</span>
<span id="cb89-6"><a href="#cb89-6"></a>   <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb89-7"><a href="#cb89-7"></a>   <span class="at">mean_r2 =</span> <span class="fu">mean</span>(Local_R2),</span>
<span id="cb89-8"><a href="#cb89-8"></a>   <span class="at">median_r2 =</span> <span class="fu">median</span>(Local_R2),</span>
<span id="cb89-9"><a href="#cb89-9"></a>   <span class="at">sd_r2 =</span> <span class="fu">sd</span>(Local_R2)</span>
<span id="cb89-10"><a href="#cb89-10"></a> )</span>
<span id="cb89-11"><a href="#cb89-11"></a>comparison <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb89-12"><a href="#cb89-12"></a> <span class="at">Area =</span> <span class="fu">c</span>(<span class="st">"Jurong East"</span>, <span class="st">"Overall"</span>),</span>
<span id="cb89-13"><a href="#cb89-13"></a> <span class="at">Mean_R2 =</span> <span class="fu">c</span>(JurongEast_r2_stats<span class="sc">$</span>mean_r2, overall_r2_stats<span class="sc">$</span>mean_r2),</span>
<span id="cb89-14"><a href="#cb89-14"></a> <span class="at">Median_R2 =</span> <span class="fu">c</span>(JurongEast_r2_stats<span class="sc">$</span>median_r2, overall_r2_stats<span class="sc">$</span>median_r2),</span>
<span id="cb89-15"><a href="#cb89-15"></a> <span class="at">SD_R2 =</span> <span class="fu">c</span>(JurongEast_r2_stats<span class="sc">$</span>sd_r2, overall_r2_stats<span class="sc">$</span>sd_r2)</span>
<span id="cb89-16"><a href="#cb89-16"></a>)</span>
<span id="cb89-17"><a href="#cb89-17"></a>comparison</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Area   Mean_R2 Median_R2      SD_R2
1 Jurong East 0.7570286 0.7624288 0.01566552
2     Overall 0.7801275 0.7796238 0.07250616</code></pre>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>