<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sathvika Subramanian">
<meta name="dcterms.date" content="2025-11-06">

<title>Take Home Exercise 3 – ISSS626</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">ISSS626</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex1-1.html">
 <span class="dropdown-text">Hands-on Exercise 1-1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex1-2.html">
 <span class="dropdown-text">Hands-on Exercise 1-2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex2-1&amp;2-2.html">
 <span class="dropdown-text">Hands-on Exercise 2-1 &amp; 2-2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex3.html">
 <span class="dropdown-text">Hands-on Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex4.html">
 <span class="dropdown-text">Hands-on Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex5-1.html">
 <span class="dropdown-text">Hands-on Exercise 5-1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex5-2.html">
 <span class="dropdown-text">Hands-on Exercise 5-2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex6.html">
 <span class="dropdown-text">Hands-on Exercise 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex7.html">
 <span class="dropdown-text">Hands-on Exercise 7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex8.html">
 <span class="dropdown-text">Hands-on Exercise 8</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex9.html">
 <span class="dropdown-text">Hands-on Exercise 9</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-class Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="../../Inclass_Ex/In_class_Ex3/In-class_Ex03a.html">
 <span class="dropdown-text">In-class Exercise 3a</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Inclass_Ex/In_class_Ex3/In-class_Ex03b.html">
 <span class="dropdown-text">In-class Exercise 3b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Inclass_Ex/In_class_Ex4/In-class_Ex04.html">
 <span class="dropdown-text">In-class Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Inclass_Ex/In_class_Ex5/In-class_Ex05.html">
 <span class="dropdown-text">In-class Exercise 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Inclass_Ex/In_class_Ex6/In-class_Ex06.html">
 <span class="dropdown-text">In-class Exercise 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Inclass_Ex/In_class_Ex7/In-class_Ex07.html">
 <span class="dropdown-text">In-class Exercise 7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Inclass_Ex/In_class_Ex8/In-class_Ex08.html">
 <span class="dropdown-text">In-class Exercise 8</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Inclass_Ex/In_class_Ex9/In-class_Ex09.html">
 <span class="dropdown-text">In-class Exercise 9</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Inclass_Ex/In_class_Ex10/In-class_Ex10.html">
 <span class="dropdown-text">In-class Exercise 10</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take Home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../Take_Home_Ex/Take_Home_Ex1/Take_Home_Ex1.html">
 <span class="dropdown-text">Take Home Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take_Home_Ex/Take_Home_Ex2/Take_Home_Ex2.html">
 <span class="dropdown-text">Take Home Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take_Home_Ex/Take_Home_Ex3/Take_Home_Ex3.html">
 <span class="dropdown-text">Take Home Exercise 3</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#modelling-hdb-resale-prices-with-geographically-weighted-methods" id="toc-modelling-hdb-resale-prices-with-geographically-weighted-methods" class="nav-link active" data-scroll-target="#modelling-hdb-resale-prices-with-geographically-weighted-methods">Modelling HDB Resale Prices with Geographically Weighted Methods</a></li>
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">1. Overview</a></li>
  <li><a href="#objectives" id="toc-objectives" class="nav-link" data-scroll-target="#objectives">2. Objectives</a></li>
  <li><a href="#installing-and-loading-packages" id="toc-installing-and-loading-packages" class="nav-link" data-scroll-target="#installing-and-loading-packages">3. Installing and Loading Packages</a></li>
  <li><a href="#hdb-resale-csv" id="toc-hdb-resale-csv" class="nav-link" data-scroll-target="#hdb-resale-csv">4. HDB resale CSV</a></li>
  <li><a href="#loading-geospatial-layers" id="toc-loading-geospatial-layers" class="nav-link" data-scroll-target="#loading-geospatial-layers">5. Loading Geospatial Layers</a></li>
  <li><a href="#assigning-hdb-to-subzone-centroids" id="toc-assigning-hdb-to-subzone-centroids" class="nav-link" data-scroll-target="#assigning-hdb-to-subzone-centroids">6. Assigning HDB to Subzone Centroids</a></li>
  <li><a href="#spatial-join-to-subzones" id="toc-spatial-join-to-subzones" class="nav-link" data-scroll-target="#spatial-join-to-subzones">7. Spatial Join to Subzones</a></li>
  <li><a href="#distance-within-radius-counts" id="toc-distance-within-radius-counts" class="nav-link" data-scroll-target="#distance-within-radius-counts">8. Distance / Within-Radius Counts</a></li>
  <li><a href="#cleaning-layers-and-scaling" id="toc-cleaning-layers-and-scaling" class="nav-link" data-scroll-target="#cleaning-layers-and-scaling">9. Cleaning Layers and Scaling</a></li>
  <li><a href="#train-test-split" id="toc-train-test-split" class="nav-link" data-scroll-target="#train-test-split">10. Train-Test Split</a></li>
  <li><a href="#global-ols-model" id="toc-global-ols-model" class="nav-link" data-scroll-target="#global-ols-model">11. Global OLS Model</a></li>
  <li><a href="#ols-residuals" id="toc-ols-residuals" class="nav-link" data-scroll-target="#ols-residuals">12. OLS Residuals</a></li>
  <li><a href="#gwr-model" id="toc-gwr-model" class="nav-link" data-scroll-target="#gwr-model">13. GWR Model</a></li>
  <li><a href="#comparing-ols-vs-gwr-coefficients-floor-area" id="toc-comparing-ols-vs-gwr-coefficients-floor-area" class="nav-link" data-scroll-target="#comparing-ols-vs-gwr-coefficients-floor-area">14. Comparing OLS vs GWR Coefficients (Floor Area)</a></li>
  <li><a href="#visualisation" id="toc-visualisation" class="nav-link" data-scroll-target="#visualisation">15. Visualisation</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">16. Conclusion</a></li>
  <li><a href="#future-work" id="toc-future-work" class="nav-link" data-scroll-target="#future-work">17. Future Work</a></li>
  </ul>
<div class="quarto-code-links"><h2>Code Links</h2><ul><li><a href="https://github.com/Sathvika-7284/ISSS626-geo"><i class="bi bi-file-code"></i>GitHub Repo</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take Home Exercise 3</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sathvika Subramanian </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 6, 2025</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">November 16, 2025</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="modelling-hdb-resale-prices-with-geographically-weighted-methods" class="level1">
<h1>Modelling HDB Resale Prices with Geographically Weighted Methods</h1>
</section>
<section id="overview" class="level1">
<h1>1. Overview</h1>
<p>This project aims to develop a spatially informed predictive model for 4-room HDB resale prices in Singapore, covering the period July 2024 to June 2025. Using HDB transaction data alongside a variety of geospatial datasets (subzones, hawker centres, parks, supermarkets, childcare, kindergartens, eldercare, and CHAS clinics), the analysis integrates structural and locational variables to model price variation. Both global (OLS) and local (GWR) regression approaches are applied, complemented by visualizations to explore spatial patterns in resale prices and residuals.</p>
</section>
<section id="objectives" class="level1">
<h1>2. Objectives</h1>
<p>The study aims to:</p>
<ul>
<li>Prepare and clean HDB resale data with structural variables (floor area, storey level, age).</li>
<li>Load and preprocess supporting geospatial datasets.</li>
<li>Assign HDB transactions to subzones and compute proximity-based locational variables.</li>
<li>Develop a train-test split for model validation.</li>
<li>Fit and compare global OLS and local GWR models.</li>
<li>Visualize HDB resale prices, locational features, and residuals spatially.</li>
</ul>
</section>
<section id="installing-and-loading-packages" class="level1">
<h1>3. Installing and Loading Packages</h1>
<p>Loads all R packages required for data manipulation. Ensures reproducibility by automatically installing missing packages.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse, sf, tmap, readxl, lwgeom, caret, janitor, stringr, GWmodel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 66%">
</colgroup>
<thead>
<tr class="header">
<th>Package</th>
<th>Purpose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>tidyverse</td>
<td>Collection of packages for data manipulation, cleaning, and visualization.</td>
</tr>
<tr class="even">
<td>sf</td>
<td>Handles spatial vector data (points, lines, polygons) and spatial operations.</td>
</tr>
<tr class="odd">
<td>tmap</td>
<td>Creates static and interactive thematic maps for geospatial visualization.</td>
</tr>
<tr class="even">
<td>readxl</td>
<td>Reads Excel files into R.</td>
</tr>
<tr class="odd">
<td>lwgeom</td>
<td>Provides advanced geometric operations for sf, including buffering and geodesic calculations.</td>
</tr>
<tr class="even">
<td>caret</td>
<td>Tools for machine learning and predictive modeling workflows, including train-test splitting.</td>
</tr>
<tr class="odd">
<td>janitor</td>
<td>Simplifies data cleaning tasks like standardizing column names and detecting duplicates.</td>
</tr>
<tr class="even">
<td>stringr</td>
<td>String manipulation and pattern matching functions for text processing.</td>
</tr>
<tr class="odd">
<td>GWmodel</td>
<td>Implements Geographically Weighted Regression and related spatial models.</td>
</tr>
</tbody>
</table>
</section>
<section id="hdb-resale-csv" class="level1">
<h1>4. HDB resale CSV</h1>
<p>Read in the HDB resale CSV, clean column names, filter for 4-room flats, and select transactions within the target period (July 2024–June 2025).Creates structural variables: storey_mid (mid-point of storey range), unit_age (years since lease commenced), and address (concatenated block and street).Prepares dataset for integration with geospatial data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a>hdb_fp <span class="ot">&lt;-</span> <span class="st">"data/HDBresale.csv"</span></span>
<span id="cb2-2"><a href="#cb2-2"></a></span>
<span id="cb2-3"><a href="#cb2-3"></a>HDB <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(hdb_fp) <span class="sc">|&gt;</span></span>
<span id="cb2-4"><a href="#cb2-4"></a>  <span class="fu">clean_names</span>()</span>
<span id="cb2-5"><a href="#cb2-5"></a></span>
<span id="cb2-6"><a href="#cb2-6"></a>HDB <span class="ot">&lt;-</span> HDB <span class="sc">|&gt;</span></span>
<span id="cb2-7"><a href="#cb2-7"></a>  <span class="fu">filter</span>(flat_type <span class="sc">==</span> <span class="st">"4 ROOM"</span>) <span class="sc">|&gt;</span></span>
<span id="cb2-8"><a href="#cb2-8"></a>  <span class="fu">filter</span>(month <span class="sc">&gt;=</span> <span class="st">"2024-07"</span> <span class="sc">&amp;</span> month <span class="sc">&lt;=</span> <span class="st">"2025-06"</span>)</span>
<span id="cb2-9"><a href="#cb2-9"></a></span>
<span id="cb2-10"><a href="#cb2-10"></a><span class="co"># Creating Structural Variables</span></span>
<span id="cb2-11"><a href="#cb2-11"></a>HDB <span class="ot">&lt;-</span> HDB <span class="sc">|&gt;</span></span>
<span id="cb2-12"><a href="#cb2-12"></a>  <span class="fu">mutate</span>(</span>
<span id="cb2-13"><a href="#cb2-13"></a>    <span class="at">storey_mid =</span> (<span class="fu">as.numeric</span>(<span class="fu">str_extract</span>(storey_range, <span class="st">"^</span><span class="sc">\\</span><span class="st">d+"</span>)) <span class="sc">+</span></span>
<span id="cb2-14"><a href="#cb2-14"></a>                    <span class="fu">as.numeric</span>(<span class="fu">str_extract</span>(storey_range, <span class="st">"</span><span class="sc">\\</span><span class="st">d+$"</span>))) <span class="sc">/</span> <span class="dv">2</span>,</span>
<span id="cb2-15"><a href="#cb2-15"></a>    <span class="at">unit_age =</span> <span class="dv">2025</span> <span class="sc">-</span> lease_commence_date,</span>
<span id="cb2-16"><a href="#cb2-16"></a>    <span class="at">address =</span> <span class="fu">paste</span>(block, street_name, <span class="st">"Singapore"</span>)</span>
<span id="cb2-17"><a href="#cb2-17"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This reads the HDB resale transaction data, cleans the column names, and performs initial data filtering and feature engineering</p>
<ul>
<li><strong>Filtering:</strong> The data is subsetted to include only ‘4 ROOM’ flat types and transactions occurring between July 2024 and June 20257. This targets a specific market segment and time frame</li>
<li><strong>Feature Engineering:</strong> Three new structural variables are created: storey_mid: The midpoint of the storey_range (e.g., 4-6 becomes 5) unit_age: The age of the flat in 2025, calculated as 2025 - lease_commence_date. address: A concatenated string of the block, street name, and “Singapore”</li>
<li><strong>Wrangling Relevance:</strong> This step transforms the raw aspatial data into a cleaner, more analytically useful dataframe, deriving two crucial continuous structural variables (storey_mid, unit_age) and preparing an address string that may be used for geocoding. The initial size of the dataset is 218,874 rows and 11 columns.</li>
</ul>
</section>
<section id="loading-geospatial-layers" class="level1">
<h1>5. Loading Geospatial Layers</h1>
<p>Safely read multiple shapefiles and GeoJSON files representing subzones, hawker centres, parks, supermarkets, childcare, kindergartens, eldercare, and CHAS clinics. CRS enforcement ensures all layers share a common projected coordinate system (EPSG:3414). Quick validation confirms successful loading of layers.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb3-2"><a href="#cb3-2"></a><span class="fu">library</span>(here)</span>
<span id="cb3-3"><a href="#cb3-3"></a></span>
<span id="cb3-4"><a href="#cb3-4"></a><span class="co"># Helper function for reading GeoJSON / shapefiles with CRS enforcement</span></span>
<span id="cb3-5"><a href="#cb3-5"></a>safe_read <span class="ot">&lt;-</span> <span class="cf">function</span>(fp, <span class="at">crs_out =</span> <span class="dv">3414</span>) {</span>
<span id="cb3-6"><a href="#cb3-6"></a>  obj <span class="ot">&lt;-</span> <span class="fu">tryCatch</span>(</span>
<span id="cb3-7"><a href="#cb3-7"></a>    <span class="fu">st_read</span>(fp, <span class="at">quiet =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-8"><a href="#cb3-8"></a>    <span class="at">error =</span> <span class="cf">function</span>(e) {</span>
<span id="cb3-9"><a href="#cb3-9"></a>      <span class="fu">warning</span>(<span class="fu">paste</span>(<span class="st">"Failed to read:"</span>, fp))</span>
<span id="cb3-10"><a href="#cb3-10"></a>      <span class="fu">return</span>(<span class="cn">NULL</span>)</span>
<span id="cb3-11"><a href="#cb3-11"></a>    }</span>
<span id="cb3-12"><a href="#cb3-12"></a>  )</span>
<span id="cb3-13"><a href="#cb3-13"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(obj)) {</span>
<span id="cb3-14"><a href="#cb3-14"></a>    <span class="cf">if</span> (<span class="fu">is.na</span>(<span class="fu">st_crs</span>(obj))) <span class="fu">st_crs</span>(obj) <span class="ot">&lt;-</span> crs_out</span>
<span id="cb3-15"><a href="#cb3-15"></a>    obj <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(obj, crs_out)</span>
<span id="cb3-16"><a href="#cb3-16"></a>  }</span>
<span id="cb3-17"><a href="#cb3-17"></a>  <span class="fu">return</span>(obj)</span>
<span id="cb3-18"><a href="#cb3-18"></a>}</span>
<span id="cb3-19"><a href="#cb3-19"></a></span>
<span id="cb3-20"><a href="#cb3-20"></a><span class="co"># File paths</span></span>
<span id="cb3-21"><a href="#cb3-21"></a>mp14_fp <span class="ot">&lt;-</span> <span class="fu">normalizePath</span>(<span class="st">"data/MP14_SUBZONE_WEB_PL.shp"</span>, <span class="at">mustWork =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-22"><a href="#cb3-22"></a>hawker_fp   <span class="ot">&lt;-</span> <span class="fu">normalizePath</span>(<span class="st">"data/HawkerCentresGEOJSON.geojson"</span>, <span class="at">mustWork =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-23"><a href="#cb3-23"></a>parks_fp    <span class="ot">&lt;-</span> <span class="fu">normalizePath</span>(<span class="st">"data/Parks.geojson"</span>, <span class="at">mustWork =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-24"><a href="#cb3-24"></a>super_fp    <span class="ot">&lt;-</span> <span class="fu">normalizePath</span>(<span class="st">"data/SupermarketsGEOJSON.geojson"</span>, <span class="at">mustWork =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-25"><a href="#cb3-25"></a>child_fp    <span class="ot">&lt;-</span> <span class="fu">normalizePath</span>(<span class="st">"data/ChildCareServices.geojson"</span>, <span class="at">mustWork =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-26"><a href="#cb3-26"></a>kinder_fp   <span class="ot">&lt;-</span> <span class="fu">normalizePath</span>(<span class="st">"data/Kindergartens.geojson"</span>, <span class="at">mustWork =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-27"><a href="#cb3-27"></a>elder_fp    <span class="ot">&lt;-</span> <span class="fu">normalizePath</span>(<span class="st">"data/ELDERCARE.shp"</span>, <span class="at">mustWork =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-28"><a href="#cb3-28"></a>chas_fp     <span class="ot">&lt;-</span> <span class="fu">normalizePath</span>(<span class="st">"data/CHASClinics.geojson"</span>, <span class="at">mustWork =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-29"><a href="#cb3-29"></a></span>
<span id="cb3-30"><a href="#cb3-30"></a><span class="co"># Loading layers</span></span>
<span id="cb3-31"><a href="#cb3-31"></a>MP14 <span class="ot">&lt;-</span> <span class="fu">safe_read</span>(mp14_fp)</span>
<span id="cb3-32"><a href="#cb3-32"></a><span class="cf">if</span> (<span class="fu">is.null</span>(MP14)) <span class="fu">stop</span>(<span class="st">"MP14_SUBZONE_WEB_PL.shp missing — required layer."</span>)</span>
<span id="cb3-33"><a href="#cb3-33"></a></span>
<span id="cb3-34"><a href="#cb3-34"></a>hawker       <span class="ot">&lt;-</span> <span class="fu">safe_read</span>(hawker_fp)</span>
<span id="cb3-35"><a href="#cb3-35"></a>parks        <span class="ot">&lt;-</span> <span class="fu">safe_read</span>(parks_fp)</span>
<span id="cb3-36"><a href="#cb3-36"></a>supermarkets <span class="ot">&lt;-</span> <span class="fu">safe_read</span>(super_fp)</span>
<span id="cb3-37"><a href="#cb3-37"></a>childcare    <span class="ot">&lt;-</span> <span class="fu">safe_read</span>(child_fp)</span>
<span id="cb3-38"><a href="#cb3-38"></a>kinderg      <span class="ot">&lt;-</span> <span class="fu">safe_read</span>(kinder_fp)</span>
<span id="cb3-39"><a href="#cb3-39"></a>eldercare    <span class="ot">&lt;-</span> <span class="fu">safe_read</span>(elder_fp)</span>
<span id="cb3-40"><a href="#cb3-40"></a>chas         <span class="ot">&lt;-</span> <span class="fu">safe_read</span>(chas_fp)</span>
<span id="cb3-41"><a href="#cb3-41"></a></span>
<span id="cb3-42"><a href="#cb3-42"></a><span class="co"># Quick checks</span></span>
<span id="cb3-43"><a href="#cb3-43"></a>layers <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb3-44"><a href="#cb3-44"></a>  <span class="at">MP14 =</span> MP14,</span>
<span id="cb3-45"><a href="#cb3-45"></a>  <span class="at">Hawker =</span> hawker,</span>
<span id="cb3-46"><a href="#cb3-46"></a>  <span class="at">Parks =</span> parks,</span>
<span id="cb3-47"><a href="#cb3-47"></a>  <span class="at">Supermarkets =</span> supermarkets,</span>
<span id="cb3-48"><a href="#cb3-48"></a>  <span class="at">Childcare =</span> childcare,</span>
<span id="cb3-49"><a href="#cb3-49"></a>  <span class="at">Kindergartens =</span> kinderg,</span>
<span id="cb3-50"><a href="#cb3-50"></a>  <span class="at">Eldercare =</span> eldercare,</span>
<span id="cb3-51"><a href="#cb3-51"></a>  <span class="at">CHAS =</span> chas</span>
<span id="cb3-52"><a href="#cb3-52"></a>)</span>
<span id="cb3-53"><a href="#cb3-53"></a></span>
<span id="cb3-54"><a href="#cb3-54"></a><span class="cf">for</span> (nm <span class="cf">in</span> <span class="fu">names</span>(layers)) {</span>
<span id="cb3-55"><a href="#cb3-55"></a>  <span class="fu">cat</span>(nm, <span class="st">"loaded:"</span>, <span class="sc">!</span><span class="fu">is.null</span>(layers[[nm]]), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb3-56"><a href="#cb3-56"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>MP14 loaded: TRUE 
Hawker loaded: TRUE 
Parks loaded: TRUE 
Supermarkets loaded: TRUE 
Childcare loaded: TRUE 
Kindergartens loaded: TRUE 
Eldercare loaded: TRUE 
CHAS loaded: TRUE </code></pre>
</div>
</div>
<p>This step sets up all the ancillary geographic data needed to calculate locational variables, standardizing their CRS to ensure compatibility with the HDB data</p>
</section>
<section id="assigning-hdb-to-subzone-centroids" class="level1">
<h1>6. Assigning HDB to Subzone Centroids</h1>
<p>Assign each HDB transaction to the nearest subzone centroid using st_nearest_feature.Allows aggregation or analysis of HDB prices by subzone.Ensures spatial alignment between point data (HDB) and polygon data (subzones).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb5-2"><a href="#cb5-2"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb5-3"><a href="#cb5-3"></a></span>
<span id="cb5-4"><a href="#cb5-4"></a><span class="co"># Transforming subzone to projected CRS (meters)</span></span>
<span id="cb5-5"><a href="#cb5-5"></a>subzone_centroids <span class="ot">&lt;-</span> <span class="fu">st_point_on_surface</span>(MP14) <span class="sc">%&gt;%</span></span>
<span id="cb5-6"><a href="#cb5-6"></a>  <span class="fu">select</span>(SUBZONE_N, PLN_AREA_N, geometry) <span class="sc">%&gt;%</span></span>
<span id="cb5-7"><a href="#cb5-7"></a>  <span class="fu">st_transform</span>(<span class="dv">3414</span>)</span>
<span id="cb5-8"><a href="#cb5-8"></a></span>
<span id="cb5-9"><a href="#cb5-9"></a><span class="co"># Assigning all points to nearest subzone centroid</span></span>
<span id="cb5-10"><a href="#cb5-10"></a><span class="co"># Creating empty HDB points with same number of rows as HDB</span></span>
<span id="cb5-11"><a href="#cb5-11"></a>HDB_sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(HDB, <span class="at">geometry =</span> <span class="fu">st_geometry</span>(subzone_centroids)[<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(HDB<span class="sc">$</span>flat_type)]) <span class="co"># placeholder</span></span>
<span id="cb5-12"><a href="#cb5-12"></a></span>
<span id="cb5-13"><a href="#cb5-13"></a><span class="co"># Assigning each HDB to nearest subzone centroid</span></span>
<span id="cb5-14"><a href="#cb5-14"></a>HDB_geo <span class="ot">&lt;-</span> <span class="fu">st_join</span>(HDB_sf, subzone_centroids, <span class="at">join =</span> st_nearest_feature)</span>
<span id="cb5-15"><a href="#cb5-15"></a></span>
<span id="cb5-16"><a href="#cb5-16"></a><span class="co"># Validating</span></span>
<span id="cb5-17"><a href="#cb5-17"></a><span class="fu">table</span>(<span class="fu">is.na</span>(HDB_geo<span class="sc">$</span>SUBZONE_N))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
FALSE  TRUE 
  323 11357 </code></pre>
</div>
</div>
<ul>
<li><strong>Interpretation:</strong> This attempts to make the aspatial HDB data spatial by assigning each flat to the nearest centroid of a planning subzone.</li>
<li><strong>Centroid Creation:</strong> It calculates the representative central point of each subzone polygon in MP14 using st_point_on_surface().</li>
<li><strong>HDB Georeferencing:</strong> The HDB data is converted to an sf object (HDB_sf) using placeholder geometry. It then uses st_join(…, join = st_nearest_feature) to join each HDB record to its closest subzone centroid. This effectively assigns a proxy coordinate (the subzone centroid) to each HDB flat, treating it as its location for subsequent spatial operations.</li>
<li><strong>Validation:</strong> The output shows that 11,357 HDB records were successfully assigned a SUBZONE_N (meaning they found a nearest subzone centroid), but 323 records resulted in NA. The reason for the small number of successful joins (11,357) compared to the initial number of rows is not explicitly clear from the provided code, but the validation shows the number of non-missing (FALSE) and missing (TRUE) subzone assignments.</li>
<li><strong>Wrangling Relevance:</strong> This is the critical step that transforms the non-geographically referenced HDB data into a geographically referenced analytical sandbox (HDB_geo) using a proxy location.</li>
</ul>
</section>
<section id="spatial-join-to-subzones" class="level1">
<h1>7. Spatial Join to Subzones</h1>
<p>Attach subzone attributes (PLN_AREA_N, SUBZONE_N) to each HDB point.Facilitates subzone-level analysis and supports downstream geospatial computations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="co"># Attaching subzone attributes to HDB points</span></span>
<span id="cb7-2"><a href="#cb7-2"></a>HDB_geo <span class="ot">&lt;-</span> <span class="fu">st_join</span>(</span>
<span id="cb7-3"><a href="#cb7-3"></a>  HDB_geo,</span>
<span id="cb7-4"><a href="#cb7-4"></a>  MP14 <span class="sc">%&gt;%</span> <span class="fu">select</span>(PLN_AREA_N, SUBZONE_N)</span>
<span id="cb7-5"><a href="#cb7-5"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Although the nearest centroid join already assigned a subzone name, this step is used to attach all relevant planning area/subzone attributes from the actual polygons. This is essential if the analysis were to include any subzone-level variables</p>
</section>
<section id="distance-within-radius-counts" class="level1">
<h1>8. Distance / Within-Radius Counts</h1>
<p>Compute the minimum distance from each HDB to nearby points of interest (POIs) such as hawker centres, parks, and eldercare. Functions dist_min_vec and count_within_vec calculate distances and counts within a specified radius.Adds locational predictors to HDB dataset, supporting spatially aware modeling.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a><span class="fu">library</span>(units)</span>
<span id="cb8-2"><a href="#cb8-2"></a></span>
<span id="cb8-3"><a href="#cb8-3"></a>dist_min_vec <span class="ot">&lt;-</span> <span class="cf">function</span>(hdb_pts, poi_pts) {</span>
<span id="cb8-4"><a href="#cb8-4"></a>  <span class="cf">if</span> (<span class="fu">is.null</span>(poi_pts)) <span class="fu">return</span>(<span class="fu">rep</span>(<span class="dv">999</span>, <span class="fu">nrow</span>(hdb_pts)))</span>
<span id="cb8-5"><a href="#cb8-5"></a>  dist_mat <span class="ot">&lt;-</span> <span class="fu">st_distance</span>(hdb_pts, poi_pts)</span>
<span id="cb8-6"><a href="#cb8-6"></a>  dist_mat <span class="ot">&lt;-</span> <span class="fu">drop_units</span>(dist_mat)</span>
<span id="cb8-7"><a href="#cb8-7"></a>  <span class="fu">apply</span>(dist_mat, <span class="dv">1</span>, min) <span class="sc">/</span> <span class="dv">1000</span>  <span class="co"># km</span></span>
<span id="cb8-8"><a href="#cb8-8"></a>}</span>
<span id="cb8-9"><a href="#cb8-9"></a></span>
<span id="cb8-10"><a href="#cb8-10"></a>count_within_vec <span class="ot">&lt;-</span> <span class="cf">function</span>(hdb_pts, poi_pts, radius_m) {</span>
<span id="cb8-11"><a href="#cb8-11"></a>  <span class="cf">if</span> (<span class="fu">is.null</span>(poi_pts)) <span class="fu">return</span>(<span class="fu">rep</span>(<span class="dv">0</span>, <span class="fu">nrow</span>(hdb_pts)))</span>
<span id="cb8-12"><a href="#cb8-12"></a>  dist_mat <span class="ot">&lt;-</span> <span class="fu">st_distance</span>(hdb_pts, poi_pts)</span>
<span id="cb8-13"><a href="#cb8-13"></a>  dist_mat <span class="ot">&lt;-</span> <span class="fu">drop_units</span>(dist_mat)</span>
<span id="cb8-14"><a href="#cb8-14"></a>  <span class="fu">rowSums</span>(dist_mat <span class="sc">&lt;=</span> radius_m)</span>
<span id="cb8-15"><a href="#cb8-15"></a>}</span>
<span id="cb8-16"><a href="#cb8-16"></a></span>
<span id="cb8-17"><a href="#cb8-17"></a><span class="co"># Computing distances and within-radius counts</span></span>
<span id="cb8-18"><a href="#cb8-18"></a><span class="co"># Computing distances only if HDB coordinates are valid</span></span>
<span id="cb8-19"><a href="#cb8-19"></a>HDB_geo <span class="ot">&lt;-</span> HDB_geo <span class="sc">%&gt;%</span></span>
<span id="cb8-20"><a href="#cb8-20"></a>  <span class="fu">mutate</span>(</span>
<span id="cb8-21"><a href="#cb8-21"></a>    <span class="at">dist_hawker_km   =</span> <span class="cf">if</span>(<span class="sc">!</span><span class="fu">is.null</span>(hawker)) <span class="fu">dist_min_vec</span>(., hawker) <span class="cf">else</span> <span class="cn">NA</span>,</span>
<span id="cb8-22"><a href="#cb8-22"></a>    <span class="at">dist_park_km     =</span> <span class="cf">if</span>(<span class="sc">!</span><span class="fu">is.null</span>(parks)) <span class="fu">dist_min_vec</span>(., parks) <span class="cf">else</span> <span class="cn">NA</span>,</span>
<span id="cb8-23"><a href="#cb8-23"></a>    <span class="at">dist_super_km    =</span> <span class="cf">if</span>(<span class="sc">!</span><span class="fu">is.null</span>(supermarkets)) <span class="fu">dist_min_vec</span>(., supermarkets) <span class="cf">else</span> <span class="cn">NA</span>,</span>
<span id="cb8-24"><a href="#cb8-24"></a>    <span class="at">dist_elder_km    =</span> <span class="cf">if</span>(<span class="sc">!</span><span class="fu">is.null</span>(eldercare)) <span class="fu">dist_min_vec</span>(., eldercare) <span class="cf">else</span> <span class="cn">NA</span>,</span>
<span id="cb8-25"><a href="#cb8-25"></a>    <span class="at">dist_chas_km     =</span> <span class="cf">if</span>(<span class="sc">!</span><span class="fu">is.null</span>(chas)) <span class="fu">dist_min_vec</span>(., chas) <span class="cf">else</span> <span class="cn">NA</span>,</span>
<span id="cb8-26"><a href="#cb8-26"></a>    <span class="at">dist_kinderg_km     =</span> <span class="cf">if</span>(<span class="sc">!</span><span class="fu">is.null</span>(kinderg)) <span class="fu">dist_min_vec</span>(., kinderg) <span class="cf">else</span> <span class="cn">NA</span>,</span>
<span id="cb8-27"><a href="#cb8-27"></a>    <span class="at">dist_childcare_km     =</span> <span class="cf">if</span>(<span class="sc">!</span><span class="fu">is.null</span>(childcare)) <span class="fu">dist_min_vec</span>(., childcare) <span class="cf">else</span> <span class="cn">NA</span></span>
<span id="cb8-28"><a href="#cb8-28"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Summarizes mean distances for exploratory insights.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="co"># Summary of locational predictors</span></span>
<span id="cb9-2"><a href="#cb9-2"></a>loc_summary <span class="ot">&lt;-</span> HDB_geo <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4"></a>  <span class="fu">summarise</span>(</span>
<span id="cb9-5"><a href="#cb9-5"></a>    <span class="at">mean_dist_hawker_km  =</span> <span class="fu">mean</span>(dist_hawker_km, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb9-6"><a href="#cb9-6"></a>    <span class="at">mean_dist_park_km    =</span> <span class="fu">mean</span>(dist_park_km, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb9-7"><a href="#cb9-7"></a>    <span class="at">mean_dist_super_km   =</span> <span class="fu">mean</span>(dist_super_km, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb9-8"><a href="#cb9-8"></a>    <span class="at">mean_dist_elder_km   =</span> <span class="fu">mean</span>(dist_elder_km, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb9-9"><a href="#cb9-9"></a>    <span class="at">mean_dist_chas_km   =</span> <span class="fu">mean</span>(dist_chas_km, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb9-10"><a href="#cb9-10"></a>    <span class="at">mean_dist_kinderg_km   =</span> <span class="fu">mean</span>(dist_kinderg_km, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb9-11"><a href="#cb9-11"></a>    <span class="at">mean_dist_childcare_km   =</span> <span class="fu">mean</span>(dist_childcare_km, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb9-12"><a href="#cb9-12"></a>  )</span>
<span id="cb9-13"><a href="#cb9-13"></a>loc_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 7
  mean_dist_hawker_km mean_dist_park_km mean_dist_super_km mean_dist_elder_km
                &lt;dbl&gt;             &lt;dbl&gt;              &lt;dbl&gt;              &lt;dbl&gt;
1                1.34              1.02              0.738               1.62
# ℹ 3 more variables: mean_dist_chas_km &lt;dbl&gt;, mean_dist_kinderg_km &lt;dbl&gt;,
#   mean_dist_childcare_km &lt;dbl&gt;</code></pre>
</div>
</div>
<ul>
<li><strong>Interpretation:</strong> This is the core of the location variable derivation, calculating the shortest distance from each HDB flat to the nearest POI (Point of Interest).</li>
<li><strong>Custom Functions:</strong> The dist_min_vec function computes the minimum distance between HDB points and a POI layer, converts the result from meters to kilometers (km), and handles cases where a POI layer is missing by returning 999.</li>
<li><strong>Variable Creation:</strong> New variables (dist_hawker_km, dist_park_km, etc.) are added to HDB_geo .</li>
<li><strong>Summary:</strong> The summary table shows the mean minimum distance (in km) from all HDB flats to each POI: Closest: Supermarkets (0.738 km) and CHAS Clinics (0.722 km). Farthest: Eldercare Centres (1.619 km).</li>
<li><strong>Wrangling Relevance:</strong> This step successfully derives a set of continuous locational predictors (distance to amenities) by leveraging the geographically referenced HDB data and the POI layers, which is a major requirement for the analysis</li>
</ul>
</section>
<section id="cleaning-layers-and-scaling" class="level1">
<h1>9. Cleaning Layers and Scaling</h1>
<p>Remove HDB listings with missing resale prices or distance measures. Defines a safe_scale function for standardizing variables, preparing them for regression modeling.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a><span class="co"># Removing HDB listings with missing resale price or distance</span></span>
<span id="cb11-2"><a href="#cb11-2"></a>HDB_geo <span class="ot">&lt;-</span> HDB_geo <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(resale_price)) <span class="sc">%&gt;%</span></span>
<span id="cb11-4"><a href="#cb11-4"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(dist_hawker_km)) <span class="sc">%&gt;%</span></span>
<span id="cb11-5"><a href="#cb11-5"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(dist_park_km)) <span class="sc">%&gt;%</span></span>
<span id="cb11-6"><a href="#cb11-6"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(dist_super_km)) <span class="sc">%&gt;%</span></span>
<span id="cb11-7"><a href="#cb11-7"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(dist_elder_km)) <span class="sc">%&gt;%</span></span>
<span id="cb11-8"><a href="#cb11-8"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(dist_chas_km)) <span class="sc">%&gt;%</span></span>
<span id="cb11-9"><a href="#cb11-9"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(dist_kinderg_km)) <span class="sc">%&gt;%</span></span>
<span id="cb11-10"><a href="#cb11-10"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(dist_childcare_km))</span>
<span id="cb11-11"><a href="#cb11-11"></a></span>
<span id="cb11-12"><a href="#cb11-12"></a><span class="co"># Scaling function</span></span>
<span id="cb11-13"><a href="#cb11-13"></a>safe_scale <span class="ot">&lt;-</span> <span class="cf">function</span>(x) (x <span class="sc">-</span> <span class="fu">mean</span>(x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">/</span> <span class="fu">sd</span>(x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This final cleaning step prepares a high-quality, complete dataset for modeling and ensures that the distance variables are valid for every record . The scaling function is defined in anticipation of the GWR model, which often benefits from scaled predictors.</p>
</section>
<section id="train-test-split" class="level1">
<h1>10. Train-Test Split</h1>
<p>Split dataset into training (80%) and testing (20%) sets using stratified sampling on resale price.Enables model validation and performance assessment.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb12-2"><a href="#cb12-2"></a>train_idx <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(HDB_geo<span class="sc">$</span>resale_price, <span class="at">p =</span> <span class="fl">0.8</span>, <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb12-3"><a href="#cb12-3"></a></span>
<span id="cb12-4"><a href="#cb12-4"></a>train <span class="ot">&lt;-</span> HDB_geo[train_idx, ]</span>
<span id="cb12-5"><a href="#cb12-5"></a>test  <span class="ot">&lt;-</span> HDB_geo[<span class="sc">-</span>train_idx, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This step is crucial for model validation and reproducibility, ensuring the model’s performance can be assessed on unseen data</p>
</section>
<section id="global-ols-model" class="level1">
<h1>11. Global OLS Model</h1>
<p>Fit an Ordinary Least Squares regression using structural and locational predictors.Drops predictors with zero variance and ensures numeric type.Provides a baseline global model for comparison against spatially varying models.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb13-2"><a href="#cb13-2"></a></span>
<span id="cb13-3"><a href="#cb13-3"></a><span class="co"># Defining predictors</span></span>
<span id="cb13-4"><a href="#cb13-4"></a>predictors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"floor_area_sqm"</span>,<span class="st">"storey_mid"</span>,<span class="st">"unit_age"</span>,</span>
<span id="cb13-5"><a href="#cb13-5"></a>                <span class="st">"dist_hawker_km"</span>,<span class="st">"dist_park_km"</span>,<span class="st">"dist_super_km"</span>,</span>
<span id="cb13-6"><a href="#cb13-6"></a>                <span class="st">"dist_elder_km"</span>,<span class="st">"dist_chas_km"</span>, <span class="st">"dist_kinderg_km"</span>, <span class="st">"dist_childcare_km"</span>)</span>
<span id="cb13-7"><a href="#cb13-7"></a></span>
<span id="cb13-8"><a href="#cb13-8"></a><span class="co"># Creating a numeric-only training dataframe</span></span>
<span id="cb13-9"><a href="#cb13-9"></a>train_numeric <span class="ot">&lt;-</span> train <span class="sc">%&gt;%</span></span>
<span id="cb13-10"><a href="#cb13-10"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span>        <span class="co"># remove geometry</span></span>
<span id="cb13-11"><a href="#cb13-11"></a>  <span class="fu">select</span>(<span class="fu">all_of</span>(<span class="fu">c</span>(<span class="st">"resale_price"</span>, predictors))) <span class="sc">%&gt;%</span> </span>
<span id="cb13-12"><a href="#cb13-12"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span><span class="fu">as.numeric</span>(<span class="fu">as.character</span>(.)))) <span class="co"># ensure numeric</span></span>
<span id="cb13-13"><a href="#cb13-13"></a></span>
<span id="cb13-14"><a href="#cb13-14"></a><span class="co"># Dropping predictors with zero variance</span></span>
<span id="cb13-15"><a href="#cb13-15"></a>var_ok <span class="ot">&lt;-</span> <span class="fu">sapply</span>(train_numeric[predictors], <span class="cf">function</span>(x) <span class="fu">sd</span>(x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb13-16"><a href="#cb13-16"></a>predictors <span class="ot">&lt;-</span> predictors[var_ok]</span>
<span id="cb13-17"><a href="#cb13-17"></a></span>
<span id="cb13-18"><a href="#cb13-18"></a><span class="co"># Fitting OLS model</span></span>
<span id="cb13-19"><a href="#cb13-19"></a>model_glm <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb13-20"><a href="#cb13-20"></a>  <span class="fu">formula</span>(<span class="fu">paste</span>(<span class="st">"resale_price ~"</span>, <span class="fu">paste</span>(predictors, <span class="at">collapse =</span> <span class="st">" + "</span>))),</span>
<span id="cb13-21"><a href="#cb13-21"></a>  <span class="at">data =</span> train_numeric</span>
<span id="cb13-22"><a href="#cb13-22"></a>)</span>
<span id="cb13-23"><a href="#cb13-23"></a></span>
<span id="cb13-24"><a href="#cb13-24"></a><span class="fu">summary</span>(model_glm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = formula(paste("resale_price ~", paste(predictors, 
    collapse = " + "))), data = train_numeric)

Residuals:
    Min      1Q  Median      3Q     Max 
-122374  -31260   -2144   30446  141216 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       631596.1    58971.9  10.710  &lt; 2e-16 ***
floor_area_sqm      2581.5      621.2   4.156 4.46e-05 ***
storey_mid          7831.4      598.1  13.095  &lt; 2e-16 ***
unit_age           -8460.8      217.2 -38.960  &lt; 2e-16 ***
dist_hawker_km     -3266.8     6082.7  -0.537   0.5917    
dist_park_km       -3838.5     5540.5  -0.693   0.4891    
dist_super_km        524.9     7586.4   0.069   0.9449    
dist_elder_km        175.8     4643.1   0.038   0.9698    
dist_chas_km        1777.5     7893.0   0.225   0.8220    
dist_kinderg_km   -18608.0     9560.5  -1.946   0.0527 .  
dist_childcare_km  25575.3    11340.4   2.255   0.0250 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 47010 on 248 degrees of freedom
Multiple R-squared:  0.9121,    Adjusted R-squared:  0.9086 
F-statistic: 257.4 on 10 and 248 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><p><strong>Interpretation:</strong> A Global Ordinary Least Squares (OLS) model is fitted to the training data to predict resale_price using the three structural variables and seven distance variables.</p></li>
<li><p><strong>Model Fit:</strong> The model has a Multiple R-squared of 0.9121 and an Adjusted R-squared of 0.908648, indicating it explains a very high proportion of the variance in HDB resale prices. The F-statistic is highly significant.</p></li>
<li><p><strong>Significant Predictors (p &lt; 0.05):</strong></p>
<p>floor_area_sqm: Positive effect (<span class="math inline">\(\beta = 2581.5\)</span> per sqm), highly significant</p>
<p>storey_mid: Positive effect (<span class="math inline">\(\beta = 7831.4\)</span>), highly significant</p>
<p>unit_age: Negative effect (<span class="math inline">\(\beta = -8460.8\)</span> per year), highly significant</p>
<p>dist_childcare_km: Positive effect (<span class="math inline">\(\beta = 25575.3\)</span> per km), significant at p &lt; 0.05</p></li>
<li><p><strong>Marginally Significant Predictor (p &lt; 0.1):</strong></p>
<p>dist_kinderg_km: Negative effect (<span class="math inline">\(\beta = -18608.0\)</span> per km), marginally significant.</p></li>
<li><p><strong>Insignificant Predictors:</strong> Distance to hawker, park, supermarket, eldercare, and CHAS clinics were all found to be statistically insignificant in this global model.</p></li>
<li><p><strong>Analysis Relevance:</strong> The OLS model establishes a baseline global relationship. The high R-squared suggests the variables are good predictors overall, but the insignificance of most distance variables suggests a potential lack of a global stationary relationship, hinting at the need for a spatial model like GWR.</p></li>
</ul>
</section>
<section id="ols-residuals" class="level1">
<h1>12. OLS Residuals</h1>
<p>Predict resale prices using OLS and compute residuals.Visualizes residuals spatially using tmap and distributionally with a histogram.Identifies areas where the OLS model over- or under-predicts prices, informing potential local effects.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb15-2"><a href="#cb15-2"></a></span>
<span id="cb15-3"><a href="#cb15-3"></a><span class="co"># Predicting resale_price for all HDB points</span></span>
<span id="cb15-4"><a href="#cb15-4"></a>HDB_geo<span class="sc">$</span>pred_price <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_glm, <span class="at">newdata =</span> <span class="fu">st_drop_geometry</span>(HDB_geo))</span>
<span id="cb15-5"><a href="#cb15-5"></a></span>
<span id="cb15-6"><a href="#cb15-6"></a><span class="co"># Computing residuals</span></span>
<span id="cb15-7"><a href="#cb15-7"></a>HDB_geo<span class="sc">$</span>ols_resid <span class="ot">&lt;-</span> HDB_geo<span class="sc">$</span>resale_price <span class="sc">-</span> HDB_geo<span class="sc">$</span>pred_price</span>
<span id="cb15-8"><a href="#cb15-8"></a></span>
<span id="cb15-9"><a href="#cb15-9"></a><span class="co"># Summary of residuals</span></span>
<span id="cb15-10"><a href="#cb15-10"></a><span class="fu">summary</span>(HDB_geo<span class="sc">$</span>ols_resid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
-122374  -28126   -2144    1844   31451  148510 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a><span class="co"># Singapore boundary polygon (union of all planning areas)</span></span>
<span id="cb17-2"><a href="#cb17-2"></a>sg_boundary <span class="ot">&lt;-</span> <span class="fu">st_union</span>(MP14)</span>
<span id="cb17-3"><a href="#cb17-3"></a></span>
<span id="cb17-4"><a href="#cb17-4"></a><span class="co"># Spatial visualisation of residuals</span></span>
<span id="cb17-5"><a href="#cb17-5"></a>tm_ols_resid <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(sg_boundary) <span class="sc">+</span></span>
<span id="cb17-6"><a href="#cb17-6"></a>  <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"white"</span>, <span class="at">border.col =</span> <span class="st">"black"</span>) <span class="sc">+</span>  <span class="co"># Singapore outline</span></span>
<span id="cb17-7"><a href="#cb17-7"></a>  <span class="fu">tm_shape</span>(HDB_geo) <span class="sc">+</span></span>
<span id="cb17-8"><a href="#cb17-8"></a>  <span class="fu">tm_dots</span>(</span>
<span id="cb17-9"><a href="#cb17-9"></a>    <span class="at">col =</span> <span class="st">"ols_resid"</span>,</span>
<span id="cb17-10"><a href="#cb17-10"></a>    <span class="at">palette =</span> <span class="st">"-RdBu"</span>,</span>
<span id="cb17-11"><a href="#cb17-11"></a>    <span class="at">style =</span> <span class="st">"quantile"</span>,          <span class="co"># better color scaling</span></span>
<span id="cb17-12"><a href="#cb17-12"></a>    <span class="at">size =</span> <span class="fl">0.3</span>,</span>
<span id="cb17-13"><a href="#cb17-13"></a>    <span class="at">fill_alpha =</span> <span class="fl">0.7</span>,</span>
<span id="cb17-14"><a href="#cb17-14"></a>    <span class="at">title =</span> <span class="st">"OLS Residuals (SGD)"</span></span>
<span id="cb17-15"><a href="#cb17-15"></a>  ) <span class="sc">+</span></span>
<span id="cb17-16"><a href="#cb17-16"></a>  <span class="fu">tm_layout</span>(</span>
<span id="cb17-17"><a href="#cb17-17"></a>    <span class="at">main.title =</span> <span class="st">"Spatial Distribution of OLS Residuals"</span>,</span>
<span id="cb17-18"><a href="#cb17-18"></a>    <span class="at">legend.outside =</span> <span class="cn">TRUE</span></span>
<span id="cb17-19"><a href="#cb17-19"></a>  )</span>
<span id="cb17-20"><a href="#cb17-20"></a>tm_ols_resid</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_Home_Ex3_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a><span class="co"># Histogram of residuals</span></span>
<span id="cb18-2"><a href="#cb18-2"></a><span class="fu">ggplot</span>(HDB_geo, <span class="fu">aes</span>(<span class="at">x =</span> ols_resid)) <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">50</span>, <span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4"></a>  <span class="fu">labs</span>(</span>
<span id="cb18-5"><a href="#cb18-5"></a>    <span class="at">title =</span> <span class="st">"Histogram of OLS Residuals"</span>,</span>
<span id="cb18-6"><a href="#cb18-6"></a>    <span class="at">x =</span> <span class="st">"Residual (SGD)"</span>,</span>
<span id="cb18-7"><a href="#cb18-7"></a>    <span class="at">y =</span> <span class="st">"Count"</span></span>
<span id="cb18-8"><a href="#cb18-8"></a>  ) <span class="sc">+</span></span>
<span id="cb18-9"><a href="#cb18-9"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_Home_Ex3_files/figure-html/unnamed-chunk-11-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><strong>Interpretation:</strong> This code calculates and visualizes the residuals (actual price - predicted price) from the OLS model.</li>
<li><strong>Summary:</strong> Residuals range from -122,374 SGD to 141,216 SGD.</li>
<li><strong>Spatial Distribution (Map):</strong> The map shows a clear spatial clustering of residuals . Positive Residuals (Red/Orange): Flats that the OLS model under-predicted the price for (i.e., they are more expensive than expected) are clustered in the Central/Southern parts of Singapore . Negative Residuals (Blue): Flats that the OLS model over-predicted the price for (i.e., they are cheaper than expected) are clustered mostly in the Northern and Western parts .</li>
<li><strong>Histogram:</strong> The histogram shows that the residuals are relatively symmetrically distributed around zero, but the distribution is slightly leptokurtic (more peaked than a normal distribution) .</li>
<li><strong>Analysis Relevance:</strong> The distinct spatial pattern in the residuals (clustering of over- and under-predictions) is a strong indicator of spatial non-stationarity . This violates a key assumption of OLS and justifies the use of the Geographically Weighted Regression (GWR) model in the next step, as GWR is designed to model coefficients that vary across space.</li>
</ul>
</section>
<section id="gwr-model" class="level1">
<h1>13. GWR Model</h1>
<p>Fit a Geographically Weighted Regression (GWR) model to capture spatial heterogeneity in predictor effects.Standardizes predictors and selects those with non-zero variance. Determines optimal bandwidth using AICc and fits a local model at each HDB point. Converts results to an sf object for mapping and analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a><span class="co"># Loading required package</span></span>
<span id="cb19-2"><a href="#cb19-2"></a><span class="fu">library</span>(GWmodel)</span>
<span id="cb19-3"><a href="#cb19-3"></a></span>
<span id="cb19-4"><a href="#cb19-4"></a><span class="co"># Only keeping predictors with variance &gt; 0</span></span>
<span id="cb19-5"><a href="#cb19-5"></a>df <span class="ot">&lt;-</span> <span class="fu">st_drop_geometry</span>(HDB_geo)[, <span class="fu">c</span>(<span class="st">"resale_price"</span>, predictors)]</span>
<span id="cb19-6"><a href="#cb19-6"></a>var_ok <span class="ot">&lt;-</span> <span class="fu">sapply</span>(df[predictors], <span class="cf">function</span>(x) <span class="fu">sd</span>(x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb19-7"><a href="#cb19-7"></a>predictors_gwr <span class="ot">&lt;-</span> predictors[var_ok]</span>
<span id="cb19-8"><a href="#cb19-8"></a>df <span class="ot">&lt;-</span> df[, <span class="fu">c</span>(<span class="st">"resale_price"</span>, predictors_gwr)]</span>
<span id="cb19-9"><a href="#cb19-9"></a></span>
<span id="cb19-10"><a href="#cb19-10"></a><span class="co"># Scaling</span></span>
<span id="cb19-11"><a href="#cb19-11"></a>df[predictors_gwr] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(df[predictors_gwr], safe_scale)</span>
<span id="cb19-12"><a href="#cb19-12"></a>df <span class="ot">&lt;-</span> df[<span class="fu">complete.cases</span>(df), ]</span>
<span id="cb19-13"><a href="#cb19-13"></a></span>
<span id="cb19-14"><a href="#cb19-14"></a><span class="co"># Subset spatial data to match df</span></span>
<span id="cb19-15"><a href="#cb19-15"></a>HDB_geo_gwr <span class="ot">&lt;-</span> HDB_geo <span class="sc">%&gt;%</span> <span class="fu">slice</span>(<span class="fu">as.numeric</span>(<span class="fu">rownames</span>(df)))</span>
<span id="cb19-16"><a href="#cb19-16"></a>HDB_sp <span class="ot">&lt;-</span> <span class="fu">as</span>(HDB_geo_gwr, <span class="st">"Spatial"</span>)</span>
<span id="cb19-17"><a href="#cb19-17"></a></span>
<span id="cb19-18"><a href="#cb19-18"></a><span class="co"># GWR formula</span></span>
<span id="cb19-19"><a href="#cb19-19"></a>gwr_formula <span class="ot">&lt;-</span> <span class="fu">as.formula</span>(<span class="fu">paste</span>(<span class="st">"resale_price ~"</span>, <span class="fu">paste</span>(predictors_gwr, <span class="at">collapse =</span> <span class="st">" + "</span>)))</span>
<span id="cb19-20"><a href="#cb19-20"></a></span>
<span id="cb19-21"><a href="#cb19-21"></a><span class="co"># Bandwidth selection</span></span>
<span id="cb19-22"><a href="#cb19-22"></a>bw <span class="ot">&lt;-</span> <span class="fu">bw.gwr</span>(gwr_formula, <span class="at">data =</span> HDB_sp, <span class="at">approach =</span> <span class="st">"AICc"</span>, <span class="at">kernel =</span> <span class="st">"bisquare"</span>, <span class="at">adaptive =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Adaptive bandwidth (number of nearest neighbours): 207 AICc value: 7853.743 
Adaptive bandwidth (number of nearest neighbours): 136 AICc value: 7867.688 
Adaptive bandwidth (number of nearest neighbours): 252 AICc value: 7852.888 
Adaptive bandwidth (number of nearest neighbours): 279 AICc value: 7854.815 
Adaptive bandwidth (number of nearest neighbours): 234 AICc value: 7852.571 
Adaptive bandwidth (number of nearest neighbours): 224 AICc value: 7853.111 
Adaptive bandwidth (number of nearest neighbours): 241 AICc value: 7852.816 
Adaptive bandwidth (number of nearest neighbours): 230 AICc value: 7852.902 
Adaptive bandwidth (number of nearest neighbours): 236 AICc value: 7852.702 
Adaptive bandwidth (number of nearest neighbours): 232 AICc value: 7852.733 
Adaptive bandwidth (number of nearest neighbours): 234 AICc value: 7852.571 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a><span class="co"># Fitting GWR</span></span>
<span id="cb21-2"><a href="#cb21-2"></a>gwr_fit <span class="ot">&lt;-</span> <span class="fu">gwr.basic</span>(gwr_formula, <span class="at">data =</span> HDB_sp, <span class="at">bw =</span> bw, <span class="at">kernel =</span> <span class="st">"bisquare"</span>, <span class="at">adaptive =</span> <span class="cn">TRUE</span>)</span>
<span id="cb21-3"><a href="#cb21-3"></a></span>
<span id="cb21-4"><a href="#cb21-4"></a><span class="co"># Converting results back to sf</span></span>
<span id="cb21-5"><a href="#cb21-5"></a>gwr_sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(gwr_fit<span class="sc">$</span>SDF)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><strong>Interpretation:</strong> This chunk fits a Geographically Weighted Regression (GWR) model to the data, allowing the predictor coefficients to vary geographically.</li>
<li><strong>Bandwidth Selection:</strong> The optimal adaptive bandwidth (the number of nearest neighbors for local estimation) is determined using the AICc criterion. The final selected optimal bandwidth is 234 nearest neighbors , which resulted in the lowest AICc value of 7852.571.</li>
<li><strong>Analysis Relevance:</strong> The GWR model is correctly implemented to address the spatial non-stationarity identified by the OLS residuals. The AICc value (7852.571) for the GWR is lower than the (non-reported) OLS AICc, and the R-squared for GWR will typically be higher, indicating better local model fit.</li>
</ul>
</section>
<section id="comparing-ols-vs-gwr-coefficients-floor-area" class="level1">
<h1>14. Comparing OLS vs GWR Coefficients (Floor Area)</h1>
<p>Compare global OLS coefficient for floor_area_sqm against GWR coefficients.Highlights spatial variation in the effect of floor area on resale price.Visualizes the distribution of local coefficients to explore heterogeneity.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a><span class="co"># Analysis: Comparing Coefficients</span></span>
<span id="cb22-2"><a href="#cb22-2"></a>coef_comparison <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb22-3"><a href="#cb22-3"></a>  <span class="at">OLS_floor_area =</span> <span class="fu">coef</span>(model_glm)[<span class="st">"floor_area_sqm"</span>],</span>
<span id="cb22-4"><a href="#cb22-4"></a>  <span class="at">GWR_floor_area_mean =</span> <span class="fu">mean</span>(gwr_sf<span class="sc">$</span>floor_area_sqm, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb22-5"><a href="#cb22-5"></a>  <span class="at">GWR_floor_area_sd   =</span> <span class="fu">sd</span>(gwr_sf<span class="sc">$</span>floor_area_sqm, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb22-6"><a href="#cb22-6"></a>)</span>
<span id="cb22-7"><a href="#cb22-7"></a>coef_comparison</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               OLS_floor_area GWR_floor_area_mean GWR_floor_area_sd
floor_area_sqm        2581.52            4002.054          1401.511</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a><span class="fu">ggplot</span>(gwr_sf, <span class="fu">aes</span>(<span class="at">x =</span> floor_area_sqm)) <span class="sc">+</span></span>
<span id="cb24-2"><a href="#cb24-2"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">50</span>, <span class="at">fill =</span> <span class="st">"lightgreen"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of GWR Coefficients: Floor Area"</span>, </span>
<span id="cb24-4"><a href="#cb24-4"></a>       <span class="at">x =</span> <span class="st">"Coefficient"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_Home_Ex3_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><strong>Interpretation:</strong> This chunk compares the coefficient for the floor_area_sqm variable between the global OLS model and the local GWR model.</li>
<li><strong>OLS Coefficient:</strong> The OLS coefficient is a single value: 2,581.5269. This suggests that globally, a 1 sqm increase in floor area is associated with a 2,581.52 SGD increase in resale price 70.</li>
<li><strong>GWR Coefficients:</strong> In contrast, the GWR coefficients are a distribution of values: Mean: 4,002.05471. Standard Deviation (SD): 1,401.51172.</li>
<li><strong>Distribution Plot:</strong> The histogram of GWR coefficients shows the coefficients are not a single value but vary widely, roughly ranging from 1,500 to over 6,000.</li>
<li><strong>Analysis Relevance:</strong> The large difference between the OLS coefficient (<span class="math inline">\(\approx 2,582\)</span>) and the mean GWR coefficient (<span class="math inline">\(\approx 4,002\)</span>), coupled with the high standard deviation (1,401.5) in the GWR coefficients and the multi-modal histogram distribution, provides quantitative evidence of spatial non-stationarity . This confirms that the relationship between floor area and price is not constant across Singapore but depends heavily on the location.</li>
</ul>
</section>
<section id="visualisation" class="level1">
<h1>15. Visualisation</h1>
<p>Generate static maps for HDB resale prices, nearby POIs, and buffers (350m, 1km).Supports exploratory spatial analysis and interpretation of locational influence on prices.Combines point, polygon, and buffer layers for clear spatial context.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1"></a><span class="fu">library</span>(tmap)</span>
<span id="cb25-2"><a href="#cb25-2"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)  <span class="co"># static maps</span></span>
<span id="cb25-3"><a href="#cb25-3"></a></span>
<span id="cb25-4"><a href="#cb25-4"></a><span class="co"># HDB Resale Prices</span></span>
<span id="cb25-5"><a href="#cb25-5"></a><span class="fu">tm_shape</span>(sg_boundary) <span class="sc">+</span></span>
<span id="cb25-6"><a href="#cb25-6"></a>  <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"white"</span>, <span class="at">border.col =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb25-7"><a href="#cb25-7"></a><span class="fu">tm_shape</span>(HDB_geo) <span class="sc">+</span></span>
<span id="cb25-8"><a href="#cb25-8"></a>  <span class="fu">tm_dots</span>(<span class="at">col =</span> <span class="st">"resale_price"</span>,</span>
<span id="cb25-9"><a href="#cb25-9"></a>          <span class="at">palette =</span> <span class="st">"YlOrRd"</span>,</span>
<span id="cb25-10"><a href="#cb25-10"></a>          <span class="at">size =</span> <span class="fl">0.4</span>,</span>
<span id="cb25-11"><a href="#cb25-11"></a>          <span class="at">border.col =</span> <span class="st">"black"</span>,</span>
<span id="cb25-12"><a href="#cb25-12"></a>          <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb25-13"><a href="#cb25-13"></a><span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"HDB Resale Prices"</span>, <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_Home_Ex3_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="co"># Hawker Centres</span></span>
<span id="cb26-2"><a href="#cb26-2"></a><span class="fu">tm_shape</span>(sg_boundary) <span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3"></a>  <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"white"</span>, <span class="at">border.col =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4"></a><span class="fu">tm_shape</span>(hawker) <span class="sc">+</span></span>
<span id="cb26-5"><a href="#cb26-5"></a>  <span class="fu">tm_symbols</span>(<span class="at">col =</span> <span class="st">"red"</span>, <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">size =</span> <span class="fl">0.3</span>, <span class="at">border.col =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb26-6"><a href="#cb26-6"></a><span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Hawker Centres"</span>, <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_Home_Ex3_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1"></a><span class="co"># Supermarkets</span></span>
<span id="cb27-2"><a href="#cb27-2"></a><span class="fu">tm_shape</span>(sg_boundary) <span class="sc">+</span></span>
<span id="cb27-3"><a href="#cb27-3"></a>  <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"white"</span>, <span class="at">border.col =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4"></a><span class="fu">tm_shape</span>(supermarkets) <span class="sc">+</span></span>
<span id="cb27-5"><a href="#cb27-5"></a>  <span class="fu">tm_symbols</span>(<span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">shape =</span> <span class="dv">22</span>, <span class="at">size =</span> <span class="fl">0.3</span>, <span class="at">border.col =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb27-6"><a href="#cb27-6"></a><span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Supermarkets"</span>, <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_Home_Ex3_files/figure-html/unnamed-chunk-14-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a><span class="co"># CHAS Clinics</span></span>
<span id="cb28-2"><a href="#cb28-2"></a><span class="fu">tm_shape</span>(sg_boundary) <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3"></a>  <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"white"</span>, <span class="at">border.col =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb28-4"><a href="#cb28-4"></a><span class="fu">tm_shape</span>(chas) <span class="sc">+</span></span>
<span id="cb28-5"><a href="#cb28-5"></a>  <span class="fu">tm_symbols</span>(<span class="at">col =</span> <span class="st">"green"</span>, <span class="at">shape =</span> <span class="dv">23</span>, <span class="at">size =</span> <span class="fl">0.3</span>, <span class="at">border.col =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb28-6"><a href="#cb28-6"></a><span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"CHAS Clinics"</span>, <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_Home_Ex3_files/figure-html/unnamed-chunk-14-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a><span class="co"># Eldercare Centres</span></span>
<span id="cb29-2"><a href="#cb29-2"></a><span class="fu">tm_shape</span>(sg_boundary) <span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3"></a>  <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"white"</span>, <span class="at">border.col =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb29-4"><a href="#cb29-4"></a><span class="fu">tm_shape</span>(eldercare) <span class="sc">+</span></span>
<span id="cb29-5"><a href="#cb29-5"></a>  <span class="fu">tm_symbols</span>(<span class="at">col =</span> <span class="st">"purple"</span>, <span class="at">shape =</span> <span class="dv">24</span>, <span class="at">size =</span> <span class="fl">0.3</span>, <span class="at">border.col =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb29-6"><a href="#cb29-6"></a><span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Eldercare Centres"</span>, <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_Home_Ex3_files/figure-html/unnamed-chunk-14-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a><span class="co"># Childcare Centres</span></span>
<span id="cb30-2"><a href="#cb30-2"></a><span class="fu">tm_shape</span>(sg_boundary) <span class="sc">+</span></span>
<span id="cb30-3"><a href="#cb30-3"></a>  <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"white"</span>, <span class="at">border.col =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb30-4"><a href="#cb30-4"></a><span class="fu">tm_shape</span>(childcare) <span class="sc">+</span></span>
<span id="cb30-5"><a href="#cb30-5"></a>  <span class="fu">tm_symbols</span>(<span class="at">col =</span> <span class="st">"orange"</span>, <span class="at">shape =</span> <span class="dv">25</span>, <span class="at">size =</span> <span class="fl">0.3</span>, <span class="at">border.col =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb30-6"><a href="#cb30-6"></a><span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Childcare Centres"</span>, <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_Home_Ex3_files/figure-html/unnamed-chunk-14-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a><span class="co"># Parks</span></span>
<span id="cb31-2"><a href="#cb31-2"></a><span class="fu">tm_shape</span>(sg_boundary) <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3"></a>  <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"white"</span>, <span class="at">border.col =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4"></a><span class="fu">tm_shape</span>(parks) <span class="sc">+</span></span>
<span id="cb31-5"><a href="#cb31-5"></a>  <span class="fu">tm_symbols</span>(<span class="at">col =</span> <span class="st">"darkgreen"</span>, <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">size =</span> <span class="fl">0.4</span>, <span class="at">border.col =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb31-6"><a href="#cb31-6"></a><span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Parks"</span>, <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_Home_Ex3_files/figure-html/unnamed-chunk-14-7.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1"></a><span class="co"># Kindergartens</span></span>
<span id="cb32-2"><a href="#cb32-2"></a><span class="fu">tm_shape</span>(sg_boundary) <span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3"></a>  <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"white"</span>, <span class="at">border.col =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb32-4"><a href="#cb32-4"></a><span class="fu">tm_shape</span>(kinderg) <span class="sc">+</span></span>
<span id="cb32-5"><a href="#cb32-5"></a>  <span class="fu">tm_symbols</span>(<span class="at">col =</span> <span class="st">"pink"</span>, <span class="at">shape =</span> <span class="dv">22</span>, <span class="at">size =</span> <span class="fl">0.3</span>, <span class="at">border.col =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb32-6"><a href="#cb32-6"></a><span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Kindergartens"</span>, <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_Home_Ex3_files/figure-html/unnamed-chunk-14-8.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>HDB Resale Prices:-</strong></p>
<ul>
<li><strong>Visual Pattern:</strong> The map shows a clear spatial pattern: higher resale prices (red/darker colors) are overwhelmingly concentrated in the Central, Southern, and Eastern parts of Singapore (especially around the city fringe). Lower resale prices (yellow/lighter colors) tend to be distributed in the Northern and Western parts (e.g., Woodlands, Choa Chu Kang, Jurong East).</li>
<li><strong>Analytical Implication:</strong> This strong clustering of prices demonstrates spatial dependence (or spatial autocorrelation). The value of an HDB flat is clearly influenced by the values of its neighbors, confirming that a global model (OLS) is likely inadequate and justifying the use of a local model like GWR.</li>
</ul>
<p><strong>Hawker Centres:-</strong></p>
<ul>
<li><strong>Visual Pattern:</strong> Hawker Centres are distributed across the island but show a higher density and clustering in the older, central residential areas. There are noticeable gaps in some newer or less developed parts of the West and Northeast.</li>
<li><strong>Analytical Implication:</strong> Proximity to a Hawker Centre is generally a desirable amenity. The higher concentration in the central areas, which also have higher resale prices, suggests that the negative effect of distance (<span class="math inline">\(\beta_{\text{dist\_hawker\_km}}\)</span>) on price might be stronger in these dense, central locations.</li>
</ul>
<p><strong>SuperMarkets:-</strong></p>
<ul>
<li><strong>Visual Pattern:</strong> Supermarkets show the most dispersed and even distribution of all POIs, covering most residential areas relatively uniformly.</li>
<li><strong>Analytical Implication:</strong> The uniform distribution implies that most HDB flats are close to a supermarket. This ubiquity likely contributes to the OLS model’s finding that distance to a supermarket is not a significant global predictor, as it is a common convenience everywhere.</li>
</ul>
<p><strong>CHAS Clinic:-</strong></p>
<ul>
<li><strong>Visual Pattern:</strong> CHAS Clinics exhibit a high density, particularly in the Southern and Central planning areas and along major transportation corridors. Similar to supermarkets, coverage is generally good, but with higher concentration in the more populated, established towns.</li>
<li><strong>Analytical Implication:</strong> The relative closeness to clinics (mean distance 0.722 km ) suggests they are a baseline amenity. Their generally clustered distribution might interact with the spatial pattern of prices, meaning the benefit of proximity could vary across locations.</li>
</ul>
<p><strong>Eldercare Centres:-</strong></p>
<ul>
<li><strong>Visual Pattern:</strong> Eldercare Centres have a sparse distribution compared to other amenities, with distinct clusters in a few major HDB towns, and many areas, particularly in the West and extreme North, having low coverage.</li>
<li><strong>Analytical Implication:</strong> The large mean distance (1.619 km ) and clustered distribution suggest that proximity to eldercare is a rare amenity, likely affecting property values only in the immediate vicinity of the centres, which GWR is better suited to capture locally than OLS.</li>
</ul>
<p><strong>Childcare Centres:-</strong></p>
<ul>
<li><strong>Visual Pattern:</strong> Childcare Centres show an extremely high density and widespread distribution across virtually all residential areas. This is indicative of a successful national coverage strategy for this essential service.</li>
<li><strong>Analytical Implication:</strong> Despite the even coverage, the OLS model found that the distance to childcare was a significant, positive predictor (<span class="math inline">\(\beta = 25575.3\)</span> per km). This counterintuitive positive sign (prices increase as the distance increases) suggests a potential collinearity or spatial confounding issue. The GWR model is necessary to check if this anomalous positive effect is localized or if it’s a global error caused by the correlation of this variable with an unobserved central location factor.</li>
</ul>
<p><strong>Parks:-</strong></p>
<ul>
<li><strong>Visual Pattern:</strong> Parks are well-distributed but show some clustering in the Central and Eastern parts . Unlike supermarkets, there are clearer gaps in coverage, suggesting that proximity to a park is not universal.</li>
<li><strong>Analytical Implication:</strong> Proximity to green spaces is a highly valued amenity. The non-uniform distribution suggests that the premium placed on being near a park may vary significantly. For instance, the value of proximity might be higher in dense central areas compared to green areas in the West.</li>
</ul>
<p><strong>Kindergartens:-</strong></p>
<ul>
<li><strong>Visual Pattern:</strong> Kindergartens are widely dispersed, with a distribution pattern that is denser than parks but less dense than childcare centers. They cover most major towns.</li>
<li><strong>Analytical Implication:</strong> Proximity to kindergartens was found to be marginally significant with a negative effect (<span class="math inline">\(\beta = -18608.0\)</span> per km) in the OLS model. Similar to the childcare finding, the GWR model must be used to examine if this relationship varies across Singapore, potentially revealing local areas where this amenity is highly valued (negative coefficient) versus areas where it is less relevant (positive or zero coefficient).</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a><span class="co"># Buffers</span></span>
<span id="cb33-2"><a href="#cb33-2"></a>HDB_buffer_350 <span class="ot">&lt;-</span> <span class="fu">st_buffer</span>(HDB_geo, <span class="at">dist =</span> <span class="dv">350</span>)</span>
<span id="cb33-3"><a href="#cb33-3"></a>HDB_buffer_1000 <span class="ot">&lt;-</span> <span class="fu">st_buffer</span>(HDB_geo, <span class="at">dist =</span> <span class="dv">1000</span>)</span>
<span id="cb33-4"><a href="#cb33-4"></a></span>
<span id="cb33-5"><a href="#cb33-5"></a><span class="fu">tm_shape</span>(sg_boundary) <span class="sc">+</span></span>
<span id="cb33-6"><a href="#cb33-6"></a>  <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"white"</span>, <span class="at">border.col =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb33-7"><a href="#cb33-7"></a></span>
<span id="cb33-8"><a href="#cb33-8"></a>  <span class="co"># HDB points</span></span>
<span id="cb33-9"><a href="#cb33-9"></a>  <span class="fu">tm_shape</span>(HDB_geo) <span class="sc">+</span></span>
<span id="cb33-10"><a href="#cb33-10"></a>  <span class="fu">tm_dots</span>(<span class="at">col =</span> <span class="st">"resale_price"</span>, <span class="at">palette =</span> <span class="st">"YlOrRd"</span>, <span class="at">size =</span> <span class="fl">0.4</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">border.col =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb33-11"><a href="#cb33-11"></a></span>
<span id="cb33-12"><a href="#cb33-12"></a>  <span class="co"># 350m buffer</span></span>
<span id="cb33-13"><a href="#cb33-13"></a>  <span class="fu">tm_shape</span>(HDB_buffer_350) <span class="sc">+</span></span>
<span id="cb33-14"><a href="#cb33-14"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"grey70"</span>, <span class="at">lty =</span> <span class="st">"dashed"</span>, <span class="at">lwd =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb33-15"><a href="#cb33-15"></a></span>
<span id="cb33-16"><a href="#cb33-16"></a>  <span class="co"># 1km buffer</span></span>
<span id="cb33-17"><a href="#cb33-17"></a>  <span class="fu">tm_shape</span>(HDB_buffer_1000) <span class="sc">+</span></span>
<span id="cb33-18"><a href="#cb33-18"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"grey50"</span>, <span class="at">lty =</span> <span class="st">"dotted"</span>, <span class="at">lwd =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb33-19"><a href="#cb33-19"></a></span>
<span id="cb33-20"><a href="#cb33-20"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"HDB Resale Prices with 350m &amp; 1km Buffers"</span>,</span>
<span id="cb33-21"><a href="#cb33-21"></a>            <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_Home_Ex3_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>HDB Resale Prices with 350m &amp; 1km Buffers:-</strong></p>
<ul>
<li><strong>Visual Pattern:</strong> This map overlays the resale price points with two geographic buffers (350m and 1km) around each point .</li>
<li><strong>Analytical Implication:</strong> This visualization is purely methodological. It visually illustrates the concept of a local neighborhood scale that is fundamental to Geographically Weighted models (like the GWR, which uses an adaptive bandwidth of 234 neighbors) and spatial statistics. It provides context for how the st_distance and count_within_vec functions operate on a local spatial scale.</li>
</ul>
</section>
<section id="conclusion" class="level1">
<h1>16. Conclusion</h1>
<p>This analysis successfully integrates structural and locational factors to model 4-room HDB resale prices in Singapore. The combination of global (OLS) and local (GWR) modeling approaches highlights both overall trends and spatial heterogeneity in price determinants. Visualizations provide clear insight into price distribution, the influence of amenities, and residual patterns, demonstrating the value of geospatial methods in housing price analysis.</p>
</section>
<section id="future-work" class="level1">
<h1>17. Future Work</h1>
<ul>
<li>Extend modeling to 3-room and 5-room flats for a comprehensive HDB price analysis.</li>
<li>Incorporate temporal dynamics to model price trends over multiple quarters.</li>
<li>Explore additional locational variables such as MRT travel time or school quality scores.</li>
<li>Implement predictive validation using cross-validation or holdout sets to assess model robustness.</li>
<li>Automate reproducible workflow with RMarkdown for full reporting and mapping outputs.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>