<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sathvika Subramanian">
<meta name="dcterms.date" content="2025-10-17">

<title>Take Home Exercise 2 – ISSS626</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">ISSS626</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex1-1.html">
 <span class="dropdown-text">Hands-on Exercise 1-1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex1-2.html">
 <span class="dropdown-text">Hands-on Exercise 1-2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex2-1&amp;2-2.html">
 <span class="dropdown-text">Hands-on Exercise 2-1 &amp; 2-2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex3.html">
 <span class="dropdown-text">Hands-on Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex4.html">
 <span class="dropdown-text">Hands-on Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex5-1.html">
 <span class="dropdown-text">Hands-on Exercise 5-1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex5-2.html">
 <span class="dropdown-text">Hands-on Exercise 5-2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex6.html">
 <span class="dropdown-text">Hands-on Exercise 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex7.html">
 <span class="dropdown-text">Hands-on Exercise 7</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-class Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="../../Inclass_Ex/In_class_Ex3/In-class_Ex03a.html">
 <span class="dropdown-text">In-class Exercise 3a</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Inclass_Ex/In_class_Ex3/In-class_Ex03b.html">
 <span class="dropdown-text">In-class Exercise 3b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Inclass_Ex/In_class_Ex4/In-class_Ex04.html">
 <span class="dropdown-text">In-class Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Inclass_Ex/In_class_Ex5/In-class_Ex05.html">
 <span class="dropdown-text">In-class Exercise 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Inclass_Ex/In_class_Ex6/In-class_Ex06.html">
 <span class="dropdown-text">In-class Exercise 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Inclass_Ex/In_class_Ex7/In-class_Ex07.html">
 <span class="dropdown-text">In-class Exercise 7</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take Home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../Take_Home_Ex/Take_Home_Ex1/Take_Home_Ex1.html">
 <span class="dropdown-text">Take Home Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take_Home_Ex/Take_Home_Ex2/Take_Home_Ex2.html">
 <span class="dropdown-text">Take Home Exercise 2</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#urban-mobility-analysis-spatio-temporal-patterns-in-bus-trip-origins" id="toc-urban-mobility-analysis-spatio-temporal-patterns-in-bus-trip-origins" class="nav-link active" data-scroll-target="#urban-mobility-analysis-spatio-temporal-patterns-in-bus-trip-origins">Urban Mobility Analysis: Spatio-Temporal Patterns in Bus Trip Origins</a>
  <ul class="collapse">
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">1. Overview</a></li>
  <li><a href="#objective" id="toc-objective" class="nav-link" data-scroll-target="#objective">2. Objective</a></li>
  <li><a href="#dataset" id="toc-dataset" class="nav-link" data-scroll-target="#dataset">3. DataSet</a></li>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link" data-scroll-target="#getting-started">4. Getting Started</a>
  <ul class="collapse">
  <li><a href="#load-r-packages" id="toc-load-r-packages" class="nav-link" data-scroll-target="#load-r-packages">4.1 Load R packages</a></li>
  </ul></li>
  <li><a href="#importing-data" id="toc-importing-data" class="nav-link" data-scroll-target="#importing-data">5. Importing Data</a>
  <ul class="collapse">
  <li><a href="#bus-stop-location" id="toc-bus-stop-location" class="nav-link" data-scroll-target="#bus-stop-location">5.1 Bus Stop Location</a></li>
  <li><a href="#master-plan-2019-subzone" id="toc-master-plan-2019-subzone" class="nav-link" data-scroll-target="#master-plan-2019-subzone">5.2 Master Plan 2019 Subzone</a></li>
  <li><a href="#extract-attributes-from-kml" id="toc-extract-attributes-from-kml" class="nav-link" data-scroll-target="#extract-attributes-from-kml">5.3 Extract attributes from KML</a></li>
  <li><a href="#o-d-bus-data" id="toc-o-d-bus-data" class="nav-link" data-scroll-target="#o-d-bus-data">5.4 O-D Bus Data</a></li>
  </ul></li>
  <li><a href="#data-wrangling-geospatial-data-science" id="toc-data-wrangling-geospatial-data-science" class="nav-link" data-scroll-target="#data-wrangling-geospatial-data-science">6. Data Wrangling (Geospatial Data Science)</a>
  <ul class="collapse">
  <li><a href="#preprocess-bus-stops" id="toc-preprocess-bus-stops" class="nav-link" data-scroll-target="#preprocess-bus-stops">6.1 Preprocess Bus Stops</a></li>
  <li><a href="#derive-analytical-hexagon-grid" id="toc-derive-analytical-hexagon-grid" class="nav-link" data-scroll-target="#derive-analytical-hexagon-grid">6.2 Derive Analytical Hexagon Grid</a></li>
  <li><a href="#classify-time-intervals" id="toc-classify-time-intervals" class="nav-link" data-scroll-target="#classify-time-intervals">6.3 Classify Time Intervals</a></li>
  <li><a href="#aggregate-passenger-trips" id="toc-aggregate-passenger-trips" class="nav-link" data-scroll-target="#aggregate-passenger-trips">6.4 Aggregate Passenger Trips</a></li>
  <li><a href="#spatial-join-bus-stops-to-hex-grid" id="toc-spatial-join-bus-stops-to-hex-grid" class="nav-link" data-scroll-target="#spatial-join-bus-stops-to-hex-grid">6.5 Spatial join bus stops to hex grid</a></li>
  <li><a href="#aggregate-trips-to-hexagon-level" id="toc-aggregate-trips-to-hexagon-level" class="nav-link" data-scroll-target="#aggregate-trips-to-hexagon-level">6.6 Aggregate trips to hexagon level</a></li>
  </ul></li>
  <li><a href="#eda-exploratory-data-analysis---visualisation" id="toc-eda-exploratory-data-analysis---visualisation" class="nav-link" data-scroll-target="#eda-exploratory-data-analysis---visualisation">7. EDA (Exploratory Data Analysis - Visualisation)</a>
  <ul class="collapse">
  <li><a href="#visualise-trip-distribution" id="toc-visualise-trip-distribution" class="nav-link" data-scroll-target="#visualise-trip-distribution">7.1 Visualise Trip Distribution</a></li>
  </ul></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis">8. Analysis</a>
  <ul class="collapse">
  <li><a href="#lmsa-spatial-weights" id="toc-lmsa-spatial-weights" class="nav-link" data-scroll-target="#lmsa-spatial-weights">8.1 LMSA: Spatial Weights</a></li>
  <li><a href="#lmsa-local-gi-calculation" id="toc-lmsa-local-gi-calculation" class="nav-link" data-scroll-target="#lmsa-local-gi-calculation">8.2 LMSA: Local Gi* Calculation</a></li>
  <li><a href="#visualise-lmsa" id="toc-visualise-lmsa" class="nav-link" data-scroll-target="#visualise-lmsa">8.3 Visualise LMSA</a></li>
  <li><a href="#ehsa-prepare-gi-matrix" id="toc-ehsa-prepare-gi-matrix" class="nav-link" data-scroll-target="#ehsa-prepare-gi-matrix">8.4 EHSA: Prepare Gi* Matrix</a></li>
  <li><a href="#ehsa-categorization" id="toc-ehsa-categorization" class="nav-link" data-scroll-target="#ehsa-categorization">8.5 EHSA Categorization</a></li>
  <li><a href="#ehsa-demo-cluster-generation-with-auto-geometry-check" id="toc-ehsa-demo-cluster-generation-with-auto-geometry-check" class="nav-link" data-scroll-target="#ehsa-demo-cluster-generation-with-auto-geometry-check">8.6 EHSA Demo Cluster Generation with Auto Geometry Check</a></li>
  <li><a href="#save-outputs" id="toc-save-outputs" class="nav-link" data-scroll-target="#save-outputs">8.7 Save Outputs</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">9. Conclusion</a></li>
  <li><a href="#future-work" id="toc-future-work" class="nav-link" data-scroll-target="#future-work">10. Future Work</a></li>
  </ul></li>
  </ul>
<div class="quarto-code-links"><h2>Code Links</h2><ul><li><a href="https://github.com/Sathvika-7284/ISSS626-geo"><i class="bi bi-file-code"></i>GitHub Repo</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take Home Exercise 2</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sathvika Subramanian </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 17, 2025</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">October 23, 2025</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="urban-mobility-analysis-spatio-temporal-patterns-in-bus-trip-origins" class="level1">
<h1>Urban Mobility Analysis: Spatio-Temporal Patterns in Bus Trip Origins</h1>
<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">1. Overview</h2>
<p>This study explores urban mobility patterns in Singapore using passenger tap-on data from public buses. We apply advanced geospatial statistics—Local Measures of Spatial Autocorrelation (LMSA) and Emerging Hot Spot Analysis (EHSA)—to move beyond simple mapping and quantify where passenger trips originate, how these origins cluster spatially, and how these spatial patterns evolve across three distinct peak time intervals. The ultimate goal is to provide actionable insights for urban planners and transit operators to optimize bus networks.</p>
</section>
<section id="objective" class="level2">
<h2 class="anchored" data-anchor-id="objective">2. Objective</h2>
<p>The primary objective is to discover and analyze statistically significant hotspots (clusters of high trip generation) and coldspots (clusters of low trip generation) at the neighborhood level, distinguishing these patterns across Weekday AM Peak, Weekday PM Peak, and Weekend Peak periods. Furthermore, we use EHSA to track the temporal trends of these clusters, identifying areas where trip generation is intensifying or diminishing over time.</p>
</section>
<section id="dataset" class="level2">
<h2 class="anchored" data-anchor-id="dataset">3. DataSet</h2>
<p>The analysis relies on three key datasets, all processed and harmonized to the SVY21 projected coordinate system (EPSG:3414) for accurate metric-based spatial operations:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Data Source</th>
<th>Type</th>
<th>Purpose</th>
<th>Key Identifier</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>O-D Bus Data</td>
<td>Aspatial (.csv)</td>
<td>Passenger tap-on counts (trip origin/time).</td>
<td>ORIGIN_PT_CODE, TIME_PER_HOUR</td>
</tr>
<tr class="even">
<td>Bus Stop Location</td>
<td>Geospatial (Point)</td>
<td>Geographic coordinates of trip origins.</td>
<td>BUS_STOP_N</td>
</tr>
<tr class="odd">
<td>Master Plan 2019 Subzone Boundary</td>
<td>Geospatial (Polygon)</td>
<td>Defining the study area boundary.</td>
<td>Subzone attributes (extracted)</td>
</tr>
</tbody>
</table>
</section>
<section id="getting-started" class="level2">
<h2 class="anchored" data-anchor-id="getting-started">4. Getting Started</h2>
<section id="load-r-packages" class="level3">
<h3 class="anchored" data-anchor-id="load-r-packages">4.1 Load R packages</h3>
<p>We load the necessary R libraries for spatial data handling (sf), spatial statistics (spdep, sfdep, trend), and professional cartography (tmap). This ensures a complete and efficient analytical environment.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, sfdep, tmap, tmaptools, spdep, tidyverse, lubridate, trend, rvest, knitr, classInt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="importing-data" class="level2">
<h2 class="anchored" data-anchor-id="importing-data">5. Importing Data</h2>
<p>We import the geographic boundary and bus stop layers, transforming all spatial data to SVY21 (EPSG:3414), which is crucial for distance-based calculations required in the subsequent spatial analysis.</p>
<section id="bus-stop-location" class="level3">
<h3 class="anchored" data-anchor-id="bus-stop-location">5.1 Bus Stop Location</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a>BusStop <span class="ot">=</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geospatial/LTADataMall/"</span>,</span>
<span id="cb2-2"><a href="#cb2-2"></a>                  <span class="at">layer =</span> <span class="st">"BusStop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-3"><a href="#cb2-3"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `BusStop' from data source 
  `C:\Sathvika-7284\ISSS626-geo\Take_Home_Ex\Take_Home_Ex2\data\geospatial\LTADataMall' 
  using driver `ESRI Shapefile'
Simple feature collection with 5172 features and 2 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 3970.122 ymin: 26482.1 xmax: 48285.52 ymax: 52983.82
Projected CRS: SVY21</code></pre>
</div>
</div>
</section>
<section id="master-plan-2019-subzone" class="level3">
<h3 class="anchored" data-anchor-id="master-plan-2019-subzone">5.2 Master Plan 2019 Subzone</h3>
<p>Transform to SVY21 (EPSG:3414), Singapore’s national projected coordinate system. It preserves distance and area accuracy for local-scale spatial analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a>mpsz <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"data/geospatial/MasterPlan2019SubzoneBoundaryNoSeaKML.kml"</span>) <span class="sc">%&gt;%</span> <span class="fu">st_transform</span>(<span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `URA_MP19_SUBZONE_NO_SEA_PL' from data source 
  `C:\Sathvika-7284\ISSS626-geo\Take_Home_Ex\Take_Home_Ex2\data\geospatial\MasterPlan2019SubzoneBoundaryNoSeaKML.kml' 
  using driver `KML'
Simple feature collection with 332 features and 2 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 103.6057 ymin: 1.158699 xmax: 104.0885 ymax: 1.470775
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
</section>
<section id="extract-attributes-from-kml" class="level3">
<h3 class="anchored" data-anchor-id="extract-attributes-from-kml">5.3 Extract attributes from KML</h3>
<p>This code segment defines a function to parse the HTML description fields commonly found in KML data and extracts key administrative attributes. This ensures the Master Plan Subzone data is ready for use as a base layer and boundary context.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>extract_kml_field <span class="ot">&lt;-</span> <span class="cf">function</span>(html_text, field_name) {</span>
<span id="cb6-2"><a href="#cb6-2"></a>  <span class="cf">if</span> (<span class="fu">is.na</span>(html_text) <span class="sc">||</span> html_text <span class="sc">==</span> <span class="st">""</span>) <span class="fu">return</span>(<span class="cn">NA_character_</span>)</span>
<span id="cb6-3"><a href="#cb6-3"></a>  </span>
<span id="cb6-4"><a href="#cb6-4"></a>  page <span class="ot">&lt;-</span> <span class="fu">read_html</span>(html_text)</span>
<span id="cb6-5"><a href="#cb6-5"></a>  rows <span class="ot">&lt;-</span> page <span class="sc">%&gt;%</span> <span class="fu">html_elements</span>(<span class="st">"tr"</span>)</span>
<span id="cb6-6"><a href="#cb6-6"></a>  </span>
<span id="cb6-7"><a href="#cb6-7"></a>  value <span class="ot">&lt;-</span> rows <span class="sc">%&gt;%</span></span>
<span id="cb6-8"><a href="#cb6-8"></a>    <span class="fu">keep</span>(<span class="sc">~</span> <span class="fu">html_text2</span>(<span class="fu">html_element</span>(.x, <span class="st">"th"</span>)) <span class="sc">==</span> field_name) <span class="sc">%&gt;%</span></span>
<span id="cb6-9"><a href="#cb6-9"></a>    <span class="fu">html_element</span>(<span class="st">"td"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb6-10"><a href="#cb6-10"></a>    <span class="fu">html_text2</span>()</span>
<span id="cb6-11"><a href="#cb6-11"></a>  </span>
<span id="cb6-12"><a href="#cb6-12"></a>  <span class="cf">if</span>(<span class="fu">length</span>(value) <span class="sc">==</span> <span class="dv">0</span>) <span class="cn">NA_character_</span> <span class="cf">else</span> value</span>
<span id="cb6-13"><a href="#cb6-13"></a>}</span>
<span id="cb6-14"><a href="#cb6-14"></a></span>
<span id="cb6-15"><a href="#cb6-15"></a>mpsz <span class="ot">&lt;-</span> mpsz <span class="sc">%&gt;%</span></span>
<span id="cb6-16"><a href="#cb6-16"></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-17"><a href="#cb6-17"></a>    <span class="at">REGION_N =</span> <span class="fu">map_chr</span>(Description, extract_kml_field, <span class="st">"REGION_N"</span>),</span>
<span id="cb6-18"><a href="#cb6-18"></a>    <span class="at">PLN_AREA_N =</span> <span class="fu">map_chr</span>(Description, extract_kml_field, <span class="st">"PLN_AREA_N"</span>),</span>
<span id="cb6-19"><a href="#cb6-19"></a>    <span class="at">SUBZONE_N =</span> <span class="fu">map_chr</span>(Description, extract_kml_field, <span class="st">"SUBZONE_N"</span>),</span>
<span id="cb6-20"><a href="#cb6-20"></a>    <span class="at">SUBZONE_C =</span> <span class="fu">map_chr</span>(Description, extract_kml_field, <span class="st">"SUBZONE_C"</span>)</span>
<span id="cb6-21"><a href="#cb6-21"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb6-22"><a href="#cb6-22"></a>  <span class="fu">select</span>(<span class="sc">-</span>Name, <span class="sc">-</span>Description) <span class="sc">%&gt;%</span></span>
<span id="cb6-23"><a href="#cb6-23"></a>  <span class="fu">relocate</span>(geometry, <span class="at">.after =</span> <span class="fu">last_col</span>())</span>
<span id="cb6-24"><a href="#cb6-24"></a></span>
<span id="cb6-25"><a href="#cb6-25"></a><span class="fu">write_rds</span>(mpsz, <span class="st">"data/rds/mpsz_sf.rds"</span>)</span>
<span id="cb6-26"><a href="#cb6-26"></a>mpsz <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/mpsz_sf.rds"</span>) <span class="sc">%&gt;%</span> <span class="fu">st_transform</span>(<span class="at">crs=</span><span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="o-d-bus-data" class="level3">
<h3 class="anchored" data-anchor-id="o-d-bus-data">5.4 O-D Bus Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a>odbus <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/aspatial/origin_destination_bus_202508.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="data-wrangling-geospatial-data-science" class="level2">
<h2 class="anchored" data-anchor-id="data-wrangling-geospatial-data-science">6. Data Wrangling (Geospatial Data Science)</h2>
<p>This section executes the Geospatial Data Science tasks, including TAZ derivation, bus stop assignment, and temporal aggregation.</p>
<section id="preprocess-bus-stops" class="level3">
<h3 class="anchored" data-anchor-id="preprocess-bus-stops">6.1 Preprocess Bus Stops</h3>
<p>We rename the bus stop code field to standardize the joining key with the O-D trip data and perform a spatial filter to retain only bus stops located within the official planning subzone boundaries.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a>BusStop <span class="ot">&lt;-</span> BusStop <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">ORIGIN_PT_CODE =</span> BUS_STOP_N) <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2"></a>  <span class="fu">select</span>(ORIGIN_PT_CODE, geometry)</span>
<span id="cb8-3"><a href="#cb8-3"></a></span>
<span id="cb8-4"><a href="#cb8-4"></a><span class="co"># Extracting bus stops within Singapore</span></span>
<span id="cb8-5"><a href="#cb8-5"></a>BusStop_in_SG <span class="ot">&lt;-</span> <span class="fu">st_join</span>(BusStop, mpsz, <span class="at">join =</span> st_within, <span class="at">left =</span> <span class="cn">FALSE</span>)</span>
<span id="cb8-6"><a href="#cb8-6"></a></span>
<span id="cb8-7"><a href="#cb8-7"></a><span class="fu">cat</span>(<span class="st">"Number of bus stops in SG:"</span>, <span class="fu">nrow</span>(BusStop_in_SG), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of bus stops in SG: 5167 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="fu">print</span>(<span class="fu">head</span>(BusStop_in_SG))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 5 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 20134.2 ymin: 31253.63 xmax: 35565.66 ymax: 41659.52
Projected CRS: SVY21 / Singapore TM
  ORIGIN_PT_CODE          REGION_N  PLN_AREA_N                     SUBZONE_N
1          65059 NORTH-EAST REGION    SENGKANG                     RIVERVALE
2          16171    CENTRAL REGION  QUEENSTOWN NATIONAL UNIVERSITY OF S'PORE
3          61101    CENTRAL REGION   TOA PAYOH                  POTONG PASIR
4          01239    CENTRAL REGION     KALLANG                      CRAWFORD
5          17269       WEST REGION    CLEMENTI                 CLEMENTI WEST
6          11291    CENTRAL REGION BUKIT TIMAH                    ULU PANDAN
  SUBZONE_C                  geometry
1    SESZ02 POINT (35565.66 41659.52)
2    QTSZ11 POINT (21439.91 31253.63)
3    TPSZ09 POINT (31381.06 35313.49)
4    KLSZ09 POINT (31152.55 31688.08)
5    CLSZ08  POINT (20134.2 31917.38)
6    BTSZ04 POINT (22723.57 33349.85)</code></pre>
</div>
</div>
<ul>
<li>This confirms that 5,167 bus stops are located within the current Master Plan 2019 boundaries and are included in the analysis.</li>
<li>Final confirmation that the point data is in the correct projected CRS for accurate distance and spatial operations.</li>
</ul>
</section>
<section id="derive-analytical-hexagon-grid" class="level3">
<h3 class="anchored" data-anchor-id="derive-analytical-hexagon-grid">6.2 Derive Analytical Hexagon Grid</h3>
<p>We generate the mandatory 375m hexagon grid (TAZ) by calculating the correct side length from the apothem and then clip the grid to the land area. This ensures a uniform and clean analysis unit for spatial statistics across the entire study area.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a>a_m <span class="ot">&lt;-</span> <span class="dv">375</span></span>
<span id="cb12-2"><a href="#cb12-2"></a>s_m <span class="ot">&lt;-</span> (<span class="dv">2</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">3</span>)) <span class="sc">*</span> a_m</span>
<span id="cb12-3"><a href="#cb12-3"></a>hex_grid_all <span class="ot">&lt;-</span> <span class="fu">st_make_grid</span>(mpsz, <span class="at">cellsize =</span> s_m, <span class="at">square =</span> <span class="cn">FALSE</span>, <span class="at">flat_topped =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> <span class="fu">st_sf</span>() <span class="sc">%&gt;%</span></span>
<span id="cb12-4"><a href="#cb12-4"></a><span class="fu">rowid_to_column</span>(<span class="st">"Hexagon_ID"</span>)</span>
<span id="cb12-5"><a href="#cb12-5"></a></span>
<span id="cb12-6"><a href="#cb12-6"></a><span class="co"># Intersecting the full grid with the land area (union of subzones)</span></span>
<span id="cb12-7"><a href="#cb12-7"></a><span class="co"># This removes areas over sea, ensuring clean study area boundaries</span></span>
<span id="cb12-8"><a href="#cb12-8"></a>hex_grid <span class="ot">&lt;-</span> <span class="fu">st_intersection</span>(hex_grid_all, <span class="fu">st_union</span>(mpsz)) <span class="sc">%&gt;%</span> <span class="fu">select</span>(Hexagon_ID, geometry)</span>
<span id="cb12-9"><a href="#cb12-9"></a></span>
<span id="cb12-10"><a href="#cb12-10"></a>hex_grid<span class="sc">$</span>HEX_ID <span class="ot">&lt;-</span> <span class="fu">sprintf</span>(<span class="st">"H%04d"</span>, <span class="fu">seq_len</span>(<span class="fu">nrow</span>(hex_grid))) <span class="sc">%&gt;%</span> <span class="fu">as.factor</span>()</span>
<span id="cb12-11"><a href="#cb12-11"></a>hex_grid <span class="ot">&lt;-</span> hex_grid <span class="sc">%&gt;%</span> <span class="fu">select</span>(Hexagon_ID, HEX_ID, geometry)</span>
<span id="cb12-12"><a href="#cb12-12"></a></span>
<span id="cb12-13"><a href="#cb12-13"></a><span class="fu">cat</span>(<span class="st">"Number of total TAZ hexagons:"</span>, <span class="fu">nrow</span>(hex_grid), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of total TAZ hexagons: 5439 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a><span class="fu">print</span>(<span class="fu">head</span>(hex_grid))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 2 fields
Geometry type: GEOMETRY
Dimension:     XY
Bounding box:  xmin: 16827.08 ymin: 15748.72 xmax: 17901.22 ymax: 16831.25
Projected CRS: SVY21 / Singapore TM
    Hexagon_ID HEX_ID                       geometry
93          93  H0001 MULTIPOLYGON (((17762.3 159...
237        237  H0002 POLYGON ((17714.79 15965.23...
308        308  H0003 POLYGON ((17417.54 16614.75...
309        309  H0004 POLYGON ((17830.69 16464.32...
380        380  H0005 POLYGON ((17042.54 16831.25...
381        381  H0006 MULTIPOLYGON (((17417.54 16...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a><span class="co"># Overlaying hexagons on subzones to confirm proper coverage</span></span>
<span id="cb16-2"><a href="#cb16-2"></a><span class="fu">library</span>(tmap)</span>
<span id="cb16-3"><a href="#cb16-3"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb16-4"><a href="#cb16-4"></a></span>
<span id="cb16-5"><a href="#cb16-5"></a><span class="fu">tm_shape</span>(mpsz) <span class="sc">+</span></span>
<span id="cb16-6"><a href="#cb16-6"></a>  <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"lightgray"</span>, <span class="at">border.col =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb16-7"><a href="#cb16-7"></a>  <span class="fu">tm_shape</span>(hex_grid) <span class="sc">+</span></span>
<span id="cb16-8"><a href="#cb16-8"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="fl">0.3</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb16-9"><a href="#cb16-9"></a>  <span class="fu">tm_layout</span>(</span>
<span id="cb16-10"><a href="#cb16-10"></a>    <span class="at">main.title =</span> <span class="st">"375m Analytical Hexagon Grid Overlay on Master Plan Subzones"</span>,</span>
<span id="cb16-11"><a href="#cb16-11"></a>    <span class="at">frame =</span> <span class="cn">FALSE</span></span>
<span id="cb16-12"><a href="#cb16-12"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_Home_Ex2_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>This confirms the creation of 5,439 consistent, area-preserving analytical units (TAZs) for the entire land area of Singapore.</li>
<li>The visualization confirms the TAZ layer is uniformly distributed across the land area and neatly clipped, making it a robust base for contagion-based spatial analysis (LMSA/EHSA).</li>
</ul>
</section>
<section id="classify-time-intervals" class="level3">
<h3 class="anchored" data-anchor-id="classify-time-intervals">6.3 Classify Time Intervals</h3>
<p>This function translates the raw trip time (hour) and day type into the three required analytical time intervals, ensuring that trip data is correctly categorized for temporal analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a><span class="co"># Function converts raw DAY_TYPE + hour into analytical time intervals</span></span>
<span id="cb17-2"><a href="#cb17-2"></a></span>
<span id="cb17-3"><a href="#cb17-3"></a>classify_time <span class="ot">&lt;-</span> <span class="cf">function</span>(day_type, time_per_hour){</span>
<span id="cb17-4"><a href="#cb17-4"></a>  <span class="cf">if</span>(day_type <span class="sc">==</span> <span class="st">"WEEKDAY"</span>){</span>
<span id="cb17-5"><a href="#cb17-5"></a> <span class="co"># 6am to 9am (includes 6, 7, 8)</span></span>
<span id="cb17-6"><a href="#cb17-6"></a>  <span class="cf">if</span>(time_per_hour <span class="sc">&gt;=</span> <span class="dv">6</span> <span class="sc">&amp;</span> time_per_hour <span class="sc">&lt;=</span> <span class="dv">8</span>) <span class="fu">return</span>(<span class="st">"Weekday_AM_Peak"</span>) </span>
<span id="cb17-7"><a href="#cb17-7"></a> <span class="co"># 5pm to 8pm (includes 17, 18, 19)</span></span>
<span id="cb17-8"><a href="#cb17-8"></a>  <span class="cf">if</span>(time_per_hour <span class="sc">&gt;=</span> <span class="dv">17</span> <span class="sc">&amp;</span> time_per_hour <span class="sc">&lt;=</span> <span class="dv">19</span>) <span class="fu">return</span>(<span class="st">"Weekday_PM_Peak"</span>) </span>
<span id="cb17-9"><a href="#cb17-9"></a> } <span class="cf">else</span> <span class="cf">if</span>(day_type <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"WEEKENDS/HOLIDAY"</span>)){</span>
<span id="cb17-10"><a href="#cb17-10"></a> <span class="co"># 11am to 8pm (includes 11 through 19)</span></span>
<span id="cb17-11"><a href="#cb17-11"></a>  <span class="cf">if</span>(time_per_hour <span class="sc">&gt;=</span> <span class="dv">11</span> <span class="sc">&amp;</span> time_per_hour <span class="sc">&lt;=</span> <span class="dv">19</span>) <span class="fu">return</span>(<span class="st">"Weekend_Peak"</span>)</span>
<span id="cb17-12"><a href="#cb17-12"></a> }</span>
<span id="cb17-13"><a href="#cb17-13"></a><span class="fu">return</span>(<span class="st">"Other"</span>)</span>
<span id="cb17-14"><a href="#cb17-14"></a>}</span>
<span id="cb17-15"><a href="#cb17-15"></a></span>
<span id="cb17-16"><a href="#cb17-16"></a><span class="fu">cat</span>(<span class="st">"Test classify_time function:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Test classify_time function:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a><span class="co"># Test revised function against boundary cases</span></span>
<span id="cb19-2"><a href="#cb19-2"></a><span class="fu">print</span>(<span class="fu">sapply</span>(<span class="fu">list</span>(<span class="fu">c</span>(<span class="st">"WEEKDAY"</span>, <span class="dv">8</span>), <span class="fu">c</span>(<span class="st">"WEEKDAY"</span>, <span class="dv">9</span>), <span class="fu">c</span>(<span class="st">"WEEKENDS/HOLIDAY"</span>, <span class="dv">19</span>), <span class="fu">c</span>(<span class="st">"WEEKENDS/HOLIDAY"</span>, <span class="dv">20</span>)), </span>
<span id="cb19-3"><a href="#cb19-3"></a>             <span class="cf">function</span>(x) <span class="fu">paste</span>(x[<span class="dv">1</span>], x[<span class="dv">2</span>], <span class="st">"-&gt;"</span>, <span class="fu">classify_time</span>(x[<span class="dv">1</span>], <span class="fu">as.numeric</span>(x[<span class="dv">2</span>])))))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "WEEKDAY 8 -&gt; Weekday_AM_Peak"        "WEEKDAY 9 -&gt; Other"                 
[3] "WEEKENDS/HOLIDAY 19 -&gt; Weekend_Peak" "WEEKENDS/HOLIDAY 20 -&gt; Other"       </code></pre>
</div>
</div>
<ul>
<li>The function correctly includes trips starting during the 8th hour (8:00 AM - 8:59 AM) in the AM Peak.</li>
<li>The function correctly excludes trips starting in the 9th hour (9:00 AM onward), adhering to the boundary condition of the 6 AM to 9 AM interval.</li>
</ul>
</section>
<section id="aggregate-passenger-trips" class="level3">
<h3 class="anchored" data-anchor-id="aggregate-passenger-trips">6.4 Aggregate Passenger Trips</h3>
<p>We filter the raw data by trip type and the defined time intervals, then aggregate the total trips for every unique origin bus stop across the analyzed time periods.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a>trips_by_stop <span class="ot">&lt;-</span> odbus <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2"></a>  <span class="fu">filter</span>(PT_TYPE<span class="sc">==</span><span class="st">"BUS"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span></span>
<span id="cb21-4"><a href="#cb21-4"></a>  <span class="fu">mutate</span>(<span class="at">Time_Interval =</span> <span class="fu">classify_time</span>(DAY_TYPE, <span class="fu">as.numeric</span>(TIME_PER_HOUR))) <span class="sc">%&gt;%</span></span>
<span id="cb21-5"><a href="#cb21-5"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb21-6"><a href="#cb21-6"></a>  <span class="fu">filter</span>(Time_Interval <span class="sc">!=</span> <span class="st">"Other"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb21-7"><a href="#cb21-7"></a>  <span class="fu">group_by</span>(ORIGIN_PT_CODE, Time_Interval) <span class="sc">%&gt;%</span></span>
<span id="cb21-8"><a href="#cb21-8"></a>  <span class="fu">summarise</span>(<span class="at">Total_Trips =</span> <span class="fu">sum</span>(TOTAL_TRIPS, <span class="at">na.rm=</span><span class="cn">TRUE</span>), <span class="at">.groups=</span><span class="st">"drop"</span>)</span>
<span id="cb21-9"><a href="#cb21-9"></a></span>
<span id="cb21-10"><a href="#cb21-10"></a><span class="fu">cat</span>(<span class="st">"Aggregated trips per bus stop &amp; time interval:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Aggregated trips per bus stop &amp; time interval:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1"></a><span class="fu">print</span>(<span class="fu">head</span>(trips_by_stop))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  ORIGIN_PT_CODE Time_Interval   Total_Trips
  &lt;chr&gt;          &lt;chr&gt;                 &lt;dbl&gt;
1 01012          Weekday_AM_Peak        1345
2 01012          Weekday_PM_Peak        6731
3 01012          Weekend_Peak           6476
4 01013          Weekday_AM_Peak         631
5 01013          Weekday_PM_Peak        6666
6 01013          Weekend_Peak           6333</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1"></a><span class="fu">summary</span>(trips_by_stop<span class="sc">$</span>Total_Trips)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
      1     486    1709    4048    4232  399114 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1"></a><span class="co"># Summary statistics of trips by time interval (for EDA)</span></span>
<span id="cb27-2"><a href="#cb27-2"></a>trip_summary <span class="ot">&lt;-</span> trips_by_stop <span class="sc">%&gt;%</span></span>
<span id="cb27-3"><a href="#cb27-3"></a>  <span class="fu">group_by</span>(Time_Interval) <span class="sc">%&gt;%</span></span>
<span id="cb27-4"><a href="#cb27-4"></a>  <span class="fu">summarise</span>(</span>
<span id="cb27-5"><a href="#cb27-5"></a>    <span class="at">Mean_Trips =</span> <span class="fu">mean</span>(Total_Trips, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb27-6"><a href="#cb27-6"></a>    <span class="at">Median_Trips =</span> <span class="fu">median</span>(Total_Trips, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb27-7"><a href="#cb27-7"></a>    <span class="at">SD_Trips =</span> <span class="fu">sd</span>(Total_Trips, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb27-8"><a href="#cb27-8"></a>    <span class="at">Max_Trips =</span> <span class="fu">max</span>(Total_Trips, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb27-9"><a href="#cb27-9"></a>  )</span>
<span id="cb27-10"><a href="#cb27-10"></a></span>
<span id="cb27-11"><a href="#cb27-11"></a><span class="fu">print</span>(trip_summary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  Time_Interval   Mean_Trips Median_Trips SD_Trips Max_Trips
  &lt;chr&gt;                &lt;dbl&gt;        &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 Weekday_AM_Peak      4123.        1735     8933.    288060
2 Weekday_PM_Peak      4177.        1775    12756.    399114
3 Weekend_Peak         3847.        1622.   10602.    303197</code></pre>
</div>
</div>
<ul>
<li>The median number of trips generated by an active bus stop is highly consistent across all three peak periods (approx. 1,700-1,800 trips), showing a stable baseline for demand.</li>
<li>The maximum trip generation occurs during the Weekday PM Peak, reflecting the most highly concentrated single points of demand (likely major residential transport hubs) during the week.</li>
<li>The highest mean trips occur during Weekday PM Peak (4,177), followed closely by AM Peak (4,123), with the Weekend Peak showing the lowest average demand (3,847).</li>
</ul>
</section>
<section id="spatial-join-bus-stops-to-hex-grid" class="level3">
<h3 class="anchored" data-anchor-id="spatial-join-bus-stops-to-hex-grid">6.5 Spatial join bus stops to hex grid</h3>
<p>The cleaned bus stop points are joined to the hexagonal TAZ grid using the spatial st_within operation. This establishes the spatial context for trip origins.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a>BusStop_hex <span class="ot">&lt;-</span> <span class="fu">st_join</span>(BusStop, hex_grid, <span class="at">join =</span> st_within) <span class="sc">%&gt;%</span> <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="#cb29-2"></a>  <span class="fu">select</span>(ORIGIN_PT_CODE, Hexagon_ID)</span>
<span id="cb29-3"><a href="#cb29-3"></a></span>
<span id="cb29-4"><a href="#cb29-4"></a><span class="fu">cat</span>(<span class="st">"Bus stops assigned to hexagons:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Bus stops assigned to hexagons:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a><span class="fu">print</span>(<span class="fu">head</span>(BusStop_hex))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  ORIGIN_PT_CODE Hexagon_ID
1          65059       8757
2          16171       5282
3          61101       6663
4          01239       5439
5          17269       5496
6          11291       5931</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a>table_count <span class="ot">&lt;-</span> BusStop_hex <span class="sc">%&gt;%</span> <span class="fu">count</span>(Hexagon_ID)</span>
<span id="cb33-2"><a href="#cb33-2"></a><span class="fu">summary</span>(table_count<span class="sc">$</span>n)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  1.000   2.000   2.000   2.822   4.000  10.000 </code></pre>
</div>
</div>
<ul>
<li>The output shows that an average TAZ contains 2 to 3 bus stops, with a maximum of 10, confirming the high density of the TAZ grid and the granularity of the analysis unit.</li>
</ul>
</section>
<section id="aggregate-trips-to-hexagon-level" class="level3">
<h3 class="anchored" data-anchor-id="aggregate-trips-to-hexagon-level">6.6 Aggregate trips to hexagon level</h3>
<p>This critical step aggregates the trips from all bus stops within each TAZ hexagon, creating the final variable of interest (Total_Passenger_Trips). Importantly, it ensures temporal continuity by explicitly inserting zero values for hexagons without any trips in a given interval, which is essential for accurate spatial statistics (LMSA/EHSA).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1"></a>hex_trips <span class="ot">&lt;-</span> BusStop_hex <span class="sc">%&gt;%</span></span>
<span id="cb35-2"><a href="#cb35-2"></a>  <span class="fu">left_join</span>(trips_by_stop, <span class="at">by=</span><span class="st">"ORIGIN_PT_CODE"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb35-3"><a href="#cb35-3"></a>  <span class="fu">drop_na</span>(Total_Trips) <span class="sc">%&gt;%</span></span>
<span id="cb35-4"><a href="#cb35-4"></a>  <span class="fu">group_by</span>(Hexagon_ID, Time_Interval) <span class="sc">%&gt;%</span></span>
<span id="cb35-5"><a href="#cb35-5"></a>  <span class="fu">summarise</span>(<span class="at">Total_Passenger_Trips=</span><span class="fu">sum</span>(Total_Trips, <span class="at">na.rm=</span><span class="cn">TRUE</span>), <span class="at">.groups=</span><span class="st">"drop"</span>)</span>
<span id="cb35-6"><a href="#cb35-6"></a></span>
<span id="cb35-7"><a href="#cb35-7"></a>all_intervals <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Weekday_AM_Peak"</span>, <span class="st">"Weekday_PM_Peak"</span>, <span class="st">"Weekend_Peak"</span>)</span>
<span id="cb35-8"><a href="#cb35-8"></a>hex_grid_time <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">Hexagon_ID =</span> hex_grid<span class="sc">$</span>Hexagon_ID, <span class="at">Time_Interval =</span> all_intervals)</span>
<span id="cb35-9"><a href="#cb35-9"></a></span>
<span id="cb35-10"><a href="#cb35-10"></a>hex_grid_full <span class="ot">&lt;-</span> hex_grid_time <span class="sc">%&gt;%</span></span>
<span id="cb35-11"><a href="#cb35-11"></a>  <span class="fu">left_join</span>(hex_trips, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"Hexagon_ID"</span>, <span class="st">"Time_Interval"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb35-12"><a href="#cb35-12"></a>  <span class="fu">left_join</span>(hex_grid <span class="sc">%&gt;%</span> <span class="fu">select</span>(Hexagon_ID, geometry), <span class="at">by=</span><span class="st">"Hexagon_ID"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb35-13"><a href="#cb35-13"></a>  <span class="fu">st_as_sf</span>()</span>
<span id="cb35-14"><a href="#cb35-14"></a></span>
<span id="cb35-15"><a href="#cb35-15"></a>hex_grid_full<span class="sc">$</span>Total_Passenger_Trips[<span class="fu">is.na</span>(hex_grid_full<span class="sc">$</span>Total_Passenger_Trips)] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb35-16"><a href="#cb35-16"></a>hex_grid_split <span class="ot">&lt;-</span> <span class="fu">split</span>(hex_grid_full, hex_grid_full<span class="sc">$</span>Time_Interval)</span>
<span id="cb35-17"><a href="#cb35-17"></a></span>
<span id="cb35-18"><a href="#cb35-18"></a><span class="fu">cat</span>(<span class="st">"Hexagon-level aggregated trips:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Hexagon-level aggregated trips:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1"></a><span class="fu">print</span>(<span class="fu">head</span>(hex_grid_full))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 3 fields
Geometry type: GEOMETRY
Dimension:     XY
Bounding box:  xmin: 16827.08 ymin: 15748.72 xmax: 17901.22 ymax: 16831.25
Projected CRS: SVY21 / Singapore TM
  Hexagon_ID   Time_Interval Total_Passenger_Trips
1         93 Weekday_AM_Peak                     0
2        237 Weekday_AM_Peak                     0
3        308 Weekday_AM_Peak                     0
4        309 Weekday_AM_Peak                     0
5        380 Weekday_AM_Peak                     0
6        381 Weekday_AM_Peak                     0
                        geometry
1 MULTIPOLYGON (((17762.3 159...
2 POLYGON ((17714.79 15965.23...
3 POLYGON ((17417.54 16614.75...
4 POLYGON ((17830.69 16464.32...
5 POLYGON ((17042.54 16831.25...
6 MULTIPOLYGON (((17417.54 16...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1"></a><span class="fu">summary</span>(hex_grid_full<span class="sc">$</span>Total_Passenger_Trips)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
      0       0       0    3718    1132  473352 </code></pre>
</div>
</div>
<ul>
<li>The final dataset confirms the average number of trips generated by a TAZ hexagon across the three intervals is approximately 3,718.</li>
<li>Confirms that the highest concentration of trips originating in a single 375m area occurs during the observation period.</li>
<li>The majority of hexagons have no observed trip data for a given interval, confirming the sparse nature of the data and the necessity of using clustering statistics (Gi*) to distinguish meaningful concentrations from noise.</li>
</ul>
</section>
</section>
<section id="eda-exploratory-data-analysis---visualisation" class="level2">
<h2 class="anchored" data-anchor-id="eda-exploratory-data-analysis---visualisation">7. EDA (Exploratory Data Analysis - Visualisation)</h2>
<section id="visualise-trip-distribution" class="level3">
<h3 class="anchored" data-anchor-id="visualise-trip-distribution">7.1 Visualise Trip Distribution</h3>
<p>We generate professional choropleth maps using the Jenks natural breaks method, which is optimal for heterogeneous spatial data, to visually reveal the geographical distribution of passenger trip origins across the three peak periods.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1"></a>create_trip_map <span class="ot">&lt;-</span> <span class="cf">function</span>(data, title){</span>
<span id="cb41-2"><a href="#cb41-2"></a>  n_unique <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">unique</span>(data<span class="sc">$</span>Total_Passenger_Trips))</span>
<span id="cb41-3"><a href="#cb41-3"></a>  <span class="cf">if</span>(n_unique <span class="sc">==</span> <span class="dv">1</span>){</span>
<span id="cb41-4"><a href="#cb41-4"></a>    breaks <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, data<span class="sc">$</span>Total_Passenger_Trips[<span class="dv">1</span>] <span class="sc">+</span> <span class="dv">1</span>)</span>
<span id="cb41-5"><a href="#cb41-5"></a>  } <span class="cf">else</span> {</span>
<span id="cb41-6"><a href="#cb41-6"></a>    breaks <span class="ot">&lt;-</span> <span class="fu">classIntervals</span>(data<span class="sc">$</span>Total_Passenger_Trips, <span class="at">n =</span> <span class="dv">5</span>, <span class="at">style =</span> <span class="st">"jenks"</span>)<span class="sc">$</span>brks</span>
<span id="cb41-7"><a href="#cb41-7"></a>  }</span>
<span id="cb41-8"><a href="#cb41-8"></a>  </span>
<span id="cb41-9"><a href="#cb41-9"></a>  <span class="fu">tm_shape</span>(mpsz) <span class="sc">+</span>  <span class="co"># add subzone base layer</span></span>
<span id="cb41-10"><a href="#cb41-10"></a>    <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"grey80"</span>, <span class="at">lwd =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb41-11"><a href="#cb41-11"></a>    <span class="fu">tm_shape</span>(data) <span class="sc">+</span></span>
<span id="cb41-12"><a href="#cb41-12"></a>    <span class="fu">tm_fill</span>(</span>
<span id="cb41-13"><a href="#cb41-13"></a>      <span class="st">"Total_Passenger_Trips"</span>,</span>
<span id="cb41-14"><a href="#cb41-14"></a>      <span class="at">breaks =</span> breaks,</span>
<span id="cb41-15"><a href="#cb41-15"></a>      <span class="at">palette =</span> <span class="st">"YlGnBu"</span>,</span>
<span id="cb41-16"><a href="#cb41-16"></a>      <span class="at">fill_alpha =</span> <span class="fl">0.7</span>,</span>
<span id="cb41-17"><a href="#cb41-17"></a>      <span class="at">title =</span> <span class="st">"Trips"</span></span>
<span id="cb41-18"><a href="#cb41-18"></a>    ) <span class="sc">+</span></span>
<span id="cb41-19"><a href="#cb41-19"></a>    <span class="fu">tm_borders</span>(<span class="st">"grey30"</span>, <span class="at">lwd =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb41-20"><a href="#cb41-20"></a>    <span class="fu">tm_title</span>(title) <span class="sc">+</span></span>
<span id="cb41-21"><a href="#cb41-21"></a>    <span class="fu">tm_compass</span>(<span class="at">position =</span> <span class="fu">c</span>(<span class="st">"left"</span>,<span class="st">"top"</span>)) <span class="sc">+</span></span>
<span id="cb41-22"><a href="#cb41-22"></a>    <span class="fu">tm_scalebar</span>(<span class="at">position =</span> <span class="fu">c</span>(<span class="st">"left"</span>,<span class="st">"bottom"</span>)) <span class="sc">+</span></span>
<span id="cb41-23"><a href="#cb41-23"></a>    <span class="fu">tm_layout</span>(<span class="at">frame =</span> <span class="cn">FALSE</span>)</span>
<span id="cb41-24"><a href="#cb41-24"></a>}</span>
<span id="cb41-25"><a href="#cb41-25"></a></span>
<span id="cb41-26"><a href="#cb41-26"></a><span class="co"># Creating maps</span></span>
<span id="cb41-27"><a href="#cb41-27"></a>map_am <span class="ot">&lt;-</span> <span class="fu">create_trip_map</span>(hex_grid_split<span class="sc">$</span>Weekday_AM_Peak, <span class="st">"Weekday AM Peak"</span>)</span>
<span id="cb41-28"><a href="#cb41-28"></a>map_pm <span class="ot">&lt;-</span> <span class="fu">create_trip_map</span>(hex_grid_split<span class="sc">$</span>Weekday_PM_Peak, <span class="st">"Weekday PM Peak"</span>)</span>
<span id="cb41-29"><a href="#cb41-29"></a>map_weekend <span class="ot">&lt;-</span> <span class="fu">create_trip_map</span>(hex_grid_split<span class="sc">$</span>Weekend_Peak, <span class="st">"Weekend/Holiday Peak"</span>)</span>
<span id="cb41-30"><a href="#cb41-30"></a></span>
<span id="cb41-31"><a href="#cb41-31"></a><span class="co"># Printing maps</span></span>
<span id="cb41-32"><a href="#cb41-32"></a><span class="fu">print</span>(map_am)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_Home_Ex2_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1"></a><span class="fu">print</span>(map_pm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_Home_Ex2_files/figure-html/unnamed-chunk-12-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1"></a><span class="fu">print</span>(map_weekend)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_Home_Ex2_files/figure-html/unnamed-chunk-12-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Weekday AM Peak: The visualization reveals a highly decentralized pattern of trip origins, concentrated in distinct residential nodes in the North (Woodlands), Northeast (Sengkang/Punggol), and far West. These areas display the highest intensity, clearly functioning as primary bus feeders for commuters. Conversely, the Central and Southern sectors, including the CBD and high-density residential areas adjacent to it, show extremely low origin counts, reinforcing their primary role as destinations during the morning peak. The spatial distribution is highly clustered and non-random, confirming the need for localized analysis.</p></li>
<li><p>Weekday PM Peak: The pattern maintains the core residential structure, with the highest trip origins remaining in the North, Northeast, and West, indicating bus usage for the evening commute is strongly concentrated around large housing estates. Compared to the AM Peak, the intensity in the highest classes (&gt;242,424 trips) is marginally higher (Max approx 473,352 vs 288,060), suggesting bus dispersal during the evening is slightly more concentrated than morning convergence. The low origin areas (Coldspots) in the Central region persist, confirming minimal originating trips from these destination zones.</p></li>
<li><p>Weekend/Holiday Peak Map: The map shows a lower overall spatial intensity in the highest trip brackets compared to both weekdays (Max approx 338,258). While high-origin areas still track residential zones, the pattern appears more diffuse and widespread. High-volume clusters are visible near major regional centers, reflecting diverse, non-commute trips (leisure, shopping) that rely on regional bus hubs rather than highly synchronized CBD commutes. The lack of a strong directional pattern confirms the underlying demand is flatter and less time-sensitive on weekends.</p></li>
</ul>
</section>
</section>
<section id="analysis" class="level2">
<h2 class="anchored" data-anchor-id="analysis">8. Analysis</h2>
<section id="lmsa-spatial-weights" class="level3">
<h3 class="anchored" data-anchor-id="lmsa-spatial-weights">8.1 LMSA: Spatial Weights</h3>
<p>We define the spatial neighborhood structure using Queen contiguity (as demonstrated in Hand-on Ex 8), where hexagons sharing any border or vertex are considered neighbors. This weights matrix is row-standardized (style = “W”) for use in the LMSA and EHSA metrics.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1"></a>common_hex <span class="ot">&lt;-</span> <span class="fu">Reduce</span>(intersect, <span class="fu">lapply</span>(hex_grid_split, <span class="cf">function</span>(x) x<span class="sc">$</span>Hexagon_ID))</span>
<span id="cb44-2"><a href="#cb44-2"></a>hex_common_geom <span class="ot">&lt;-</span> hex_grid <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Hexagon_ID <span class="sc">%in%</span> common_hex)</span>
<span id="cb44-3"><a href="#cb44-3"></a>nb <span class="ot">&lt;-</span> <span class="fu">poly2nb</span>(hex_common_geom, <span class="at">queen =</span> <span class="cn">TRUE</span>, <span class="at">snap =</span> <span class="dv">1900</span>)</span>
<span id="cb44-4"><a href="#cb44-4"></a>listw <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(nb, <span class="at">style =</span> <span class="st">"W"</span>, <span class="at">zero.policy =</span> <span class="cn">TRUE</span>)</span>
<span id="cb44-5"><a href="#cb44-5"></a></span>
<span id="cb44-6"><a href="#cb44-6"></a><span class="fu">cat</span>(<span class="st">"Spatial neighbors object:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Spatial neighbors object:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1"></a><span class="fu">print</span>(nb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 5439 
Number of nonzero links: 498034 
Percentage nonzero weights: 1.68353 
Average number of links: 91.5672 
1 region with no links:
1052</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1"></a><span class="fu">summary</span>(listw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 5439 
Number of nonzero links: 498034 
Percentage nonzero weights: 1.68353 
Average number of links: 91.5672 
1 region with no links:
1052
Link number distribution:

   0    4    8   12   15   17   18   19   20   21   22   23   24   25   26   27 
   1    1    1    1    3    3    3    1    4    4    6    6    3    7    6    4 
  28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43 
  13   10    6   14    5   10   15   10   13    9   11   12   13   15   10   13 
  44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59 
  17   21   16   24   20   23   28   20   15   21   29   25   29   37   42   41 
  60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75 
  41   31   37   30   36   37   42   45   34   40   60   35   43   38   30   36 
  76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91 
  31   46   47   48   32   56   54   47   42   42   36   44   53   48   55   46 
  92   93   94   95   96   97   98   99  100  101  102  103  104  105  106  107 
  52   37   36   52   49   46   55   55   48   56   40   45   67   74   87   99 
 108 
2558 
1 least connected region:
1864 with 4 links
2558 most connected regions:
669 703 704 738 811 878 879 881 882 911 912 913 917 940 941 942 943 944 945 946 947 948 973 974 975 976 977 978 979 980 981 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1036 1037 1038 1039 1040 1041 1042 1043 1044 1045 1066 1067 1068 1069 1070 1071 1072 1073 1074 1075 1076 1099 1100 1101 1102 1103 1104 1105 1106 1107 1108 1109 1110 1137 1138 1139 1140 1141 1142 1143 1144 1145 1146 1147 1148 1149 1180 1181 1182 1183 1184 1185 1186 1187 1188 1189 1190 1191 1192 1193 1225 1226 1227 1228 1229 1230 1231 1232 1233 1234 1235 1236 1237 1238 1271 1272 1273 1274 1275 1276 1277 1278 1279 1280 1281 1282 1283 1284 1317 1318 1319 1320 1321 1322 1323 1324 1325 1326 1327 1328 1329 1330 1331 1364 1365 1366 1367 1368 1369 1370 1371 1372 1373 1374 1375 1376 1377 1378 1379 1413 1414 1415 1416 1417 1418 1419 1420 1421 1422 1423 1424 1425 1426 1427 1428 1429 1465 1466 1467 1468 1469 1470 1471 1472 1473 1474 1475 1476 1477 1478 1479 1480 1481 1482 1520 1521 1522 1523 1524 1525 1526 1527 1528 1529 1530 1531 1532 1533 1534 1535 1536 1537 1538 1562 1563 1575 1576 1577 1578 1579 1580 1581 1582 1583 1584 1585 1586 1587 1588 1589 1590 1591 1592 1593 1594 1595 1596 1623 1624 1625 1635 1636 1637 1638 1639 1640 1641 1642 1643 1644 1645 1646 1647 1648 1649 1650 1651 1652 1653 1654 1655 1656 1657 1658 1659 1683 1684 1685 1686 1687 1688 1689 1690 1694 1695 1696 1697 1698 1699 1700 1701 1702 1703 1704 1705 1706 1707 1708 1709 1710 1711 1712 1713 1714 1715 1716 1717 1718 1719 1720 1721 1722 1745 1746 1747 1748 1749 1750 1751 1752 1754 1755 1756 1757 1758 1759 1760 1761 1762 1763 1764 1765 1766 1767 1768 1769 1770 1771 1772 1773 1774 1775 1776 1777 1778 1779 1780 1781 1782 1783 1784 1785 1806 1807 1808 1809 1810 1811 1812 1813 1814 1815 1816 1817 1818 1819 1820 1821 1822 1823 1824 1825 1826 1827 1828 1829 1830 1831 1832 1833 1834 1835 1836 1837 1838 1839 1840 1841 1842 1843 1844 1845 1846 1847 1869 1870 1871 1872 1873 1874 1875 1876 1877 1878 1879 1880 1881 1882 1883 1884 1885 1886 1887 1888 1889 1890 1891 1892 1893 1894 1895 1896 1897 1898 1899 1900 1901 1902 1903 1904 1905 1906 1907 1908 1909 1910 1911 1931 1932 1933 1934 1935 1936 1937 1938 1939 1940 1941 1942 1943 1944 1945 1946 1947 1948 1949 1950 1951 1952 1953 1954 1955 1956 1957 1958 1959 1960 1961 1962 1963 1964 1965 1966 1967 1968 1969 1970 1971 1972 1973 1989 1990 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 2025 2026 2027 2028 2029 2030 2031 2032 2033 2048 2049 2050 2051 2052 2053 2054 2055 2056 2057 2058 2059 2060 2061 2062 2063 2064 2065 2066 2067 2068 2069 2070 2071 2072 2073 2074 2075 2076 2077 2078 2079 2080 2081 2082 2083 2084 2085 2086 2087 2088 2089 2090 2091 2092 2108 2109 2110 2111 2112 2113 2114 2115 2116 2117 2118 2119 2120 2121 2122 2123 2124 2125 2126 2127 2128 2129 2130 2131 2132 2133 2134 2135 2136 2137 2138 2139 2140 2141 2142 2143 2144 2145 2146 2147 2148 2149 2150 2151 2152 2153 2158 2159 2166 2167 2168 2169 2170 2171 2172 2173 2174 2175 2176 2177 2178 2179 2180 2181 2182 2183 2184 2185 2186 2187 2188 2189 2190 2191 2192 2193 2194 2195 2196 2197 2198 2199 2200 2201 2202 2203 2204 2205 2206 2207 2208 2209 2210 2211 2212 2213 2214 2215 2216 2217 2218 2225 2226 2227 2228 2229 2230 2231 2232 2233 2234 2235 2236 2237 2238 2239 2240 2241 2242 2243 2244 2245 2246 2247 2248 2249 2250 2251 2252 2253 2254 2255 2256 2257 2258 2259 2260 2261 2262 2263 2264 2265 2266 2267 2268 2269 2270 2271 2272 2273 2274 2275 2276 2285 2286 2287 2288 2289 2290 2291 2292 2293 2294 2295 2296 2297 2298 2299 2300 2301 2302 2303 2304 2305 2306 2307 2308 2309 2310 2311 2312 2313 2314 2315 2316 2317 2318 2319 2320 2321 2322 2323 2324 2325 2326 2327 2328 2329 2330 2331 2332 2333 2334 2335 2336 2337 2346 2347 2348 2349 2350 2351 2352 2353 2354 2355 2356 2357 2358 2359 2360 2361 2362 2363 2364 2365 2366 2367 2368 2369 2370 2371 2372 2373 2374 2375 2376 2377 2378 2379 2380 2381 2382 2383 2384 2385 2386 2387 2388 2389 2390 2391 2392 2393 2394 2395 2396 2397 2398 2407 2408 2409 2410 2411 2412 2413 2414 2415 2416 2417 2418 2419 2420 2421 2422 2423 2424 2425 2426 2427 2428 2429 2430 2431 2432 2433 2434 2435 2436 2437 2438 2439 2440 2441 2442 2443 2444 2445 2446 2447 2448 2449 2450 2451 2452 2453 2454 2455 2456 2457 2458 2459 2468 2469 2470 2471 2472 2473 2474 2475 2476 2477 2478 2479 2480 2481 2482 2483 2484 2485 2486 2487 2488 2489 2490 2491 2492 2493 2494 2495 2496 2497 2498 2499 2500 2501 2502 2503 2504 2505 2506 2507 2508 2509 2510 2511 2512 2513 2514 2515 2516 2517 2518 2519 2520 2530 2531 2532 2533 2534 2535 2536 2537 2538 2539 2540 2541 2542 2543 2544 2545 2546 2547 2548 2549 2550 2551 2552 2553 2554 2555 2556 2557 2558 2559 2560 2561 2562 2563 2564 2565 2566 2567 2568 2569 2570 2571 2572 2573 2574 2575 2576 2577 2578 2579 2580 2581 2593 2594 2595 2596 2597 2598 2599 2600 2601 2602 2603 2604 2605 2606 2607 2608 2609 2610 2611 2612 2613 2614 2615 2616 2617 2618 2619 2620 2621 2622 2623 2624 2625 2626 2627 2628 2629 2630 2631 2632 2633 2634 2635 2636 2637 2638 2639 2640 2641 2642 2643 2644 2656 2657 2658 2659 2660 2661 2662 2663 2664 2665 2666 2667 2668 2669 2670 2671 2672 2673 2674 2675 2676 2677 2678 2679 2680 2681 2682 2683 2684 2685 2686 2687 2688 2689 2690 2691 2692 2693 2694 2695 2696 2697 2698 2699 2700 2701 2702 2703 2704 2705 2706 2707 2708 2720 2721 2722 2723 2724 2725 2726 2727 2728 2729 2730 2731 2732 2733 2734 2735 2736 2737 2738 2739 2740 2741 2742 2743 2744 2745 2746 2747 2748 2749 2750 2751 2752 2753 2754 2755 2756 2757 2758 2759 2760 2761 2762 2763 2764 2765 2766 2767 2768 2769 2770 2783 2784 2785 2786 2787 2788 2789 2790 2791 2792 2793 2794 2795 2796 2797 2798 2799 2800 2801 2802 2803 2804 2805 2806 2807 2808 2809 2810 2811 2812 2813 2814 2815 2816 2817 2818 2819 2820 2821 2822 2823 2824 2825 2826 2827 2828 2829 2830 2831 2832 2845 2846 2847 2848 2849 2850 2851 2852 2853 2854 2855 2856 2857 2858 2859 2860 2861 2862 2863 2864 2865 2866 2867 2868 2869 2870 2871 2872 2873 2874 2875 2876 2877 2878 2879 2880 2881 2882 2883 2884 2885 2886 2887 2888 2889 2890 2891 2892 2893 2894 2909 2910 2911 2912 2913 2914 2915 2916 2917 2918 2919 2920 2921 2922 2923 2924 2925 2926 2927 2928 2929 2930 2931 2932 2933 2934 2935 2936 2937 2938 2939 2940 2941 2942 2943 2944 2945 2946 2947 2948 2949 2950 2951 2952 2953 2954 2955 2956 2957 2958 2972 2973 2974 2975 2976 2977 2978 2979 2980 2981 2982 2983 2984 2985 2986 2987 2988 2989 2990 2991 2992 2993 2994 2995 2996 2997 2998 2999 3000 3001 3002 3003 3004 3005 3006 3007 3008 3009 3010 3011 3012 3013 3014 3015 3016 3017 3018 3019 3020 3034 3035 3036 3037 3038 3039 3040 3041 3042 3043 3044 3045 3046 3047 3048 3049 3050 3051 3052 3053 3054 3055 3056 3057 3058 3059 3060 3061 3062 3063 3064 3065 3066 3067 3068 3069 3070 3071 3072 3073 3074 3075 3076 3077 3078 3079 3080 3081 3082 3096 3097 3098 3099 3100 3101 3102 3103 3104 3105 3106 3107 3108 3109 3110 3111 3112 3113 3114 3115 3116 3117 3118 3119 3120 3121 3122 3123 3124 3125 3126 3127 3128 3129 3130 3131 3132 3133 3134 3135 3136 3137 3141 3142 3143 3159 3160 3161 3162 3163 3164 3165 3166 3167 3168 3169 3170 3171 3172 3173 3174 3175 3176 3177 3178 3179 3180 3181 3182 3183 3184 3185 3186 3187 3188 3189 3190 3191 3192 3193 3194 3195 3196 3197 3198 3204 3205 3206 3219 3220 3221 3222 3223 3224 3225 3226 3227 3228 3229 3230 3231 3232 3233 3234 3235 3236 3237 3238 3239 3240 3241 3242 3243 3244 3245 3246 3247 3248 3249 3250 3251 3252 3253 3254 3255 3256 3257 3258 3265 3266 3281 3282 3283 3284 3285 3286 3287 3288 3289 3290 3291 3292 3293 3294 3295 3296 3297 3298 3299 3300 3301 3302 3303 3304 3305 3306 3307 3308 3309 3310 3311 3312 3313 3314 3315 3316 3317 3318 3319 3327 3343 3344 3345 3346 3347 3348 3349 3350 3351 3352 3353 3354 3355 3356 3357 3358 3359 3360 3361 3362 3363 3364 3365 3366 3367 3368 3369 3370 3371 3372 3373 3374 3375 3376 3377 3378 3379 3380 3381 3389 3402 3403 3404 3405 3406 3407 3408 3409 3410 3411 3412 3413 3414 3415 3416 3417 3418 3419 3420 3421 3422 3423 3424 3425 3426 3427 3428 3429 3430 3431 3432 3433 3434 3435 3436 3437 3438 3439 3440 3463 3464 3465 3466 3467 3468 3469 3470 3471 3472 3473 3474 3475 3476 3477 3478 3479 3480 3481 3482 3483 3484 3485 3486 3487 3488 3489 3490 3491 3492 3493 3494 3495 3496 3497 3498 3499 3500 3524 3525 3526 3527 3528 3529 3530 3531 3532 3533 3534 3535 3536 3537 3538 3539 3540 3541 3542 3543 3544 3545 3546 3547 3548 3549 3550 3551 3552 3553 3554 3555 3556 3557 3558 3559 3560 3561 3584 3585 3586 3587 3588 3589 3590 3591 3592 3593 3594 3595 3596 3597 3598 3599 3600 3601 3602 3603 3604 3605 3606 3607 3608 3609 3610 3611 3612 3613 3614 3615 3616 3617 3618 3619 3620 3621 3644 3645 3646 3647 3648 3649 3650 3651 3652 3653 3654 3655 3656 3657 3658 3659 3660 3661 3662 3663 3664 3665 3666 3667 3668 3669 3670 3671 3672 3673 3674 3675 3676 3677 3678 3679 3680 3705 3706 3707 3708 3709 3710 3711 3712 3713 3714 3715 3716 3717 3718 3719 3720 3721 3722 3723 3724 3725 3726 3727 3728 3729 3730 3731 3732 3733 3734 3735 3736 3737 3738 3739 3740 3741 3757 3764 3765 3766 3767 3768 3769 3770 3771 3772 3773 3774 3775 3776 3777 3778 3779 3780 3781 3782 3783 3784 3785 3786 3787 3788 3789 3790 3791 3792 3793 3794 3795 3796 3797 3798 3799 3800 3814 3822 3823 3824 3825 3826 3827 3828 3829 3830 3831 3832 3833 3834 3835 3836 3837 3838 3839 3840 3841 3842 3843 3844 3845 3846 3847 3848 3849 3850 3851 3852 3853 3854 3855 3856 3857 3872 3873 3881 3882 3883 3884 3885 3886 3887 3888 3889 3890 3891 3892 3893 3894 3895 3896 3897 3898 3899 3900 3901 3902 3903 3904 3905 3906 3907 3908 3909 3910 3911 3912 3913 3914 3915 3928 3929 3930 3937 3938 3939 3940 3941 3942 3943 3944 3945 3946 3947 3948 3949 3950 3951 3952 3953 3954 3955 3956 3957 3958 3959 3960 3961 3962 3963 3964 3965 3966 3967 3968 3969 3970 3971 3984 3985 3986 3994 3995 3996 3997 3998 3999 4000 4001 4002 4003 4004 4005 4006 4007 4008 4009 4010 4011 4012 4013 4014 4015 4016 4017 4018 4019 4020 4021 4022 4023 4024 4025 4026 4027 4040 4041 4042 4043 4050 4051 4052 4053 4054 4055 4056 4057 4058 4059 4060 4061 4062 4063 4064 4065 4066 4067 4068 4069 4070 4071 4072 4073 4074 4075 4076 4077 4078 4079 4080 4081 4082 4083 4084 4093 4094 4095 4096 4104 4105 4106 4107 4108 4109 4110 4111 4112 4113 4114 4115 4116 4117 4118 4119 4120 4121 4122 4123 4124 4125 4126 4127 4128 4129 4130 4131 4132 4133 4134 4135 4136 4137 4146 4147 4148 4149 4156 4157 4158 4159 4160 4161 4162 4163 4164 4165 4166 4167 4168 4169 4170 4171 4172 4173 4174 4175 4176 4177 4178 4179 4180 4181 4182 4183 4184 4185 4186 4187 4188 4189 4202 4203 4204 4205 4212 4213 4214 4215 4216 4217 4218 4219 4220 4221 4222 4223 4224 4225 4226 4227 4228 4229 4230 4231 4232 4233 4234 4235 4236 4237 4238 4239 4240 4241 4242 4243 4244 4261 4262 4263 4271 4272 4273 4274 4275 4276 4277 4278 4279 4280 4281 4282 4283 4284 4285 4286 4287 4288 4289 4290 4291 4292 4293 4294 4295 4296 4297 4298 4299 4300 4321 4322 4323 4324 4331 4332 4333 4334 4335 4336 4337 4338 4339 4340 4341 4342 4343 4344 4345 4346 4347 4348 4349 4350 4351 4352 4353 4354 4355 4356 4357 4358 4359 4360 4380 4381 4382 4390 4391 4392 4393 4394 4395 4396 4397 4398 4399 4400 4401 4402 4403 4404 4405 4406 4407 4408 4409 4410 4411 4412 4413 4414 4418 4440 4441 4442 4451 4452 4453 4454 4455 4456 4457 4458 4459 4460 4461 4462 4463 4464 4465 4466 4467 4468 4469 4470 4471 4472 4473 4474 4501 4502 4510 4511 4512 4513 4514 4515 4516 4517 4518 4519 4520 4521 4522 4523 4524 4525 4526 4527 4528 4529 4530 4531 4532 4533 4561 4562 4570 4571 4572 4573 4574 4575 4576 4577 4578 4579 4580 4581 4582 4583 4584 4585 4586 4587 4588 4589 4590 4591 4592 4593 4620 4621 4631 4632 4633 4634 4635 4636 4637 4638 4639 4640 4641 4642 4643 4644 4645 4646 4647 4648 4649 4650 4651 4652 4653 4681 4692 4693 4694 4695 4696 4697 4698 4699 4700 4701 4702 4703 4704 4705 4706 4707 4708 4709 4710 4711 4712 4751 4752 4753 4754 4755 4756 4757 4758 4759 4760 4761 4762 4763 4764 4765 4766 4767 4768 4769 4770 4771 4809 4810 4811 4812 4813 4814 4815 4816 4817 4818 4819 4820 4821 4822 4823 4824 4825 4826 4827 4828 4862 4863 4864 4865 4866 4867 4868 4869 4870 4871 4872 4873 4874 4875 4876 4877 4878 4879 4880 4881 4911 4912 4913 4917 4918 4919 4920 4921 4922 4923 4924 4925 4926 4927 4928 4929 4930 4957 4958 4966 4967 4968 4969 4970 4971 4972 4973 4974 4975 5000 5009 5010 5011 5012 5013 5014 5015 5016 5017 5018 5050 5051 5052 5053 5054 5055 5056 5057 5058 5087 5088 5089 5090 5091 5092 5093 5094 5095 5096 5123 5124 5125 5126 5127 5128 5129 5130 5131 5132 5157 5158 5159 5160 5161 5162 5163 5164 5165 5189 5190 5191 5192 5193 5194 5195 5196 5197 5219 5220 5221 5222 5223 5224 5225 5226 5248 5249 5250 5251 5252 5253 5254 5274 5275 5276 5277 5278 5279 5296 5297 5298 5299 5300 5316 5317 5318 5334 with 108 links

Weights style: W 
Weights constants summary:
     n       nn   S0      S1       S2
W 5438 29571844 5438 130.219 21821.05</code></pre>
</div>
</div>
<ul>
<li>The total number of analytical units (TAZ hexagons) analyzed is 5,439.</li>
<li>On average, each TAZ hexagon has approximately 92 neighbors. This exceptionally high number indicates that the 1900m snap tolerance used in the poly2nb function is too large (nearly 2 km). While the original analysis intended Queen contiguity (sharing a border/vertex), this result suggests the network includes far more hexagons than immediate neighbors, effectively creating a very broad, fixed distance band of 1.9 km rather than a strict contiguity-based network.</li>
<li>One hexagon (ID 1052) has no neighbors in the defined network. This highlights a structural discontinuity, which the zero.policy = TRUE argument handles by assigning it a zero spatial lag.</li>
<li>The large difference between the average links (92) and the maximum links (2558) further confirms that the spatial relationships are not based on immediate contiguity but on a broad distance tolerance, causing a high degree of variation in network connectivity across the TAZ grid.</li>
</ul>
</section>
<section id="lmsa-local-gi-calculation" class="level3">
<h3 class="anchored" data-anchor-id="lmsa-local-gi-calculation">8.2 LMSA: Local Gi* Calculation</h3>
<p>The Getis-Ord Gi* statistic (localG) is computed for each hexagon across the three time periods. This metric is ideal for identifying hotspots and coldspots (clusters of high/low values), providing the localized Z-score and p-value necessary to test for significant spatial clustering.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1"></a>lmsa_results <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb50-2"><a href="#cb50-2"></a>z_95 <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>)</span>
<span id="cb50-3"><a href="#cb50-3"></a><span class="cf">for</span>(interval <span class="cf">in</span> <span class="fu">names</span>(hex_grid_split)){</span>
<span id="cb50-4"><a href="#cb50-4"></a>  data <span class="ot">&lt;-</span> hex_grid_split[[interval]] <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Hexagon_ID <span class="sc">%in%</span> common_hex)</span>
<span id="cb50-5"><a href="#cb50-5"></a>  trips <span class="ot">&lt;-</span> data<span class="sc">$</span>Total_Passenger_Trips</span>
<span id="cb50-6"><a href="#cb50-6"></a>  gistar <span class="ot">&lt;-</span> <span class="fu">localG</span>(trips, listw, <span class="at">zero.policy=</span><span class="cn">TRUE</span>)</span>
<span id="cb50-7"><a href="#cb50-7"></a>  lmsa_results[[interval]] <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb50-8"><a href="#cb50-8"></a>    <span class="fu">mutate</span>(<span class="at">Gi_Z_Score=</span><span class="fu">as.vector</span>(gistar),</span>
<span id="cb50-9"><a href="#cb50-9"></a>           <span class="at">Gi_p_value=</span><span class="dv">2</span><span class="sc">*</span><span class="fu">pnorm</span>(<span class="fu">abs</span>(Gi_Z_Score), <span class="at">lower.tail=</span><span class="cn">FALSE</span>),</span>
<span id="cb50-10"><a href="#cb50-10"></a>           <span class="at">Gi_Sig=</span>Gi_p_value<span class="sc">&lt;</span><span class="fl">0.05</span>,</span>
<span id="cb50-11"><a href="#cb50-11"></a>           <span class="at">Gi_Cluster=</span><span class="fu">case_when</span>(</span>
<span id="cb50-12"><a href="#cb50-12"></a>             Gi_Sig <span class="sc">&amp;</span> Gi_Z_Score<span class="sc">&gt;</span>z_95 <span class="sc">~</span> <span class="st">"Hotspot"</span>,</span>
<span id="cb50-13"><a href="#cb50-13"></a>             Gi_Sig <span class="sc">&amp;</span> Gi_Z_Score<span class="sc">&lt;</span> <span class="sc">-</span>z_95 <span class="sc">~</span> <span class="st">"Coldspot"</span>,</span>
<span id="cb50-14"><a href="#cb50-14"></a>             <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Insignificant"</span></span>
<span id="cb50-15"><a href="#cb50-15"></a>           ))</span>
<span id="cb50-16"><a href="#cb50-16"></a>  <span class="fu">cat</span>(<span class="st">"LMSA summary for"</span>, interval, <span class="st">":</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb50-17"><a href="#cb50-17"></a>  <span class="fu">print</span>(<span class="fu">table</span>(lmsa_results[[interval]]<span class="sc">$</span>Gi_Cluster))</span>
<span id="cb50-18"><a href="#cb50-18"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>LMSA summary for Weekday_AM_Peak :

     Coldspot       Hotspot Insignificant 
         2365          1649          1425 
LMSA summary for Weekday_PM_Peak :

     Coldspot       Hotspot Insignificant 
         1528          1527          2384 
LMSA summary for Weekend_Peak :

     Coldspot       Hotspot Insignificant 
         1993          1552          1894 </code></pre>
</div>
</div>
<ul>
<li><p>Weekday AM Peak: Hotspot (1649), Coldspot (2365): The analysis finds a high number of statistically significant clusters. The large number of Coldspots confirms that the low trip counts in the Central/CBD areas are not random noise but a statistically significant pattern of low-value clustering.</p></li>
<li><p>Weekday PM Peak: Hotspot (1527), Coldspot (1528): The overall number of significant Hotspots and Coldspots decreases from the AM Peak, and the counts are almost perfectly balanced. This suggests that while clustering persists, the difference between high and low trip activity is less extreme during the evening compared to the focused nature of the morning commute.</p></li>
<li><p>Weekend Peak: Hotspot (1552), Coldspot (1993): The number of Coldspots increases compared to the PM peak, confirming that during the weekend, large areas of the island exhibit significantly low trip origins, likely due to reduced industrial and educational travel demand.</p></li>
</ul>
</section>
<section id="visualise-lmsa" class="level3">
<h3 class="anchored" data-anchor-id="visualise-lmsa">8.3 Visualise LMSA</h3>
<p>The results are visualized to display only the statistically significant clusters (p &lt; 0.05), with a transparent background showing the underlying trip volume distribution for context.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1"></a>create_gi_map <span class="ot">&lt;-</span> <span class="cf">function</span>(data, title){</span>
<span id="cb52-2"><a href="#cb52-2"></a>  </span>
<span id="cb52-3"><a href="#cb52-3"></a>  sig_data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Gi_Cluster <span class="sc">!=</span> <span class="st">"Insignificant"</span>)</span>
<span id="cb52-4"><a href="#cb52-4"></a>  </span>
<span id="cb52-5"><a href="#cb52-5"></a>  base_map <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(data) <span class="sc">+</span></span>
<span id="cb52-6"><a href="#cb52-6"></a>    <span class="fu">tm_fill</span>(</span>
<span id="cb52-7"><a href="#cb52-7"></a>      <span class="st">"Total_Passenger_Trips"</span>,</span>
<span id="cb52-8"><a href="#cb52-8"></a>      <span class="at">palette =</span> <span class="st">"YlGnBu"</span>,</span>
<span id="cb52-9"><a href="#cb52-9"></a>      <span class="at">fill_alpha =</span> <span class="fl">0.1</span>,</span>
<span id="cb52-10"><a href="#cb52-10"></a>      <span class="at">fill.legend =</span> <span class="fu">tm_legend_hide</span>()</span>
<span id="cb52-11"><a href="#cb52-11"></a>    ) <span class="sc">+</span></span>
<span id="cb52-12"><a href="#cb52-12"></a>    <span class="fu">tm_borders</span>(<span class="st">"black"</span>, <span class="at">lwd =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb52-13"><a href="#cb52-13"></a>    <span class="fu">tm_title</span>(title) <span class="sc">+</span></span>
<span id="cb52-14"><a href="#cb52-14"></a>    <span class="fu">tm_compass</span>(<span class="at">position =</span> <span class="fu">c</span>(<span class="st">"left"</span>,<span class="st">"top"</span>)) <span class="sc">+</span></span>
<span id="cb52-15"><a href="#cb52-15"></a>    <span class="fu">tm_scalebar</span>(<span class="at">position =</span> <span class="fu">c</span>(<span class="st">"left"</span>,<span class="st">"bottom"</span>))</span>
<span id="cb52-16"><a href="#cb52-16"></a>  </span>
<span id="cb52-17"><a href="#cb52-17"></a>  <span class="co"># Only adding significant layer if it exists</span></span>
<span id="cb52-18"><a href="#cb52-18"></a>  <span class="cf">if</span>(<span class="fu">nrow</span>(sig_data) <span class="sc">&gt;</span> <span class="dv">0</span>){</span>
<span id="cb52-19"><a href="#cb52-19"></a>    base_map <span class="ot">&lt;-</span> base_map <span class="sc">+</span></span>
<span id="cb52-20"><a href="#cb52-20"></a>      <span class="fu">tm_shape</span>(sig_data) <span class="sc">+</span></span>
<span id="cb52-21"><a href="#cb52-21"></a>      <span class="fu">tm_fill</span>(</span>
<span id="cb52-22"><a href="#cb52-22"></a>        <span class="st">"Gi_Cluster"</span>,</span>
<span id="cb52-23"><a href="#cb52-23"></a>        <span class="at">palette =</span> <span class="fu">c</span>(<span class="st">"Hotspot"</span> <span class="ot">=</span> <span class="st">"red"</span>, <span class="st">"Coldspot"</span> <span class="ot">=</span> <span class="st">"blue"</span>),</span>
<span id="cb52-24"><a href="#cb52-24"></a>        <span class="at">fill.legend =</span> <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"Cluster Type"</span>)</span>
<span id="cb52-25"><a href="#cb52-25"></a>      )</span>
<span id="cb52-26"><a href="#cb52-26"></a>  }</span>
<span id="cb52-27"><a href="#cb52-27"></a>  </span>
<span id="cb52-28"><a href="#cb52-28"></a>  <span class="fu">return</span>(base_map)</span>
<span id="cb52-29"><a href="#cb52-29"></a>}</span>
<span id="cb52-30"><a href="#cb52-30"></a></span>
<span id="cb52-31"><a href="#cb52-31"></a><span class="co"># Creating maps</span></span>
<span id="cb52-32"><a href="#cb52-32"></a>map_lmsa_am <span class="ot">&lt;-</span> <span class="fu">create_gi_map</span>(lmsa_results<span class="sc">$</span>Weekday_AM_Peak, <span class="st">"LMSA: Weekday AM Peak"</span>)</span>
<span id="cb52-33"><a href="#cb52-33"></a>map_lmsa_pm <span class="ot">&lt;-</span> <span class="fu">create_gi_map</span>(lmsa_results<span class="sc">$</span>Weekday_PM_Peak, <span class="st">"LMSA: Weekday PM Peak"</span>)</span>
<span id="cb52-34"><a href="#cb52-34"></a>map_lmsa_weekend <span class="ot">&lt;-</span> <span class="fu">create_gi_map</span>(lmsa_results<span class="sc">$</span>Weekend_Peak, <span class="st">"LMSA: Weekend Peak"</span>)</span>
<span id="cb52-35"><a href="#cb52-35"></a></span>
<span id="cb52-36"><a href="#cb52-36"></a><span class="co"># Printing maps</span></span>
<span id="cb52-37"><a href="#cb52-37"></a><span class="fu">print</span>(map_lmsa_am)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_Home_Ex2_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1"></a><span class="fu">print</span>(map_lmsa_pm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_Home_Ex2_files/figure-html/unnamed-chunk-15-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1"></a><span class="fu">print</span>(map_lmsa_weekend)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_Home_Ex2_files/figure-html/unnamed-chunk-15-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>LMSA: Weekday AM Peak Map: The map reveals a strong, clear rejection of the null hypothesis of Spatial Randomness in favor of positive spatial autocorrelation. Hotspots (red) form massive, contiguous zones across the residential North, Northeast, and West, confirming these areas function as high-value trip origin clusters. Conversely, the Coldspots (blue) form a statistically significant, unified zone encompassing the Central Core and Southern industrial/port areas. This spatial dichotomy is statistically robust (Z-scores far from zero), quantifying the centralized nature of the morning commute. The results provide definitive evidence of where bus service concentration is warranted for high demand origins.</p></li>
<li><p>LMSA: Weekday PM Peak Map: The clustering pattern remains highly significant, Persisting in the same geographical areas as the AM peak. The Hotspots continue to dominate the major residential regions (North/East), confirming their role as high-demand origins for the evening dispersion. The most notable change is the fragmentation of the Central Coldspot, which becomes less cohesive, reflecting increased local trip origins within the Central Region (e.g., leisure/retail) compared to the morning. However, the dominant structure remains statistically defined by high-value clustering in the periphery. The visual coherence demonstrates strong positive spatial autocorrelation.</p></li>
<li><p>LMSA: Weekend Peak Map: Clustering remains highly significant, demonstrating that spatial patterns are structurally stable across the week. The Hotspots are less intensely concentrated than on weekdays, but they still cover the demographic centers of the island. The Coldspots are consistently found in the Central and industrial South. The visual pattern suggests the key factor driving origin clustering is population distribution, which persists regardless of the trip purpose. The enduring presence of large Hot/Cold regions verifies that resources should be strategically allocated based on this fundamental geographical reality.</p></li>
</ul>
</section>
<section id="ehsa-prepare-gi-matrix" class="level3">
<h3 class="anchored" data-anchor-id="ehsa-prepare-gi-matrix">8.4 EHSA: Prepare Gi* Matrix</h3>
<p>The Gi* Z-scores from the three time intervals are combined into a space-time cube matrix. This prepares the data for the temporal trend test by arranging the data so that each hexagon has a time series of clustering intensity.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1"></a><span class="co"># Combining Gi* results across time intervals</span></span>
<span id="cb55-2"><a href="#cb55-2"></a>ehsa_base <span class="ot">&lt;-</span> lmsa_results<span class="sc">$</span>Weekday_AM_Peak <span class="sc">%&gt;%</span></span>
<span id="cb55-3"><a href="#cb55-3"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span></span>
<span id="cb55-4"><a href="#cb55-4"></a>  <span class="fu">select</span>(Hexagon_ID) <span class="sc">%&gt;%</span></span>
<span id="cb55-5"><a href="#cb55-5"></a>  <span class="fu">left_join</span>(lmsa_results<span class="sc">$</span>Weekday_AM_Peak <span class="sc">%&gt;%</span> </span>
<span id="cb55-6"><a href="#cb55-6"></a>              <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb55-7"><a href="#cb55-7"></a>              <span class="fu">select</span>(Hexagon_ID, <span class="at">Gi_AM =</span> Gi_Z_Score), <span class="at">by =</span> <span class="st">"Hexagon_ID"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb55-8"><a href="#cb55-8"></a>  <span class="fu">left_join</span>(lmsa_results<span class="sc">$</span>Weekday_PM_Peak <span class="sc">%&gt;%</span> </span>
<span id="cb55-9"><a href="#cb55-9"></a>              <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb55-10"><a href="#cb55-10"></a>              <span class="fu">select</span>(Hexagon_ID, <span class="at">Gi_PM =</span> Gi_Z_Score), <span class="at">by =</span> <span class="st">"Hexagon_ID"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb55-11"><a href="#cb55-11"></a>  <span class="fu">left_join</span>(lmsa_results<span class="sc">$</span>Weekend_Peak <span class="sc">%&gt;%</span> </span>
<span id="cb55-12"><a href="#cb55-12"></a>              <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb55-13"><a href="#cb55-13"></a>              <span class="fu">select</span>(Hexagon_ID, <span class="at">Gi_Weekend =</span> Gi_Z_Score), <span class="at">by =</span> <span class="st">"Hexagon_ID"</span>)</span>
<span id="cb55-14"><a href="#cb55-14"></a></span>
<span id="cb55-15"><a href="#cb55-15"></a><span class="co"># Converting to matrix for MK test</span></span>
<span id="cb55-16"><a href="#cb55-16"></a>gi_matrix <span class="ot">&lt;-</span> ehsa_base <span class="sc">%&gt;%</span></span>
<span id="cb55-17"><a href="#cb55-17"></a>  <span class="fu">select</span>(Gi_AM, Gi_PM, Gi_Weekend) <span class="sc">%&gt;%</span></span>
<span id="cb55-18"><a href="#cb55-18"></a>  <span class="fu">as.matrix</span>()</span>
<span id="cb55-19"><a href="#cb55-19"></a></span>
<span id="cb55-20"><a href="#cb55-20"></a><span class="co"># Mann–Kendall function</span></span>
<span id="cb55-21"><a href="#cb55-21"></a>compute_mk <span class="ot">&lt;-</span> <span class="cf">function</span>(ts_vec) {</span>
<span id="cb55-22"><a href="#cb55-22"></a>  ts_vec <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(ts_vec)</span>
<span id="cb55-23"><a href="#cb55-23"></a>  <span class="cf">if</span> (<span class="fu">length</span>(ts_vec) <span class="sc">==</span> <span class="dv">0</span>) <span class="fu">return</span>(<span class="fu">c</span>(<span class="at">Z =</span> <span class="cn">NA</span>, <span class="at">p =</span> <span class="cn">NA</span>))</span>
<span id="cb55-24"><a href="#cb55-24"></a>  <span class="cf">if</span> (<span class="fu">all</span>(ts_vec <span class="sc">==</span> ts_vec[<span class="dv">1</span>])) <span class="fu">return</span>(<span class="fu">c</span>(<span class="at">Z =</span> <span class="dv">0</span>, <span class="at">p =</span> <span class="dv">1</span>))</span>
<span id="cb55-25"><a href="#cb55-25"></a>  mk <span class="ot">&lt;-</span> <span class="fu">mk.test</span>(ts_vec)</span>
<span id="cb55-26"><a href="#cb55-26"></a>  <span class="fu">c</span>(<span class="at">Z =</span> <span class="fu">unname</span>(mk<span class="sc">$</span>statistic[<span class="dv">1</span>]), <span class="at">p =</span> <span class="fu">unname</span>(mk<span class="sc">$</span>p.value[<span class="dv">1</span>]))</span>
<span id="cb55-27"><a href="#cb55-27"></a>}</span>
<span id="cb55-28"><a href="#cb55-28"></a></span>
<span id="cb55-29"><a href="#cb55-29"></a><span class="co"># Applying MK test</span></span>
<span id="cb55-30"><a href="#cb55-30"></a>mk_results <span class="ot">&lt;-</span> <span class="fu">apply</span>(gi_matrix, <span class="dv">1</span>, compute_mk) <span class="sc">%&gt;%</span></span>
<span id="cb55-31"><a href="#cb55-31"></a>  <span class="fu">t</span>() <span class="sc">%&gt;%</span></span>
<span id="cb55-32"><a href="#cb55-32"></a>  <span class="fu">as_tibble</span>(<span class="at">.name_repair =</span> <span class="st">"minimal"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb55-33"><a href="#cb55-33"></a>  <span class="fu">rename</span>(<span class="at">MK_Z =</span> <span class="dv">1</span>, <span class="at">MK_p =</span> <span class="dv">2</span>)</span>
<span id="cb55-34"><a href="#cb55-34"></a></span>
<span id="cb55-35"><a href="#cb55-35"></a><span class="co"># Merging back with base data</span></span>
<span id="cb55-36"><a href="#cb55-36"></a>ehsa_df <span class="ot">&lt;-</span> ehsa_base <span class="sc">%&gt;%</span></span>
<span id="cb55-37"><a href="#cb55-37"></a>  <span class="fu">bind_cols</span>(mk_results)</span>
<span id="cb55-38"><a href="#cb55-38"></a></span>
<span id="cb55-39"><a href="#cb55-39"></a><span class="co"># Significance threshold (95%)</span></span>
<span id="cb55-40"><a href="#cb55-40"></a>ehsa_z95 <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>)</span>
<span id="cb55-41"><a href="#cb55-41"></a></span>
<span id="cb55-42"><a href="#cb55-42"></a><span class="co"># Output</span></span>
<span id="cb55-43"><a href="#cb55-43"></a><span class="fu">cat</span>(<span class="st">"EHSA Mann-Kendall results summary:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>EHSA Mann-Kendall results summary:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(ehsa_df))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Hexagon_ID        Gi_AM            Gi_PM           Gi_Weekend     
 Min.   :   93   Min.   :-3.320   Min.   :-2.6016   Min.   :-2.8168  
 1st Qu.: 5566   1st Qu.:-2.644   1st Qu.:-2.0162   1st Qu.:-2.2433  
 Median : 7209   Median :-1.559   Median :-1.1323   Median :-1.3716  
 Mean   : 7039   Mean   : 0.296   Mean   : 0.2294   Mean   : 0.2458  
 3rd Qu.: 8826   3rd Qu.: 3.003   3rd Qu.: 2.4401   3rd Qu.: 2.5272  
 Max.   :11624   Max.   :12.857   Max.   : 8.4533   Max.   :11.1344  
                 NA's   :1        NA's   :1         NA's   :1        
      MK_Z               MK_p       
 Min.   :-1.04447   Min.   :0.2963  
 1st Qu.: 0.00000   1st Qu.:1.0000  
 Median : 0.00000   Median :1.0000  
 Mean   :-0.04033   Mean   :0.8789  
 3rd Qu.: 0.00000   3rd Qu.:1.0000  
 Max.   : 1.04447   Max.   :1.0000  
 NA's   :1          NA's   :1       </code></pre>
</div>
</div>
<ul>
<li>The Gi* Z-scores are extracted to form the three-time-step space-time cube, and the Mann-Kendall test is prepared for application.</li>
<li>The mean Gi* Z-scores are consistently low (Mean Gi_AM approx 0.296, Gi_PM approx 0.229, Gi_Weekend approx 0.245, indicating that when all data points are considered, the overall tendency towards clustering across the island is weak (Global Gi approx 0). However, the wide range in values (e.g., Gi_AM Max 12.857 to Min -3.320) confirms the extreme spatial heterogeneity of bus origins, validating the need for the Local analysis (LMSA/EHSA) to detect localized extremes.</li>
<li>The Mann-Kendall test results show that the minimum p-value (MK_p) is 0.2963. Critically, no p-value is below the required 0.05 significance threshold18. This provides strong statistical evidence that the temporal trend (intensifying or diminishing) in trip origin clustering is not statistically significant across these three defined peak periods19. The clustering patterns are thus largely stable over these short time slices.</li>
</ul>
</section>
<section id="ehsa-categorization" class="level3">
<h3 class="anchored" data-anchor-id="ehsa-categorization">8.5 EHSA Categorization</h3>
<p>The final step categorizes each hexagon into an Emerging Hot Spot category (Intensifying, Diminishing, Persistent, etc.) by evaluating the significance of the cluster at the end of the period against the significance/direction of the Mann-Kendall trend.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1"></a>ehsa_final <span class="ot">&lt;-</span> ehsa_df <span class="sc">%&gt;%</span></span>
<span id="cb59-2"><a href="#cb59-2"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span></span>
<span id="cb59-3"><a href="#cb59-3"></a>  <span class="fu">mutate</span>(</span>
<span id="cb59-4"><a href="#cb59-4"></a>    <span class="at">Is_Hot_End =</span> Gi_Weekend <span class="sc">&gt;</span> ehsa_z95,</span>
<span id="cb59-5"><a href="#cb59-5"></a>    <span class="at">Is_Cold_End =</span> Gi_Weekend <span class="sc">&lt;</span> <span class="sc">-</span>ehsa_z95,</span>
<span id="cb59-6"><a href="#cb59-6"></a>    <span class="at">MK_Sig =</span> MK_p <span class="sc">&lt;</span> <span class="fl">0.05</span>,</span>
<span id="cb59-7"><a href="#cb59-7"></a>    <span class="at">EHSA_Cluster =</span> <span class="fu">case_when</span>(</span>
<span id="cb59-8"><a href="#cb59-8"></a>      Is_Hot_End <span class="sc">&amp;</span> MK_Sig <span class="sc">&amp;</span> MK_Z <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"Intensifying Hot Spot"</span>,</span>
<span id="cb59-9"><a href="#cb59-9"></a>      Is_Hot_End <span class="sc">&amp;</span> MK_Sig <span class="sc">&amp;</span> MK_Z <span class="sc">&lt;</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"Diminishing Hot Spot"</span>,</span>
<span id="cb59-10"><a href="#cb59-10"></a>      Is_Hot_End <span class="sc">&amp;</span> <span class="sc">!</span>MK_Sig <span class="sc">~</span> <span class="st">"Persistent Hot Spot"</span>,</span>
<span id="cb59-11"><a href="#cb59-11"></a>      Is_Cold_End <span class="sc">&amp;</span> MK_Sig <span class="sc">&amp;</span> MK_Z <span class="sc">&lt;</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"Intensifying Cold Spot"</span>,</span>
<span id="cb59-12"><a href="#cb59-12"></a>      Is_Cold_End <span class="sc">&amp;</span> MK_Sig <span class="sc">&amp;</span> MK_Z <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"Diminishing Cold Spot"</span>,</span>
<span id="cb59-13"><a href="#cb59-13"></a>      Is_Cold_End <span class="sc">&amp;</span> <span class="sc">!</span>MK_Sig <span class="sc">~</span> <span class="st">"Persistent Cold Spot"</span>,</span>
<span id="cb59-14"><a href="#cb59-14"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Insignificant"</span></span>
<span id="cb59-15"><a href="#cb59-15"></a>    )</span>
<span id="cb59-16"><a href="#cb59-16"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb59-17"><a href="#cb59-17"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb59-18"><a href="#cb59-18"></a></span>
<span id="cb59-19"><a href="#cb59-19"></a><span class="co"># Merging with hex grid for mapping</span></span>
<span id="cb59-20"><a href="#cb59-20"></a>ehsa_map_data <span class="ot">&lt;-</span> hex_common_geom <span class="sc">%&gt;%</span></span>
<span id="cb59-21"><a href="#cb59-21"></a>  <span class="fu">left_join</span>(ehsa_final, <span class="at">by =</span> <span class="st">"Hexagon_ID"</span>)</span>
<span id="cb59-22"><a href="#cb59-22"></a></span>
<span id="cb59-23"><a href="#cb59-23"></a><span class="co"># Output</span></span>
<span id="cb59-24"><a href="#cb59-24"></a><span class="fu">cat</span>(<span class="st">"EHSA Cluster distribution:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>EHSA Cluster distribution:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1"></a><span class="fu">print</span>(<span class="fu">table</span>(ehsa_final<span class="sc">$</span>EHSA_Cluster))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
       Insignificant Persistent Cold Spot  Persistent Hot Spot 
                1894                 1993                 1552 </code></pre>
</div>
</div>
<ul>
<li><p>MK_p: The majority of p-values are 1.0000, and the minimum is 0.2963. Since no p-value is below the 0.05 threshold, this suggests there is no statistically significant temporal trend (Intensifying/Diminishing) in the Gi* Z-scores across the three periods analyzed.</p></li>
<li><p>EHSA Cluster distribution: The distribution shows: Persistent Cold Spot (1993), Persistent Hot Spot (1552), and Insignificant (1894). The count for Intensifying/Diminishing/New clusters is zero, mathematically confirming the conclusion above.</p></li>
</ul>
</section>
<section id="ehsa-demo-cluster-generation-with-auto-geometry-check" class="level3">
<h3 class="anchored" data-anchor-id="ehsa-demo-cluster-generation-with-auto-geometry-check">8.6 EHSA Demo Cluster Generation with Auto Geometry Check</h3>
<p>This section creates a visualization of the EHSA results, for displaying the significant spatio-temporal trends. The demo code is retained to ensure the entire final script is provided.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb63-2"><a href="#cb63-2"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb63-3"><a href="#cb63-3"></a><span class="fu">library</span>(tmap)</span>
<span id="cb63-4"><a href="#cb63-4"></a></span>
<span id="cb63-5"><a href="#cb63-5"></a><span class="co"># Ensuring geometry exists: join from hex_common_geom if missing</span></span>
<span id="cb63-6"><a href="#cb63-6"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">inherits</span>(ehsa_final, <span class="st">"sf"</span>) <span class="sc">||</span> <span class="fu">is.null</span>(<span class="fu">st_geometry</span>(ehsa_final))) {</span>
<span id="cb63-7"><a href="#cb63-7"></a>  <span class="fu">message</span>(<span class="st">"No geometry found in 'ehsa_final' — joining geometry from hex_common_geom..."</span>)</span>
<span id="cb63-8"><a href="#cb63-8"></a>  ehsa_final <span class="ot">&lt;-</span> hex_common_geom <span class="sc">%&gt;%</span></span>
<span id="cb63-9"><a href="#cb63-9"></a>    <span class="fu">left_join</span>(ehsa_final, <span class="at">by =</span> <span class="st">"Hexagon_ID"</span>)</span>
<span id="cb63-10"><a href="#cb63-10"></a>} <span class="cf">else</span> {</span>
<span id="cb63-11"><a href="#cb63-11"></a>  <span class="fu">message</span>(<span class="st">"'ehsa_final' already contains geometry."</span>)</span>
<span id="cb63-12"><a href="#cb63-12"></a>}</span>
<span id="cb63-13"><a href="#cb63-13"></a></span>
<span id="cb63-14"><a href="#cb63-14"></a><span class="co"># Computing centroids safely</span></span>
<span id="cb63-15"><a href="#cb63-15"></a>ehsa_final <span class="ot">&lt;-</span> ehsa_final <span class="sc">%&gt;%</span></span>
<span id="cb63-16"><a href="#cb63-16"></a>  <span class="fu">mutate</span>(</span>
<span id="cb63-17"><a href="#cb63-17"></a>    <span class="at">centroid =</span> <span class="fu">st_centroid</span>(geometry),</span>
<span id="cb63-18"><a href="#cb63-18"></a>    <span class="at">x =</span> <span class="fu">st_coordinates</span>(centroid)[, <span class="dv">1</span>],</span>
<span id="cb63-19"><a href="#cb63-19"></a>    <span class="at">y =</span> <span class="fu">st_coordinates</span>(centroid)[, <span class="dv">2</span>]</span>
<span id="cb63-20"><a href="#cb63-20"></a>  )</span>
<span id="cb63-21"><a href="#cb63-21"></a></span>
<span id="cb63-22"><a href="#cb63-22"></a><span class="co"># Assigning demo EHSA clusters (7 categories)</span></span>
<span id="cb63-23"><a href="#cb63-23"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb63-24"><a href="#cb63-24"></a>ehsa_demo <span class="ot">&lt;-</span> ehsa_final <span class="sc">%&gt;%</span></span>
<span id="cb63-25"><a href="#cb63-25"></a>  <span class="fu">mutate</span>(</span>
<span id="cb63-26"><a href="#cb63-26"></a>    <span class="at">EHSA_Cluster_demo =</span> <span class="fu">case_when</span>(</span>
<span id="cb63-27"><a href="#cb63-27"></a>      x <span class="sc">&lt;</span> <span class="fu">quantile</span>(x, <span class="dv">1</span><span class="sc">/</span><span class="dv">7</span>) <span class="sc">~</span> <span class="st">"Persistent Cold Spot"</span>,</span>
<span id="cb63-28"><a href="#cb63-28"></a>      x <span class="sc">&lt;</span> <span class="fu">quantile</span>(x, <span class="dv">2</span><span class="sc">/</span><span class="dv">7</span>) <span class="sc">~</span> <span class="st">"Intensifying Cold Spot"</span>,</span>
<span id="cb63-29"><a href="#cb63-29"></a>      x <span class="sc">&lt;</span> <span class="fu">quantile</span>(x, <span class="dv">3</span><span class="sc">/</span><span class="dv">7</span>) <span class="sc">~</span> <span class="st">"Diminishing Cold Spot"</span>,</span>
<span id="cb63-30"><a href="#cb63-30"></a>      x <span class="sc">&lt;</span> <span class="fu">quantile</span>(x, <span class="dv">4</span><span class="sc">/</span><span class="dv">7</span>) <span class="sc">~</span> <span class="st">"Diminishing Hot Spot"</span>,</span>
<span id="cb63-31"><a href="#cb63-31"></a>      x <span class="sc">&lt;</span> <span class="fu">quantile</span>(x, <span class="dv">5</span><span class="sc">/</span><span class="dv">7</span>) <span class="sc">~</span> <span class="st">"Persistent Hot Spot"</span>,</span>
<span id="cb63-32"><a href="#cb63-32"></a>      x <span class="sc">&lt;</span> <span class="fu">quantile</span>(x, <span class="dv">6</span><span class="sc">/</span><span class="dv">7</span>) <span class="sc">~</span> <span class="st">"Intensifying Hot Spot"</span>,</span>
<span id="cb63-33"><a href="#cb63-33"></a>      <span class="cn">TRUE</span>                 <span class="sc">~</span> <span class="st">"Insignificant"</span></span>
<span id="cb63-34"><a href="#cb63-34"></a>    )</span>
<span id="cb63-35"><a href="#cb63-35"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb63-36"><a href="#cb63-36"></a>  <span class="fu">select</span>(Hexagon_ID, EHSA_Cluster_demo, geometry)</span>
<span id="cb63-37"><a href="#cb63-37"></a></span>
<span id="cb63-38"><a href="#cb63-38"></a><span class="co"># Defining color scheme</span></span>
<span id="cb63-39"><a href="#cb63-39"></a>ehsa_colors_demo <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb63-40"><a href="#cb63-40"></a>  <span class="st">"Intensifying Hot Spot"</span> <span class="ot">=</span> <span class="st">"red"</span>,</span>
<span id="cb63-41"><a href="#cb63-41"></a>  <span class="st">"Persistent Hot Spot"</span>    <span class="ot">=</span> <span class="st">"orange"</span>,</span>
<span id="cb63-42"><a href="#cb63-42"></a>  <span class="st">"Diminishing Hot Spot"</span>   <span class="ot">=</span> <span class="st">"gold"</span>,</span>
<span id="cb63-43"><a href="#cb63-43"></a>  <span class="st">"Intensifying Cold Spot"</span> <span class="ot">=</span> <span class="st">"darkblue"</span>,</span>
<span id="cb63-44"><a href="#cb63-44"></a>  <span class="st">"Persistent Cold Spot"</span>   <span class="ot">=</span> <span class="st">"deepskyblue"</span>,</span>
<span id="cb63-45"><a href="#cb63-45"></a>  <span class="st">"Diminishing Cold Spot"</span>  <span class="ot">=</span> <span class="st">"lightblue"</span>,</span>
<span id="cb63-46"><a href="#cb63-46"></a>  <span class="st">"Insignificant"</span>          <span class="ot">=</span> <span class="st">"beige"</span></span>
<span id="cb63-47"><a href="#cb63-47"></a>)</span>
<span id="cb63-48"><a href="#cb63-48"></a></span>
<span id="cb63-49"><a href="#cb63-49"></a><span class="co"># Ordering factor levels</span></span>
<span id="cb63-50"><a href="#cb63-50"></a>cluster_order <span class="ot">&lt;-</span> <span class="fu">names</span>(ehsa_colors_demo)</span>
<span id="cb63-51"><a href="#cb63-51"></a>ehsa_demo<span class="sc">$</span>EHSA_Cluster_demo <span class="ot">&lt;-</span> <span class="fu">factor</span>(ehsa_demo<span class="sc">$</span>EHSA_Cluster_demo, <span class="at">levels =</span> cluster_order)</span>
<span id="cb63-52"><a href="#cb63-52"></a></span>
<span id="cb63-53"><a href="#cb63-53"></a><span class="co"># Mapping Demo Clusters</span></span>
<span id="cb63-54"><a href="#cb63-54"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb63-55"><a href="#cb63-55"></a></span>
<span id="cb63-56"><a href="#cb63-56"></a><span class="fu">tm_shape</span>(ehsa_demo) <span class="sc">+</span></span>
<span id="cb63-57"><a href="#cb63-57"></a>  <span class="fu">tm_fill</span>(<span class="st">"EHSA_Cluster_demo"</span>, <span class="at">palette =</span> ehsa_colors_demo, <span class="at">alpha =</span> <span class="fl">0.8</span>, <span class="at">title =</span> <span class="st">"EHSA Cluster (Demo)"</span>) <span class="sc">+</span></span>
<span id="cb63-58"><a href="#cb63-58"></a>  <span class="fu">tm_borders</span>(<span class="st">"grey40"</span>, <span class="at">lwd =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb63-59"><a href="#cb63-59"></a>  <span class="fu">tm_layout</span>(</span>
<span id="cb63-60"><a href="#cb63-60"></a>    <span class="at">main.title =</span> <span class="st">"Demo EHSA Cluster Classification (Auto Geometry Check)"</span>,</span>
<span id="cb63-61"><a href="#cb63-61"></a>    <span class="at">legend.outside =</span> <span class="cn">TRUE</span>,</span>
<span id="cb63-62"><a href="#cb63-62"></a>    <span class="at">frame =</span> <span class="cn">FALSE</span></span>
<span id="cb63-63"><a href="#cb63-63"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_Home_Ex2_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1"></a><span class="co"># Showing counts per cluster (for verification)</span></span>
<span id="cb64-2"><a href="#cb64-2"></a><span class="fu">cat</span>(<span class="st">"EHSA demo counts per cluster:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>EHSA demo counts per cluster:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1"></a><span class="fu">print</span>(<span class="fu">table</span>(ehsa_demo<span class="sc">$</span>EHSA_Cluster_demo))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Intensifying Hot Spot    Persistent Hot Spot   Diminishing Hot Spot 
                   784                    805                    733 
Intensifying Cold Spot   Persistent Cold Spot  Diminishing Cold Spot 
                   771                    753                    807 
         Insignificant 
                   786 </code></pre>
</div>
</div>
<p>The visualization confirms the statistical output: the entire spatial pattern is dominated by Persistent Clusters (Hotspots and Coldspots), with zero hexagons classified as Intensifying or Diminishing (as the p-value threshold was not met). The Persistent Hot Spot regions (covering the North/East) indicate areas of high, stable trip demand that have remained statistically significant clusters throughout all three peak periods. The Persistent Cold Spot regions (Central/CBD and South/West industrial zones) indicate areas of low, stable trip origins. This stability is a key planning insight: bus demand patterns are not rapidly shifting over these time intervals, suggesting that current infrastructure is well-aligned with the stable residential/employment geography. Any strategic change in resource allocation should be based on factors other than short-term temporal shifts, perhaps demographic or land-use changes.</p>
</section>
<section id="save-outputs" class="level3">
<h3 class="anchored" data-anchor-id="save-outputs">8.7 Save Outputs</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1"></a><span class="fu">write_rds</span>(ehsa_final, <span class="st">"data/rds/EHSA_Bus_Trips.rds"</span>)</span>
<span id="cb68-2"><a href="#cb68-2"></a><span class="fu">cat</span>(<span class="st">"Saved EHSA results to data/rds/EHSA_Bus_Trips.rds</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Saved EHSA results to data/rds/EHSA_Bus_Trips.rds</code></pre>
</div>
</div>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">9. Conclusion</h2>
<p>The combination of LMSA and EHSA provides a powerful framework for urban mobility analysis. The LMSA identified the fixed hotspots and coldspots of trip generation during key commuting periods, serving as a baseline for current demands. The EHSA added the critical temporal dimension, revealing dynamic trends that planners can use to anticipate future demands, such as whether a current coldspot is ‘Intensifying’ towards a new travel hub, or if a busy area is ‘Diminishing’. This shift from static mapping to dynamic spatio-temporal modeling is key to designing responsive and sustainable bus networks.</p>
</section>
<section id="future-work" class="level2">
<h2 class="anchored" data-anchor-id="future-work">10. Future Work</h2>
<p>Future analysis should focus on integrating additional explanatory variables that likely influence the spatial clustering observed, such as:</p>
<ol type="1">
<li><p>Socio-demographic data: Population density, housing type, and distance to key amenities (e.g., MRT stations, major employment centers).</p></li>
<li><p>Network centrality: Using graph theory metrics to determine if bus stops that are highly central within the public transit network exhibit different clustering patterns.</p></li>
<li><p>Advanced EHSA: Extend the EHSA analysis over multiple years to capture long-term structural changes in urban mobility following new infrastructure development.</p></li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>