{
  "hash": "ecbc0e07bbd1a2c00de2a454c01fb3e2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"In class Exercise 7\"\nauthor: \"Sathvika Subramanian\"\ndate: \"Oct 18, 2025\"\ndate-modified: \"last-modified\"\nformat: html\nexecute:\n echo: true\n eval: true\n warning: false\n freeze: true\n---\n\n\n\n# Calibrating Hedonic Pricing Model for Private Highrise Property with GWR Method\n\n# 1.Getting Started\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(olsrr, corrplot, ggpubr, \n               sf, sfdep, GWmodel, tmap, \n               tidyverse, gtsummary,\n               performance, RColorBrewer,qqplotr)\n```\n:::\n\n\n\n# 2. Geospatial Data Wrangling\n\n## 2.1 Importing geospatial data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz = st_read(dsn = \"data/geospatial\", \n               layer = \"MP14_SUBZONE_WEB_PL\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `MP14_SUBZONE_WEB_PL' from data source \n  `C:\\Sathvika-7284\\ISSS626-geo\\Inclass_Ex\\In_class_Ex7\\data\\geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 323 features and 15 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33\nProjected CRS: SVY21\n```\n\n\n:::\n:::\n\n\n\n## 2.2 Updating CRS information\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz_svy21 <- st_transform(mpsz, 3414)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nst_crs(mpsz_svy21)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:3414 \n  wkt:\nPROJCRS[\"SVY21 / Singapore TM\",\n    BASEGEOGCRS[\"SVY21\",\n        DATUM[\"SVY21\",\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4757]],\n    CONVERSION[\"Singapore Transverse Mercator\",\n        METHOD[\"Transverse Mercator\",\n            ID[\"EPSG\",9807]],\n        PARAMETER[\"Latitude of natural origin\",1.36666666666667,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",103.833333333333,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"Scale factor at natural origin\",1,\n            SCALEUNIT[\"unity\",1],\n            ID[\"EPSG\",8805]],\n        PARAMETER[\"False easting\",28001.642,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",38744.572,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"northing (N)\",north,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"easting (E)\",east,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Cadastre, engineering survey, topographic mapping.\"],\n        AREA[\"Singapore - onshore and offshore.\"],\n        BBOX[1.13,103.59,1.47,104.07]],\n    ID[\"EPSG\",3414]]\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nst_bbox(mpsz_svy21)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     xmin      ymin      xmax      ymax \n 2667.538 15748.721 56396.440 50256.334 \n```\n\n\n:::\n:::\n\n\n\n# 3. Aspatial Data Wrangling\n\n## 3.1 Importing the aspatial data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncondo_resale = read_csv(\n  \"data/aspatial/Condo_resale_2015.csv\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(condo_resale)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,436\nColumns: 23\n$ LATITUDE             <dbl> 1.287145, 1.328698, 1.313727, 1.308563, 1.321437,…\n$ LONGITUDE            <dbl> 103.7802, 103.8123, 103.7971, 103.8247, 103.9505,…\n$ POSTCODE             <dbl> 118635, 288420, 267833, 258380, 467169, 466472, 3…\n$ SELLING_PRICE        <dbl> 3000000, 3880000, 3325000, 4250000, 1400000, 1320…\n$ AREA_SQM             <dbl> 309, 290, 248, 127, 145, 139, 218, 141, 165, 168,…\n$ AGE                  <dbl> 30, 32, 33, 7, 28, 22, 24, 24, 27, 31, 17, 22, 6,…\n$ PROX_CBD             <dbl> 7.941259, 6.609797, 6.898000, 4.038861, 11.783402…\n$ PROX_CHILDCARE       <dbl> 0.16597932, 0.28027246, 0.42922669, 0.39473543, 0…\n$ PROX_ELDERLYCARE     <dbl> 2.5198118, 1.9333338, 0.5021395, 1.9910316, 1.121…\n$ PROX_URA_GROWTH_AREA <dbl> 6.618741, 7.505109, 6.463887, 4.906512, 6.410632,…\n$ PROX_HAWKER_MARKET   <dbl> 1.76542207, 0.54507614, 0.37789301, 1.68259969, 0…\n$ PROX_KINDERGARTEN    <dbl> 0.05835552, 0.61592412, 0.14120309, 0.38200076, 0…\n$ PROX_MRT             <dbl> 0.5607188, 0.6584461, 0.3053433, 0.6910183, 0.528…\n$ PROX_PARK            <dbl> 1.1710446, 0.1992269, 0.2779886, 0.9832843, 0.116…\n$ PROX_PRIMARY_SCH     <dbl> 1.6340256, 0.9747834, 1.4715016, 1.4546324, 0.709…\n$ PROX_TOP_PRIMARY_SCH <dbl> 3.3273195, 0.9747834, 1.4715016, 2.3006394, 0.709…\n$ PROX_SHOPPING_MALL   <dbl> 2.2102717, 2.9374279, 1.2256850, 0.3525671, 1.307…\n$ PROX_SUPERMARKET     <dbl> 0.9103958, 0.5900617, 0.4135583, 0.4162219, 0.581…\n$ PROX_BUS_STOP        <dbl> 0.10336166, 0.28673408, 0.28504777, 0.29872340, 0…\n$ NO_Of_UNITS          <dbl> 18, 20, 27, 30, 30, 31, 32, 32, 32, 32, 34, 34, 3…\n$ FAMILY_FRIENDLY      <dbl> 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0…\n$ FREEHOLD             <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1…\n$ LEASEHOLD_99YR       <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(condo_resale$LONGITUDE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 103.7802 103.8123 103.7971 103.8247 103.9505 103.9386\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(condo_resale$LATITUDE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.287145 1.328698 1.313727 1.308563 1.321437 1.314198\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(condo_resale)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    LATITUDE       LONGITUDE        POSTCODE      SELLING_PRICE     \n Min.   :1.240   Min.   :103.7   Min.   : 18965   Min.   :  540000  \n 1st Qu.:1.309   1st Qu.:103.8   1st Qu.:259849   1st Qu.: 1100000  \n Median :1.328   Median :103.8   Median :469298   Median : 1383222  \n Mean   :1.334   Mean   :103.8   Mean   :440439   Mean   : 1751211  \n 3rd Qu.:1.357   3rd Qu.:103.9   3rd Qu.:589486   3rd Qu.: 1950000  \n Max.   :1.454   Max.   :104.0   Max.   :828833   Max.   :18000000  \n    AREA_SQM          AGE           PROX_CBD       PROX_CHILDCARE    \n Min.   : 34.0   Min.   : 0.00   Min.   : 0.3869   Min.   :0.004927  \n 1st Qu.:103.0   1st Qu.: 5.00   1st Qu.: 5.5574   1st Qu.:0.174481  \n Median :121.0   Median :11.00   Median : 9.3567   Median :0.258135  \n Mean   :136.5   Mean   :12.14   Mean   : 9.3254   Mean   :0.326313  \n 3rd Qu.:156.0   3rd Qu.:18.00   3rd Qu.:12.6661   3rd Qu.:0.368293  \n Max.   :619.0   Max.   :37.00   Max.   :19.1804   Max.   :3.465726  \n PROX_ELDERLYCARE  PROX_URA_GROWTH_AREA PROX_HAWKER_MARKET PROX_KINDERGARTEN \n Min.   :0.05451   Min.   :0.2145       Min.   :0.05182    Min.   :0.004927  \n 1st Qu.:0.61254   1st Qu.:3.1643       1st Qu.:0.55245    1st Qu.:0.276345  \n Median :0.94179   Median :4.6186       Median :0.90842    Median :0.413385  \n Mean   :1.05351   Mean   :4.5981       Mean   :1.27987    Mean   :0.458903  \n 3rd Qu.:1.35122   3rd Qu.:5.7550       3rd Qu.:1.68578    3rd Qu.:0.578474  \n Max.   :3.94916   Max.   :9.1554       Max.   :5.37435    Max.   :2.229045  \n    PROX_MRT         PROX_PARK       PROX_PRIMARY_SCH  PROX_TOP_PRIMARY_SCH\n Min.   :0.05278   Min.   :0.02906   Min.   :0.07711   Min.   :0.07711     \n 1st Qu.:0.34646   1st Qu.:0.26211   1st Qu.:0.44024   1st Qu.:1.34451     \n Median :0.57430   Median :0.39926   Median :0.63505   Median :1.88213     \n Mean   :0.67316   Mean   :0.49802   Mean   :0.75471   Mean   :2.27347     \n 3rd Qu.:0.84844   3rd Qu.:0.65592   3rd Qu.:0.95104   3rd Qu.:2.90954     \n Max.   :3.48037   Max.   :2.16105   Max.   :3.92899   Max.   :6.74819     \n PROX_SHOPPING_MALL PROX_SUPERMARKET PROX_BUS_STOP       NO_Of_UNITS    \n Min.   :0.0000     Min.   :0.0000   Min.   :0.001595   Min.   :  18.0  \n 1st Qu.:0.5258     1st Qu.:0.3695   1st Qu.:0.098356   1st Qu.: 188.8  \n Median :0.9357     Median :0.5687   Median :0.151710   Median : 360.0  \n Mean   :1.0455     Mean   :0.6141   Mean   :0.193974   Mean   : 409.2  \n 3rd Qu.:1.3994     3rd Qu.:0.7862   3rd Qu.:0.220466   3rd Qu.: 590.0  \n Max.   :3.4774     Max.   :2.2441   Max.   :2.476639   Max.   :1703.0  \n FAMILY_FRIENDLY     FREEHOLD      LEASEHOLD_99YR  \n Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  \n 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000  \n Median :0.0000   Median :0.0000   Median :0.0000  \n Mean   :0.4868   Mean   :0.4227   Mean   :0.4882  \n 3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000  \n Max.   :1.0000   Max.   :1.0000   Max.   :1.0000  \n```\n\n\n:::\n:::\n\n\n\n## 3.2 Converting aspatial data frame into a sf object\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncondo_resale.sf <- st_as_sf(condo_resale,\n                            coords = c(\"LONGITUDE\", \"LATITUDE\"),\n                            crs=4326) %>%\n  st_transform(crs=3414)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(condo_resale.sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 21 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 22085.12 ymin: 29951.54 xmax: 41042.56 ymax: 34546.2\nProjected CRS: SVY21 / Singapore TM\n# A tibble: 6 × 22\n  POSTCODE SELLING_PRICE AREA_SQM   AGE PROX_CBD PROX_CHILDCARE PROX_ELDERLYCARE\n     <dbl>         <dbl>    <dbl> <dbl>    <dbl>          <dbl>            <dbl>\n1   118635       3000000      309    30     7.94          0.166            2.52 \n2   288420       3880000      290    32     6.61          0.280            1.93 \n3   267833       3325000      248    33     6.90          0.429            0.502\n4   258380       4250000      127     7     4.04          0.395            1.99 \n5   467169       1400000      145    28    11.8           0.119            1.12 \n6   466472       1320000      139    22    10.3           0.125            0.789\n# ℹ 15 more variables: PROX_URA_GROWTH_AREA <dbl>, PROX_HAWKER_MARKET <dbl>,\n#   PROX_KINDERGARTEN <dbl>, PROX_MRT <dbl>, PROX_PARK <dbl>,\n#   PROX_PRIMARY_SCH <dbl>, PROX_TOP_PRIMARY_SCH <dbl>,\n#   PROX_SHOPPING_MALL <dbl>, PROX_SUPERMARKET <dbl>, PROX_BUS_STOP <dbl>,\n#   NO_Of_UNITS <dbl>, FAMILY_FRIENDLY <dbl>, FREEHOLD <dbl>,\n#   LEASEHOLD_99YR <dbl>, geometry <POINT [m]>\n```\n\n\n:::\n:::\n\n\n\n# 4. Exploratory Data Analysis (EDA)\n\n## 4.1 EDA using statistical graphics\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=condo_resale.sf, \n       aes(x=`SELLING_PRICE`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncondo_resale.sf <- condo_resale.sf %>%\n  mutate(`LOG_SELLING_PRICE` = log(SELLING_PRICE))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=condo_resale.sf, \n       aes(x=`LOG_SELLING_PRICE`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\n## 4.2 Multiple Histogram Plots distribution of variables\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAREA_SQM <- ggplot(data=condo_resale.sf, \n                   aes(x= `AREA_SQM`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nAGE <- ggplot(data=condo_resale.sf, \n              aes(x= `AGE`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nPROX_CBD <- ggplot(data=condo_resale.sf, \n                   aes(x= `PROX_CBD`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nPROX_CHILDCARE <- ggplot(data=condo_resale.sf, \n                         aes(x= `PROX_CHILDCARE`)) + \n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nPROX_ELDERLYCARE <- ggplot(data=condo_resale.sf, \n                           aes(x= `PROX_ELDERLYCARE`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nPROX_URA_GROWTH_AREA <- ggplot(data=condo_resale.sf, \n                               aes(x= `PROX_URA_GROWTH_AREA`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nPROX_HAWKER_MARKET <- ggplot(data=condo_resale.sf, \n                             aes(x= `PROX_HAWKER_MARKET`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nPROX_KINDERGARTEN <- ggplot(data=condo_resale.sf, \n                            aes(x= `PROX_KINDERGARTEN`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nPROX_MRT <- ggplot(data=condo_resale.sf, \n                   aes(x= `PROX_MRT`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nPROX_PARK <- ggplot(data=condo_resale.sf, \n                    aes(x= `PROX_PARK`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nPROX_PRIMARY_SCH <- ggplot(data=condo_resale.sf, \n                           aes(x= `PROX_PRIMARY_SCH`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nPROX_TOP_PRIMARY_SCH <- ggplot(data=condo_resale.sf, \n                               aes(x= `PROX_TOP_PRIMARY_SCH`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nggarrange(AREA_SQM, AGE, PROX_CBD, PROX_CHILDCARE, \n          PROX_ELDERLYCARE, PROX_URA_GROWTH_AREA,\n          PROX_HAWKER_MARKET, PROX_KINDERGARTEN, PROX_MRT,\n          PROX_PARK, PROX_PRIMARY_SCH, PROX_TOP_PRIMARY_SCH,  \n          ncol = 3, nrow = 4)\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n\n## 4.3 Drawing Statistical Point Map\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz_svy21)+\n  tm_polygons() +\ntm_shape(condo_resale.sf) +  \n  tm_dots(fill = \"SELLING_PRICE\",\n          fill_alpha = 0.6,\n          size = 0.5,\n          fill.scale = tm_scale_intervals(\n            style=\"quantile\")) +\n  tm_view(set_zoom_limits = c(11,14))\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n```\n:::\n\n\n\n# 5. Hedonic Pricing Modelling in R\n\n## 5.1 Simple Linear Regression Method\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncondo.slr <- lm(formula=SELLING_PRICE ~ AREA_SQM, \n                data = condo_resale.sf)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(condo.slr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = SELLING_PRICE ~ AREA_SQM, data = condo_resale.sf)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-3695815  -391764   -87517   258900 13503875 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -258121.1    63517.2  -4.064 5.09e-05 ***\nAREA_SQM      14719.0      428.1  34.381  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 942700 on 1434 degrees of freedom\nMultiple R-squared:  0.4518,\tAdjusted R-squared:  0.4515 \nF-statistic:  1182 on 1 and 1434 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=condo_resale.sf,  \n       aes(x=`AREA_SQM`, y=`SELLING_PRICE`)) +\n  geom_point() +\n  geom_smooth(method = lm)\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n\n## 5.2 Multiple Linear Regression Method\n\n### 5.2.1 Visualising the relationships of the independent variables\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncorrplot(cor(condo_resale[, 5:23]), \n         diag = FALSE, \n         order = \"AOE\",\n         tl.pos = \"td\", \n         tl.cex = 0.5, \n         method = \"number\", \n         type = \"upper\")\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n\n## 5.3 Building a hedonic pricing model using multiple linear regression method\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncondo.mlr <- lm(\n  formula = SELLING_PRICE ~ AREA_SQM + AGE  + \n    PROX_CBD + PROX_CHILDCARE + PROX_ELDERLYCARE +\n    PROX_URA_GROWTH_AREA + PROX_HAWKER_MARKET   +\n    PROX_KINDERGARTEN   + PROX_MRT  + PROX_PARK +\n    PROX_PRIMARY_SCH + PROX_TOP_PRIMARY_SCH +\n    PROX_SHOPPING_MALL  + PROX_SUPERMARKET + \n    PROX_BUS_STOP   + NO_Of_UNITS + \n    FAMILY_FRIENDLY + FREEHOLD, \n  data=condo_resale.sf)\nsummary(condo.mlr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = SELLING_PRICE ~ AREA_SQM + AGE + PROX_CBD + PROX_CHILDCARE + \n    PROX_ELDERLYCARE + PROX_URA_GROWTH_AREA + PROX_HAWKER_MARKET + \n    PROX_KINDERGARTEN + PROX_MRT + PROX_PARK + PROX_PRIMARY_SCH + \n    PROX_TOP_PRIMARY_SCH + PROX_SHOPPING_MALL + PROX_SUPERMARKET + \n    PROX_BUS_STOP + NO_Of_UNITS + FAMILY_FRIENDLY + FREEHOLD, \n    data = condo_resale.sf)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-3475964  -293923   -23069   241043 12260381 \n\nCoefficients:\n                       Estimate Std. Error t value Pr(>|t|)    \n(Intercept)           481728.40  121441.01   3.967 7.65e-05 ***\nAREA_SQM               12708.32     369.59  34.385  < 2e-16 ***\nAGE                   -24440.82    2763.16  -8.845  < 2e-16 ***\nPROX_CBD              -78669.78    6768.97 -11.622  < 2e-16 ***\nPROX_CHILDCARE       -351617.91  109467.25  -3.212  0.00135 ** \nPROX_ELDERLYCARE      171029.42   42110.51   4.061 5.14e-05 ***\nPROX_URA_GROWTH_AREA   38474.53   12523.57   3.072  0.00217 ** \nPROX_HAWKER_MARKET     23746.10   29299.76   0.810  0.41782    \nPROX_KINDERGARTEN     147468.99   82668.87   1.784  0.07466 .  \nPROX_MRT             -314599.68   57947.44  -5.429 6.66e-08 ***\nPROX_PARK             563280.50   66551.68   8.464  < 2e-16 ***\nPROX_PRIMARY_SCH      180186.08   65237.95   2.762  0.00582 ** \nPROX_TOP_PRIMARY_SCH    2280.04   20410.43   0.112  0.91107    \nPROX_SHOPPING_MALL   -206604.06   42840.60  -4.823 1.57e-06 ***\nPROX_SUPERMARKET      -44991.80   77082.64  -0.584  0.55953    \nPROX_BUS_STOP         683121.35  138353.28   4.938 8.85e-07 ***\nNO_Of_UNITS             -231.18      89.03  -2.597  0.00951 ** \nFAMILY_FRIENDLY       140340.77   47020.55   2.985  0.00289 ** \nFREEHOLD              359913.01   49220.22   7.312 4.38e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 755800 on 1417 degrees of freedom\nMultiple R-squared:  0.6518,\tAdjusted R-squared:  0.6474 \nF-statistic: 147.4 on 18 and 1417 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n## 5.4 Revising the model\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncondo.mlr1 <- lm(\n  formula = SELLING_PRICE ~ AREA_SQM + AGE + \n    PROX_CBD + PROX_CHILDCARE + PROX_MRT +\n    PROX_ELDERLYCARE    + PROX_URA_GROWTH_AREA +\n    PROX_PARK   + PROX_PRIMARY_SCH + \n    PROX_SHOPPING_MALL  + PROX_BUS_STOP + \n    NO_Of_UNITS + FAMILY_FRIENDLY + FREEHOLD,\n  data=condo_resale.sf)\nsummary(condo.mlr1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = SELLING_PRICE ~ AREA_SQM + AGE + PROX_CBD + PROX_CHILDCARE + \n    PROX_MRT + PROX_ELDERLYCARE + PROX_URA_GROWTH_AREA + PROX_PARK + \n    PROX_PRIMARY_SCH + PROX_SHOPPING_MALL + PROX_BUS_STOP + NO_Of_UNITS + \n    FAMILY_FRIENDLY + FREEHOLD, data = condo_resale.sf)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-3470778  -298119   -23481   248917 12234210 \n\nCoefficients:\n                       Estimate Std. Error t value Pr(>|t|)    \n(Intercept)           527633.22  108183.22   4.877 1.20e-06 ***\nAREA_SQM               12777.52     367.48  34.771  < 2e-16 ***\nAGE                   -24687.74    2754.84  -8.962  < 2e-16 ***\nPROX_CBD              -77131.32    5763.12 -13.384  < 2e-16 ***\nPROX_CHILDCARE       -318472.75  107959.51  -2.950 0.003231 ** \nPROX_MRT             -294745.11   56916.37  -5.179 2.56e-07 ***\nPROX_ELDERLYCARE      185575.62   39901.86   4.651 3.61e-06 ***\nPROX_URA_GROWTH_AREA   39163.25   11754.83   3.332 0.000885 ***\nPROX_PARK             570504.81   65507.03   8.709  < 2e-16 ***\nPROX_PRIMARY_SCH      159856.14   60234.60   2.654 0.008046 ** \nPROX_SHOPPING_MALL   -220947.25   36561.83  -6.043 1.93e-09 ***\nPROX_BUS_STOP         682482.22  134513.24   5.074 4.42e-07 ***\nNO_Of_UNITS             -245.48      87.95  -2.791 0.005321 ** \nFAMILY_FRIENDLY       146307.58   46893.02   3.120 0.001845 ** \nFREEHOLD              350599.81   48506.48   7.228 7.98e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 756000 on 1421 degrees of freedom\nMultiple R-squared:  0.6507,\tAdjusted R-squared:  0.6472 \nF-statistic: 189.1 on 14 and 1421 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n## 5.5 Preparing Publication Quality Table: gtsummary method\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntbl_regression(condo.mlr1, intercept = TRUE)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"addfkdinlm\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#addfkdinlm table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#addfkdinlm thead, #addfkdinlm tbody, #addfkdinlm tfoot, #addfkdinlm tr, #addfkdinlm td, #addfkdinlm th {\n  border-style: none;\n}\n\n#addfkdinlm p {\n  margin: 0;\n  padding: 0;\n}\n\n#addfkdinlm .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#addfkdinlm .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#addfkdinlm .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#addfkdinlm .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#addfkdinlm .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#addfkdinlm .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#addfkdinlm .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#addfkdinlm .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#addfkdinlm .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#addfkdinlm .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#addfkdinlm .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#addfkdinlm .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#addfkdinlm .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#addfkdinlm .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#addfkdinlm .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#addfkdinlm .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#addfkdinlm .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#addfkdinlm .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#addfkdinlm .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#addfkdinlm .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#addfkdinlm .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#addfkdinlm .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#addfkdinlm .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#addfkdinlm .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#addfkdinlm .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#addfkdinlm .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#addfkdinlm .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#addfkdinlm .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#addfkdinlm .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#addfkdinlm .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#addfkdinlm .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#addfkdinlm .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#addfkdinlm .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#addfkdinlm .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#addfkdinlm .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#addfkdinlm .gt_left {\n  text-align: left;\n}\n\n#addfkdinlm .gt_center {\n  text-align: center;\n}\n\n#addfkdinlm .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#addfkdinlm .gt_font_normal {\n  font-weight: normal;\n}\n\n#addfkdinlm .gt_font_bold {\n  font-weight: bold;\n}\n\n#addfkdinlm .gt_font_italic {\n  font-style: italic;\n}\n\n#addfkdinlm .gt_super {\n  font-size: 65%;\n}\n\n#addfkdinlm .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#addfkdinlm .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#addfkdinlm .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#addfkdinlm .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#addfkdinlm .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#addfkdinlm .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#addfkdinlm .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#addfkdinlm .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#addfkdinlm div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"PHN0cm9uZz5DaGFyYWN0ZXJpc3RpYzwvc3Ryb25nPg==\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"PHN0cm9uZz5CZXRhPC9zdHJvbmc+\"><span class='gt_from_md'><strong>Beta</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"PHN0cm9uZz45NSUgQ0k8L3N0cm9uZz4=\"><span class='gt_from_md'><strong>95% CI</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"PHN0cm9uZz5wLXZhbHVlPC9zdHJvbmc+\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">527,633</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">315,417, 739,849</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">AREA_SQM</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">12,778</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">12,057, 13,498</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">AGE</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-24,688</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-30,092, -19,284</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_CBD</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-77,131</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-88,436, -65,826</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_CHILDCARE</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-318,473</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-530,250, -106,696</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.003</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_MRT</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-294,745</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-406,394, -183,096</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_ELDERLYCARE</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">185,576</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">107,303, 263,849</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_URA_GROWTH_AREA</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">39,163</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">16,105, 62,222</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_PARK</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">570,505</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">442,004, 699,006</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_PRIMARY_SCH</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">159,856</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">41,698, 278,014</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.008</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_SHOPPING_MALL</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-220,947</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-292,668, -149,226</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_BUS_STOP</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">682,482</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">418,616, 946,348</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">NO_Of_UNITS</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-245</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-418, -73</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.005</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">FAMILY_FRIENDLY</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">146,308</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">54,321, 238,295</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.002</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">FREEHOLD</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">350,600</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">255,448, 445,752</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"Q0kgPSBDb25maWRlbmNlIEludGVydmFs\"><span class='gt_from_md'>CI = Confidence Interval</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntbl_regression(condo.mlr1, \n               intercept = TRUE) %>% \n  add_glance_source_note(\n    label = list(sigma ~ \"\\U03C3\"),\n    include = c(r.squared, adj.r.squared, \n                AIC, statistic,\n                p.value, sigma))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"hcybprzrdu\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#hcybprzrdu table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#hcybprzrdu thead, #hcybprzrdu tbody, #hcybprzrdu tfoot, #hcybprzrdu tr, #hcybprzrdu td, #hcybprzrdu th {\n  border-style: none;\n}\n\n#hcybprzrdu p {\n  margin: 0;\n  padding: 0;\n}\n\n#hcybprzrdu .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#hcybprzrdu .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#hcybprzrdu .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#hcybprzrdu .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#hcybprzrdu .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hcybprzrdu .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hcybprzrdu .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hcybprzrdu .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#hcybprzrdu .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#hcybprzrdu .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#hcybprzrdu .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#hcybprzrdu .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#hcybprzrdu .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#hcybprzrdu .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#hcybprzrdu .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#hcybprzrdu .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#hcybprzrdu .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#hcybprzrdu .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#hcybprzrdu .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hcybprzrdu .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#hcybprzrdu .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#hcybprzrdu .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#hcybprzrdu .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hcybprzrdu .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#hcybprzrdu .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#hcybprzrdu .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hcybprzrdu .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hcybprzrdu .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#hcybprzrdu .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hcybprzrdu .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#hcybprzrdu .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hcybprzrdu .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hcybprzrdu .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hcybprzrdu .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hcybprzrdu .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hcybprzrdu .gt_left {\n  text-align: left;\n}\n\n#hcybprzrdu .gt_center {\n  text-align: center;\n}\n\n#hcybprzrdu .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#hcybprzrdu .gt_font_normal {\n  font-weight: normal;\n}\n\n#hcybprzrdu .gt_font_bold {\n  font-weight: bold;\n}\n\n#hcybprzrdu .gt_font_italic {\n  font-style: italic;\n}\n\n#hcybprzrdu .gt_super {\n  font-size: 65%;\n}\n\n#hcybprzrdu .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#hcybprzrdu .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#hcybprzrdu .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#hcybprzrdu .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#hcybprzrdu .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#hcybprzrdu .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#hcybprzrdu .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#hcybprzrdu .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#hcybprzrdu div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"PHN0cm9uZz5DaGFyYWN0ZXJpc3RpYzwvc3Ryb25nPg==\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"PHN0cm9uZz5CZXRhPC9zdHJvbmc+\"><span class='gt_from_md'><strong>Beta</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"PHN0cm9uZz45NSUgQ0k8L3N0cm9uZz4=\"><span class='gt_from_md'><strong>95% CI</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"PHN0cm9uZz5wLXZhbHVlPC9zdHJvbmc+\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">527,633</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">315,417, 739,849</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">AREA_SQM</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">12,778</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">12,057, 13,498</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">AGE</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-24,688</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-30,092, -19,284</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_CBD</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-77,131</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-88,436, -65,826</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_CHILDCARE</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-318,473</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-530,250, -106,696</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.003</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_MRT</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-294,745</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-406,394, -183,096</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_ELDERLYCARE</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">185,576</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">107,303, 263,849</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_URA_GROWTH_AREA</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">39,163</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">16,105, 62,222</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_PARK</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">570,505</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">442,004, 699,006</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_PRIMARY_SCH</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">159,856</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">41,698, 278,014</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.008</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_SHOPPING_MALL</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-220,947</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-292,668, -149,226</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_BUS_STOP</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">682,482</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">418,616, 946,348</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">NO_Of_UNITS</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-245</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-418, -73</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.005</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">FAMILY_FRIENDLY</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">146,308</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">54,321, 238,295</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.002</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">FREEHOLD</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">350,600</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">255,448, 445,752</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"4\"><span data-qmd-base64=\"UsKyID0gMC42NTE7IEFkanVzdGVkIFLCsiA9IDAuNjQ3OyBBSUMgPSA0Miw5Njc7IFN0YXRpc3RpYyA9IDE4OTsgcC12YWx1ZSA9ICZsdDswLjAwMTsgz4MgPSA3NTUsOTU3\"><span class='gt_from_md'>R² = 0.651; Adjusted R² = 0.647; AIC = 42,967; Statistic = 189; p-value = &lt;0.001; σ = 755,957</span></span></td>\n    </tr>\n  </tfoot>\n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"Q0kgPSBDb25maWRlbmNlIEludGVydmFs\"><span class='gt_from_md'>CI = Confidence Interval</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n## 5.6 Regression Diagnostics\n\n### 5.6.1 Multicollinearity test\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_collinearity(condo.mlr1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Check for Multicollinearity\n\nLow Correlation\n\n                 Term  VIF   VIF 95% CI Increased SE Tolerance Tolerance 95% CI\n             AREA_SQM 1.15 [1.09, 1.23]         1.07      0.87     [0.81, 0.92]\n                  AGE 1.41 [1.33, 1.52]         1.19      0.71     [0.66, 0.75]\n             PROX_CBD 1.57 [1.47, 1.69]         1.25      0.64     [0.59, 0.68]\n       PROX_CHILDCARE 3.26 [3.00, 3.56]         1.81      0.31     [0.28, 0.33]\n             PROX_MRT 1.91 [1.78, 2.07]         1.38      0.52     [0.48, 0.56]\n     PROX_ELDERLYCARE 1.52 [1.42, 1.63]         1.23      0.66     [0.61, 0.70]\n PROX_URA_GROWTH_AREA 1.33 [1.26, 1.43]         1.15      0.75     [0.70, 0.80]\n            PROX_PARK 1.21 [1.15, 1.29]         1.10      0.83     [0.77, 0.87]\n     PROX_PRIMARY_SCH 2.21 [2.05, 2.40]         1.49      0.45     [0.42, 0.49]\n   PROX_SHOPPING_MALL 1.48 [1.39, 1.60]         1.22      0.67     [0.63, 0.72]\n        PROX_BUS_STOP 2.85 [2.62, 3.10]         1.69      0.35     [0.32, 0.38]\n          NO_Of_UNITS 1.45 [1.36, 1.56]         1.20      0.69     [0.64, 0.73]\n      FAMILY_FRIENDLY 1.38 [1.30, 1.48]         1.17      0.72     [0.67, 0.77]\n             FREEHOLD 1.44 [1.36, 1.55]         1.20      0.69     [0.65, 0.74]\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmlr.vif <- check_collinearity(condo.mlr1)\nplot(mlr.vif)\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n\n### 5.6.2 Test for Non-Linearity\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_model(condo.mlr1,\n            check = \"linearity\")\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n\n### 5.6.3 Test for Normality Assumption\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_normality(condo.mlr1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWarning: Non-normality of residuals detected (p < .001).\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(check_normality(condo.mlr1), \n     type = \"qq\")\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_model(condo.mlr1,\n            check= \"normality\")\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\n\n### 5.6.4 Testing for Spatial Autocorrelation\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmlr.output <- as.data.frame(condo.mlr1$residuals)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncondo_resale.sf <- cbind(condo_resale.sf, \n                        condo.mlr1$residuals) %>%\nrename(`MLR_RES` = `condo.mlr1.residuals`)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz_svy21) +\n  tm_polygons(fill_alpha = 0.4) +\ntm_shape(condo_resale.sf) +  \n  tm_dots(\n    fill = \"MLR_RES\",\n    size = 0.7,\n    col = \"black\",\n    fill.scale = tm_scale(\n      n = 10,\n      values = rev(\n        brewer.pal(11, \"RdBu\")),\n      style = \"quantile\",\n      midpoint = NA),\n    fill.legend = tm_legend(title = \"Residuals\")\n  ) + \n  tm_title(\"LM Residuals (Quantile Classification)\") +\n  tm_layout(legend.outside = TRUE) +\n  tm_view(set_zoom_limits = c(11,14))\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncondo_resale.sf <- condo_resale.sf %>% \n  mutate(\n    nb = st_dist_band(\n      st_geometry(geometry), \n                 upper = 1500),\n    wt = st_weights(\n      nb, style = \"W\"),\n    .before = 1) \n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nglobal_moran_perm(\n  condo_resale.sf$MLR_RES, \n  nb = condo_resale.sf$nb, \n  wt = condo_resale.sf$wt,\n  alternative = \"two.sided\", \n  nsim = 499)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 500 \n\nstatistic = 0.14389, observed rank = 500, p-value < 2.2e-16\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\n\n# 6. Building Hedonic Pricing Models using GWmodel\n\n## 6.1 Building Fixed Bandwidth GWR Model\n\n### 6.1.1 Computing fixed bandwith\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw.fixed <- bw.gwr(\n  formula = SELLING_PRICE ~ AREA_SQM + AGE  + \n    PROX_CBD + PROX_CHILDCARE + PROX_ELDERLYCARE    +\n    PROX_URA_GROWTH_AREA + PROX_MRT + PROX_PARK + \n    PROX_PRIMARY_SCH + PROX_SHOPPING_MALL   + \n    PROX_BUS_STOP   + NO_Of_UNITS + FAMILY_FRIENDLY + \n    FREEHOLD, \n  data=condo_resale.sf, \n  approach=\"CV\", \n  kernel=\"gaussian\", \n  adaptive=FALSE, \n  longlat=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFixed bandwidth: 17660.96 CV score: 8.259118e+14 \nFixed bandwidth: 10917.26 CV score: 7.970454e+14 \nFixed bandwidth: 6749.419 CV score: 7.273273e+14 \nFixed bandwidth: 4173.553 CV score: 6.300006e+14 \nFixed bandwidth: 2581.58 CV score: 5.404958e+14 \nFixed bandwidth: 1597.687 CV score: 4.857515e+14 \nFixed bandwidth: 989.6077 CV score: 4.722431e+14 \nFixed bandwidth: 613.7939 CV score: 1.377823e+16 \nFixed bandwidth: 1221.873 CV score: 4.778717e+14 \nFixed bandwidth: 846.0596 CV score: 4.791629e+14 \nFixed bandwidth: 1078.325 CV score: 4.751406e+14 \nFixed bandwidth: 934.7772 CV score: 4.72518e+14 \nFixed bandwidth: 1023.495 CV score: 4.730305e+14 \nFixed bandwidth: 968.6643 CV score: 4.721317e+14 \nFixed bandwidth: 955.7206 CV score: 4.722072e+14 \nFixed bandwidth: 976.6639 CV score: 4.721387e+14 \nFixed bandwidth: 963.7202 CV score: 4.721484e+14 \nFixed bandwidth: 971.7199 CV score: 4.721293e+14 \nFixed bandwidth: 973.6083 CV score: 4.721309e+14 \nFixed bandwidth: 970.5527 CV score: 4.721295e+14 \nFixed bandwidth: 972.4412 CV score: 4.721296e+14 \nFixed bandwidth: 971.2741 CV score: 4.721292e+14 \nFixed bandwidth: 970.9985 CV score: 4.721293e+14 \nFixed bandwidth: 971.4443 CV score: 4.721292e+14 \nFixed bandwidth: 971.5496 CV score: 4.721293e+14 \nFixed bandwidth: 971.3793 CV score: 4.721292e+14 \nFixed bandwidth: 971.3391 CV score: 4.721292e+14 \nFixed bandwidth: 971.3143 CV score: 4.721292e+14 \nFixed bandwidth: 971.3545 CV score: 4.721292e+14 \nFixed bandwidth: 971.3296 CV score: 4.721292e+14 \nFixed bandwidth: 971.345 CV score: 4.721292e+14 \nFixed bandwidth: 971.3355 CV score: 4.721292e+14 \nFixed bandwidth: 971.3413 CV score: 4.721292e+14 \nFixed bandwidth: 971.3377 CV score: 4.721292e+14 \nFixed bandwidth: 971.34 CV score: 4.721292e+14 \nFixed bandwidth: 971.3405 CV score: 4.721292e+14 \nFixed bandwidth: 971.3408 CV score: 4.721292e+14 \nFixed bandwidth: 971.3403 CV score: 4.721292e+14 \nFixed bandwidth: 971.3406 CV score: 4.721292e+14 \nFixed bandwidth: 971.3404 CV score: 4.721292e+14 \nFixed bandwidth: 971.3405 CV score: 4.721292e+14 \nFixed bandwidth: 971.3405 CV score: 4.721292e+14 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbw.fixed <- bw.gwr(\n  formula = SELLING_PRICE ~ AREA_SQM + AGE  + \n    PROX_CBD + PROX_CHILDCARE + PROX_ELDERLYCARE    +\n    PROX_URA_GROWTH_AREA + PROX_MRT + PROX_PARK + \n    PROX_PRIMARY_SCH + PROX_SHOPPING_MALL   + \n    PROX_BUS_STOP   + NO_Of_UNITS + FAMILY_FRIENDLY + \n    FREEHOLD, \n  data=condo_resale.sf, \n  approach=\"AIC\", \n  kernel=\"gaussian\", \n  adaptive=FALSE, \n  longlat=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFixed bandwidth: 17660.96 AICc value: 42937.77 \nFixed bandwidth: 10917.26 AICc value: 42886.26 \nFixed bandwidth: 6749.419 AICc value: 42757.54 \nFixed bandwidth: 4173.553 AICc value: 42565.01 \nFixed bandwidth: 2581.58 AICc value: 42368.05 \nFixed bandwidth: 1597.687 AICc value: 42256.42 \nFixed bandwidth: 989.6077 AICc value: 42262.3 \nFixed bandwidth: 1973.501 AICc value: 42279.95 \nFixed bandwidth: 1365.421 AICc value: 42254.72 \nFixed bandwidth: 1221.873 AICc value: 42255.41 \nFixed bandwidth: 1454.139 AICc value: 42254.82 \nFixed bandwidth: 1310.591 AICc value: 42254.84 \nFixed bandwidth: 1399.309 AICc value: 42254.71 \nFixed bandwidth: 1420.252 AICc value: 42254.73 \nFixed bandwidth: 1386.365 AICc value: 42254.7 \nFixed bandwidth: 1378.365 AICc value: 42254.71 \nFixed bandwidth: 1391.309 AICc value: 42254.7 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbw.fixed <- bw.gwr(\n  formula = SELLING_PRICE ~ AREA_SQM + AGE  + \n    PROX_CBD + PROX_CHILDCARE + PROX_ELDERLYCARE    +\n    PROX_URA_GROWTH_AREA + PROX_MRT + PROX_PARK + \n    PROX_PRIMARY_SCH + PROX_SHOPPING_MALL   + \n    PROX_BUS_STOP   + NO_Of_UNITS + FAMILY_FRIENDLY + \n    FREEHOLD, \n  data=condo_resale.sf, \n  approach=\"BIC\", \n  kernel=\"gaussian\", \n  adaptive=FALSE, \n  longlat=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFixed bandwidth: 17660.96 BIC value: 41593.33 \nFixed bandwidth: 10917.26 BIC value: 41566.56 \nFixed bandwidth: 6749.419 BIC value: 41500.35 \nFixed bandwidth: 4173.553 BIC value: 41445.41 \nFixed bandwidth: 2581.58 BIC value: 41505.47 \nFixed bandwidth: 5157.446 BIC value: 41459.8 \nFixed bandwidth: 3565.473 BIC value: 41449.85 \nFixed bandwidth: 4549.367 BIC value: 41448.63 \nFixed bandwidth: 3941.287 BIC value: 41445.46 \nFixed bandwidth: 4317.101 BIC value: 41446.21 \nFixed bandwidth: 4084.835 BIC value: 41445.22 \nFixed bandwidth: 4030.005 BIC value: 41445.22 \nFixed bandwidth: 4118.722 BIC value: 41445.26 \nFixed bandwidth: 4063.892 BIC value: 41445.21 \nFixed bandwidth: 4050.948 BIC value: 41445.21 \nFixed bandwidth: 4071.891 BIC value: 41445.21 \nFixed bandwidth: 4058.948 BIC value: 41445.21 \nFixed bandwidth: 4066.947 BIC value: 41445.21 \nFixed bandwidth: 4062.003 BIC value: 41445.21 \n```\n\n\n:::\n:::\n\n\n\n### 6.1.2 GWModel method - fixed bandwith\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr.fixed <- gwr.basic(\n  formula = SELLING_PRICE ~ AREA_SQM + AGE  + \n    PROX_CBD + PROX_CHILDCARE + PROX_ELDERLYCARE    +\n    PROX_URA_GROWTH_AREA + PROX_MRT + PROX_PARK +\n    PROX_PRIMARY_SCH + PROX_SHOPPING_MALL   + \n    PROX_BUS_STOP   + NO_Of_UNITS + FAMILY_FRIENDLY + \n    FREEHOLD, \n  data=condo_resale.sf, \n  bw=bw.fixed, \n  kernel = 'gaussian', \n  longlat = FALSE)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr.fixed\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   ***********************************************************************\n   *                       Package   GWmodel                             *\n   ***********************************************************************\n   Program starts at: 2025-10-18 17:14:29.844247 \n   Call:\n   gwr.basic(formula = SELLING_PRICE ~ AREA_SQM + AGE + PROX_CBD + \n    PROX_CHILDCARE + PROX_ELDERLYCARE + PROX_URA_GROWTH_AREA + \n    PROX_MRT + PROX_PARK + PROX_PRIMARY_SCH + PROX_SHOPPING_MALL + \n    PROX_BUS_STOP + NO_Of_UNITS + FAMILY_FRIENDLY + FREEHOLD, \n    data = condo_resale.sf, bw = bw.fixed, kernel = \"gaussian\", \n    longlat = FALSE)\n\n   Dependent (y) variable:  SELLING_PRICE\n   Independent variables:  AREA_SQM AGE PROX_CBD PROX_CHILDCARE PROX_ELDERLYCARE PROX_URA_GROWTH_AREA PROX_MRT PROX_PARK PROX_PRIMARY_SCH PROX_SHOPPING_MALL PROX_BUS_STOP NO_Of_UNITS FAMILY_FRIENDLY FREEHOLD\n   Number of data points: 1436\n   ***********************************************************************\n   *                    Results of Global Regression                     *\n   ***********************************************************************\n\n   Call:\n    lm(formula = formula, data = data)\n\n   Residuals:\n     Min       1Q   Median       3Q      Max \n-3470778  -298119   -23481   248917 12234210 \n\n   Coefficients:\n                          Estimate Std. Error t value Pr(>|t|)    \n   (Intercept)           527633.22  108183.22   4.877 1.20e-06 ***\n   AREA_SQM               12777.52     367.48  34.771  < 2e-16 ***\n   AGE                   -24687.74    2754.84  -8.962  < 2e-16 ***\n   PROX_CBD              -77131.32    5763.12 -13.384  < 2e-16 ***\n   PROX_CHILDCARE       -318472.75  107959.51  -2.950 0.003231 ** \n   PROX_ELDERLYCARE      185575.62   39901.86   4.651 3.61e-06 ***\n   PROX_URA_GROWTH_AREA   39163.25   11754.83   3.332 0.000885 ***\n   PROX_MRT             -294745.11   56916.37  -5.179 2.56e-07 ***\n   PROX_PARK             570504.81   65507.03   8.709  < 2e-16 ***\n   PROX_PRIMARY_SCH      159856.14   60234.60   2.654 0.008046 ** \n   PROX_SHOPPING_MALL   -220947.25   36561.83  -6.043 1.93e-09 ***\n   PROX_BUS_STOP         682482.22  134513.24   5.074 4.42e-07 ***\n   NO_Of_UNITS             -245.48      87.95  -2.791 0.005321 ** \n   FAMILY_FRIENDLY       146307.58   46893.02   3.120 0.001845 ** \n   FREEHOLD              350599.81   48506.48   7.228 7.98e-13 ***\n\n   ---Significance stars\n   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 \n   Residual standard error: 756000 on 1421 degrees of freedom\n   Multiple R-squared: 0.6507\n   Adjusted R-squared: 0.6472 \n   F-statistic: 189.1 on 14 and 1421 DF,  p-value: < 2.2e-16 \n   ***Extra Diagnostic information\n   Residual sum of squares: 8.120609e+14\n   Sigma(hat): 752522.9\n   AIC:  42966.76\n   AICc:  42967.14\n   BIC:  41731.39\n   ***********************************************************************\n   *          Results of Geographically Weighted Regression              *\n   ***********************************************************************\n\n   *********************Model calibration information*********************\n   Kernel function: gaussian \n   Fixed bandwidth: 4062.003 \n   Regression points: the same locations as observations are used.\n   Distance metric: Euclidean distance metric is used.\n\n   ****************Summary of GWR coefficient estimates:******************\n                               Min.     1st Qu.      Median     3rd Qu.\n   Intercept             -53177.018  281529.345  880015.720 1370819.342\n   AREA_SQM                4782.896    7711.152   12015.329   15634.498\n   AGE                   -45640.381  -37497.344  -23025.827  -12442.350\n   PROX_CBD             -131232.506 -105150.303  -91465.675  -72185.483\n   PROX_CHILDCARE       -918543.637 -497289.624  -91262.832   25164.643\n   PROX_ELDERLYCARE     -105874.439   75882.790  197613.698  287555.979\n   PROX_URA_GROWTH_AREA  -58433.315  -14446.323   22865.285   66854.992\n   PROX_MRT             -818742.856 -527888.506 -370736.000 -194231.914\n   PROX_PARK            -147538.508  159980.396  493820.240  768741.542\n   PROX_PRIMARY_SCH     -194486.524  -38433.509  176372.551  324480.299\n   PROX_SHOPPING_MALL   -524492.230 -268138.078 -145438.042  -43047.002\n   PROX_BUS_STOP          39694.313  354428.154  784663.633 1079425.882\n   NO_Of_UNITS             -638.405    -510.445    -259.764     -47.244\n   FAMILY_FRIENDLY       -62978.435   69588.845  154439.412  303570.142\n   FREEHOLD               42267.156  202338.112  295430.145  406652.963\n                              Max.\n   Intercept            1805833.71\n   AREA_SQM               16573.26\n   AGE                    -4653.84\n   PROX_CBD              -35186.70\n   PROX_CHILDCARE        236120.38\n   PROX_ELDERLYCARE      377837.54\n   PROX_URA_GROWTH_AREA  105132.33\n   PROX_MRT              -40558.75\n   PROX_PARK             884432.31\n   PROX_PRIMARY_SCH      541493.93\n   PROX_SHOPPING_MALL    139775.01\n   PROX_BUS_STOP        1366060.08\n   NO_Of_UNITS              151.23\n   FAMILY_FRIENDLY       411016.58\n   FREEHOLD              544941.24\n   ************************Diagnostic information*************************\n   Number of data points: 1436 \n   Effective number of parameters (2trace(S) - trace(S'S)): 82.88972 \n   Effective degrees of freedom (n-2trace(S) + trace(S'S)): 1353.11 \n   AICc (GWR book, Fotheringham, et al. 2002, p. 61, eq 2.33): 42553.96 \n   AIC (GWR book, Fotheringham, et al. 2002,GWR p. 96, eq. 4.22): 42482.11 \n   BIC (GWR book, Fotheringham, et al. 2002,GWR p. 61, eq. 2.34): 41445.21 \n   Residual sum of squares: 5.668132e+14 \n   R-square value:  0.7561723 \n   Adjusted R-square value:  0.7412247 \n\n   ***********************************************************************\n   Program stops at: 2025-10-18 17:14:31.79288 \n```\n\n\n:::\n:::\n\n\n\n## 6.2 Building Adaptive Bandwidth GWR Model\n\n### 6.2.1 Computing the adaptive bandwidth\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw.adaptive <- bw.gwr(\n  formula = SELLING_PRICE ~ AREA_SQM + AGE  + \n    PROX_CBD + PROX_CHILDCARE + PROX_ELDERLYCARE    +\n    PROX_URA_GROWTH_AREA + PROX_MRT + PROX_PARK +\n    PROX_PRIMARY_SCH + PROX_SHOPPING_MALL   + \n    PROX_BUS_STOP   + NO_Of_UNITS + \n    FAMILY_FRIENDLY + FREEHOLD, \n  data=condo_resale.sf, \n  approach=\"CV\", \n  kernel=\"gaussian\", \n  adaptive=TRUE, \n  longlat=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAdaptive bandwidth: 895 CV score: 7.952401e+14 \nAdaptive bandwidth: 561 CV score: 7.667364e+14 \nAdaptive bandwidth: 354 CV score: 6.953454e+14 \nAdaptive bandwidth: 226 CV score: 6.15223e+14 \nAdaptive bandwidth: 147 CV score: 5.674373e+14 \nAdaptive bandwidth: 98 CV score: 5.426745e+14 \nAdaptive bandwidth: 68 CV score: 5.168117e+14 \nAdaptive bandwidth: 49 CV score: 4.859631e+14 \nAdaptive bandwidth: 37 CV score: 4.646518e+14 \nAdaptive bandwidth: 30 CV score: 4.422088e+14 \nAdaptive bandwidth: 25 CV score: 4.430816e+14 \nAdaptive bandwidth: 32 CV score: 4.505602e+14 \nAdaptive bandwidth: 27 CV score: 4.462172e+14 \nAdaptive bandwidth: 30 CV score: 4.422088e+14 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbw.adaptive <- bw.gwr(\n  formula = SELLING_PRICE ~ AREA_SQM + AGE  + \n    PROX_CBD + PROX_CHILDCARE + PROX_ELDERLYCARE    +\n    PROX_URA_GROWTH_AREA + PROX_MRT + PROX_PARK +\n    PROX_PRIMARY_SCH + PROX_SHOPPING_MALL   + \n    PROX_BUS_STOP   + NO_Of_UNITS + \n    FAMILY_FRIENDLY + FREEHOLD, \n  data=condo_resale.sf, \n  approach=\"AIC\", \n  kernel=\"gaussian\", \n  adaptive=TRUE, \n  longlat=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAdaptive bandwidth (number of nearest neighbours): 895 AICc value: 42879.45 \nAdaptive bandwidth (number of nearest neighbours): 561 AICc value: 42823.52 \nAdaptive bandwidth (number of nearest neighbours): 354 AICc value: 42677.14 \nAdaptive bandwidth (number of nearest neighbours): 226 AICc value: 42484.37 \nAdaptive bandwidth (number of nearest neighbours): 147 AICc value: 42353.27 \nAdaptive bandwidth (number of nearest neighbours): 98 AICc value: 42280.68 \nAdaptive bandwidth (number of nearest neighbours): 68 AICc value: 42201.18 \nAdaptive bandwidth (number of nearest neighbours): 49 AICc value: 42100.66 \nAdaptive bandwidth (number of nearest neighbours): 37 AICc value: 42055.68 \nAdaptive bandwidth (number of nearest neighbours): 30 AICc value: 41982.22 \nAdaptive bandwidth (number of nearest neighbours): 25 AICc value: 42003.33 \nAdaptive bandwidth (number of nearest neighbours): 32 AICc value: 42035.41 \nAdaptive bandwidth (number of nearest neighbours): 27 AICc value: 41978.63 \nAdaptive bandwidth (number of nearest neighbours): 27 AICc value: 41978.63 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbw.adaptive <- bw.gwr(\n  formula = SELLING_PRICE ~ AREA_SQM + AGE  + \n    PROX_CBD + PROX_CHILDCARE + PROX_ELDERLYCARE    +\n    PROX_URA_GROWTH_AREA + PROX_MRT + PROX_PARK +\n    PROX_PRIMARY_SCH + PROX_SHOPPING_MALL   + \n    PROX_BUS_STOP   + NO_Of_UNITS + \n    FAMILY_FRIENDLY + FREEHOLD, \n  data=condo_resale.sf, \n  approach=\"BIC\", \n  kernel=\"gaussian\", \n  adaptive=TRUE, \n  longlat=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAdaptive bandwidth (number of nearest neighbours): 895 BIC value: 41549.42 \nAdaptive bandwidth (number of nearest neighbours): 561 BIC value: 41522.62 \nAdaptive bandwidth (number of nearest neighbours): 354 BIC value: 41426.52 \nAdaptive bandwidth (number of nearest neighbours): 226 BIC value: 41306.39 \nAdaptive bandwidth (number of nearest neighbours): 147 BIC value: 41278.47 \nAdaptive bandwidth (number of nearest neighbours): 98 BIC value: 41355.99 \nAdaptive bandwidth (number of nearest neighbours): 177 BIC value: 41282.21 \nAdaptive bandwidth (number of nearest neighbours): 128 BIC value: 41294.4 \nAdaptive bandwidth (number of nearest neighbours): 158 BIC value: 41280.62 \nAdaptive bandwidth (number of nearest neighbours): 139 BIC value: 41280.71 \nAdaptive bandwidth (number of nearest neighbours): 151 BIC value: 41280.81 \nAdaptive bandwidth (number of nearest neighbours): 143 BIC value: 41283.33 \nAdaptive bandwidth (number of nearest neighbours): 147 BIC value: 41278.47 \n```\n\n\n:::\n:::\n\n\n\n### 6.2.2 Constructing the adaptive bandwidth gwr model\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr.adaptive <- gwr.basic(\n  formula = SELLING_PRICE ~ AREA_SQM + AGE + \n    PROX_CBD + PROX_CHILDCARE + PROX_ELDERLYCARE +\n    PROX_URA_GROWTH_AREA + PROX_MRT + PROX_PARK +\n    PROX_PRIMARY_SCH + PROX_SHOPPING_MALL + PROX_BUS_STOP +\n    NO_Of_UNITS + FAMILY_FRIENDLY + FREEHOLD,\n  data=condo_resale.sf, \n  bw=bw.adaptive, \n  kernel = 'gaussian', \n  adaptive=TRUE, \n  longlat = FALSE)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr.adaptive\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   ***********************************************************************\n   *                       Package   GWmodel                             *\n   ***********************************************************************\n   Program starts at: 2025-10-18 17:15:22.383254 \n   Call:\n   gwr.basic(formula = SELLING_PRICE ~ AREA_SQM + AGE + PROX_CBD + \n    PROX_CHILDCARE + PROX_ELDERLYCARE + PROX_URA_GROWTH_AREA + \n    PROX_MRT + PROX_PARK + PROX_PRIMARY_SCH + PROX_SHOPPING_MALL + \n    PROX_BUS_STOP + NO_Of_UNITS + FAMILY_FRIENDLY + FREEHOLD, \n    data = condo_resale.sf, bw = bw.adaptive, kernel = \"gaussian\", \n    adaptive = TRUE, longlat = FALSE)\n\n   Dependent (y) variable:  SELLING_PRICE\n   Independent variables:  AREA_SQM AGE PROX_CBD PROX_CHILDCARE PROX_ELDERLYCARE PROX_URA_GROWTH_AREA PROX_MRT PROX_PARK PROX_PRIMARY_SCH PROX_SHOPPING_MALL PROX_BUS_STOP NO_Of_UNITS FAMILY_FRIENDLY FREEHOLD\n   Number of data points: 1436\n   ***********************************************************************\n   *                    Results of Global Regression                     *\n   ***********************************************************************\n\n   Call:\n    lm(formula = formula, data = data)\n\n   Residuals:\n     Min       1Q   Median       3Q      Max \n-3470778  -298119   -23481   248917 12234210 \n\n   Coefficients:\n                          Estimate Std. Error t value Pr(>|t|)    \n   (Intercept)           527633.22  108183.22   4.877 1.20e-06 ***\n   AREA_SQM               12777.52     367.48  34.771  < 2e-16 ***\n   AGE                   -24687.74    2754.84  -8.962  < 2e-16 ***\n   PROX_CBD              -77131.32    5763.12 -13.384  < 2e-16 ***\n   PROX_CHILDCARE       -318472.75  107959.51  -2.950 0.003231 ** \n   PROX_ELDERLYCARE      185575.62   39901.86   4.651 3.61e-06 ***\n   PROX_URA_GROWTH_AREA   39163.25   11754.83   3.332 0.000885 ***\n   PROX_MRT             -294745.11   56916.37  -5.179 2.56e-07 ***\n   PROX_PARK             570504.81   65507.03   8.709  < 2e-16 ***\n   PROX_PRIMARY_SCH      159856.14   60234.60   2.654 0.008046 ** \n   PROX_SHOPPING_MALL   -220947.25   36561.83  -6.043 1.93e-09 ***\n   PROX_BUS_STOP         682482.22  134513.24   5.074 4.42e-07 ***\n   NO_Of_UNITS             -245.48      87.95  -2.791 0.005321 ** \n   FAMILY_FRIENDLY       146307.58   46893.02   3.120 0.001845 ** \n   FREEHOLD              350599.81   48506.48   7.228 7.98e-13 ***\n\n   ---Significance stars\n   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 \n   Residual standard error: 756000 on 1421 degrees of freedom\n   Multiple R-squared: 0.6507\n   Adjusted R-squared: 0.6472 \n   F-statistic: 189.1 on 14 and 1421 DF,  p-value: < 2.2e-16 \n   ***Extra Diagnostic information\n   Residual sum of squares: 8.120609e+14\n   Sigma(hat): 752522.9\n   AIC:  42966.76\n   AICc:  42967.14\n   BIC:  41731.39\n   ***********************************************************************\n   *          Results of Geographically Weighted Regression              *\n   ***********************************************************************\n\n   *********************Model calibration information*********************\n   Kernel function: gaussian \n   Adaptive bandwidth: 147 (number of nearest neighbours)\n   Regression points: the same locations as observations are used.\n   Distance metric: Euclidean distance metric is used.\n\n   ****************Summary of GWR coefficient estimates:******************\n                               Min.     1st Qu.      Median     3rd Qu.\n   Intercept            -9.0930e+05  2.9000e+05  7.4952e+05  1.4368e+06\n   AREA_SQM              4.8484e+03  7.9316e+03  1.2043e+04  1.5604e+04\n   AGE                  -6.9805e+04 -3.9558e+04 -2.3204e+04 -1.0307e+04\n   PROX_CBD             -2.5012e+05 -1.1125e+05 -9.1179e+04 -7.5267e+04\n   PROX_CHILDCARE       -1.0638e+06 -3.1424e+05 -1.6611e+04  9.9726e+04\n   PROX_ELDERLYCARE     -1.0512e+05  1.1387e+05  1.7661e+05  2.8105e+05\n   PROX_URA_GROWTH_AREA -1.3688e+05 -1.6629e+04  3.1436e+04  7.1311e+04\n   PROX_MRT             -1.6188e+06 -6.2991e+05 -3.5663e+05 -2.7298e+05\n   PROX_PARK            -2.4102e+05  9.4328e+03  4.5910e+05  7.1345e+05\n   PROX_PRIMARY_SCH     -1.9279e+05  2.8732e+04  1.4874e+05  3.3334e+05\n   PROX_SHOPPING_MALL   -4.8662e+05 -2.5510e+05 -1.3863e+05 -1.2313e+04\n   PROX_BUS_STOP        -3.7614e+04  2.8960e+05  7.2455e+05  1.1552e+06\n   NO_Of_UNITS          -8.6929e+02 -4.6827e+02 -2.4796e+02 -7.1072e+01\n   FAMILY_FRIENDLY      -1.1400e+04  6.3580e+04  1.2901e+05  3.0417e+05\n   FREEHOLD              5.5328e+04  2.0819e+05  3.0825e+05  4.0026e+05\n                              Max.\n   Intercept            2559437.32\n   AREA_SQM               17753.77\n   AGE                    -4583.59\n   PROX_CBD              -24210.29\n   PROX_CHILDCARE        491634.42\n   PROX_ELDERLYCARE      408110.11\n   PROX_URA_GROWTH_AREA  282678.32\n   PROX_MRT              -42428.11\n   PROX_PARK             869914.38\n   PROX_PRIMARY_SCH     1628158.01\n   PROX_SHOPPING_MALL    132979.30\n   PROX_BUS_STOP        3262113.43\n   NO_Of_UNITS              268.59\n   FAMILY_FRIENDLY       976625.77\n   FREEHOLD              830532.49\n   ************************Diagnostic information*************************\n   Number of data points: 1436 \n   Effective number of parameters (2trace(S) - trace(S'S)): 92.47833 \n   Effective degrees of freedom (n-2trace(S) + trace(S'S)): 1343.522 \n   AICc (GWR book, Fotheringham, et al. 2002, p. 61, eq 2.33): 42353.27 \n   AIC (GWR book, Fotheringham, et al. 2002,GWR p. 96, eq. 4.22): 42273.34 \n   BIC (GWR book, Fotheringham, et al. 2002,GWR p. 61, eq. 2.34): 41278.47 \n   Residual sum of squares: 4.878365e+14 \n   R-square value:  0.790146 \n   Adjusted R-square value:  0.7756904 \n\n   ***********************************************************************\n   Program stops at: 2025-10-18 17:15:24.157756 \n```\n\n\n:::\n:::\n\n\n\n-   Fixed bandwidth (4062 m) assumes spatial processes vary uniformly — good for evenly spaced data, but may over-smooth dense urban areas.\n-   Adaptive bandwidth (147 nearest neighbours) adjusts the window size depending on data density — smaller in dense areas, larger in sparse ones.\n-   Both AIC and BIC results point to adaptive GWR (147 NN) as the best-performing and most realistic model for spatially heterogeneous housing data.\n\nBetween fixed and adaptive bandwidth approaches, the adaptive GWR model using 147 nearest neighbours (BIC-selected) performed best. It achieved the lowest BIC (41278.47), higher R², and smaller residuals, indicating that local spatial variations in housing prices are better captured when the bandwidth adapts to data density. Therefore, the adaptive (BIC-based) approach represents the correct and optimal nearest-neighbour configuration for this pricing model.\n\n## 6.3 Converting SDF into sf data.frame\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncondo_resale.sf.adaptive <-\n  st_as_sf(gwr.adaptive$SDF) %>%\n  st_transform(crs=3414)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(condo_resale.sf.adaptive)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,436\nColumns: 52\n$ Intercept               <dbl> 882486.7, 290126.6, 762198.0, -324250.4, 14305…\n$ AREA_SQM                <dbl> 14191.900, 16520.276, 15351.762, 17448.807, 60…\n$ AGE                     <dbl> -26635.424, -46734.827, -37492.117, -68060.842…\n$ PROX_CBD                <dbl> -83598.91, -79953.53, -100097.21, -59865.84, -…\n$ PROX_CHILDCARE          <dbl> -149160.2200, -24807.3116, 298809.4758, 296018…\n$ PROX_ELDERLYCARE        <dbl> 106476.23, 314537.95, 266428.22, 325458.48, 13…\n$ PROX_URA_GROWTH_AREA    <dbl> -35528.459, -65086.870, -106494.148, -41795.52…\n$ PROX_MRT                <dbl> -356634.61, -804282.70, -639312.85, -1497751.4…\n$ PROX_PARK               <dbl> 578680.22, 810906.05, 660302.23, 613782.83, -1…\n$ PROX_PRIMARY_SCH        <dbl> 205590.319, 584054.935, 454049.928, 1183859.95…\n$ PROX_SHOPPING_MALL      <dbl> -230134.792, -142567.378, -142656.086, -332052…\n$ PROX_BUS_STOP           <dbl> 886508.0, 1313545.2, 1374644.7, 2760175.8, 289…\n$ NO_Of_UNITS             <dbl> -545.41020, -591.15844, -671.30595, -676.49262…\n$ FAMILY_FRIENDLY         <dbl> 239435.13, 458560.30, 450543.57, 839633.52, 52…\n$ FREEHOLD                <dbl> 330841.66, 371572.01, 353790.24, 704445.59, 22…\n$ y                       <dbl> 3000000, 3880000, 3325000, 4250000, 1400000, 1…\n$ yhat                    <dbl> 4530852.6, 3688595.9, 3424534.4, 4415548.7, 14…\n$ residual                <dbl> -1530852.55, 191404.07, -99534.41, -165548.74,…\n$ CV_Score                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ Stud_residual           <dbl> -2.73696354, 0.33009145, -0.17492358, -0.28549…\n$ Intercept_SE            <dbl> 153159.7, 141182.3, 169637.3, 170343.2, 246354…\n$ AREA_SQM_SE             <dbl> 410.2435, 426.4684, 434.1756, 492.0255, 680.34…\n$ AGE_SE                  <dbl> 3376.742, 3432.861, 3556.053, 4611.327, 5340.5…\n$ PROX_CBD_SE             <dbl> 8850.299, 9557.984, 10988.952, 16693.223, 3318…\n$ PROX_CHILDCARE_SE       <dbl> 143065.5, 154669.8, 174407.4, 208856.5, 289010…\n$ PROX_ELDERLYCARE_SE     <dbl> 55210.90, 53738.31, 57257.64, 71930.62, 103953…\n$ PROX_URA_GROWTH_AREA_SE <dbl> 24456.83, 20320.78, 28721.74, 35000.51, 46549.…\n$ PROX_MRT_SE             <dbl> 86685.95, 87813.34, 99123.30, 153791.23, 11386…\n$ PROX_PARK_SE            <dbl> 86917.94, 94712.09, 103293.89, 118405.57, 1630…\n$ PROX_PRIMARY_SCH_SE     <dbl> 74070.89, 73926.43, 80033.07, 104437.67, 14983…\n$ PROX_SHOPPING_MALL_SE   <dbl> 53543.34, 48335.82, 57728.08, 75382.46, 83412.…\n$ PROX_BUS_STOP_SE        <dbl> 175118.3, 219682.9, 233035.8, 303479.1, 397614…\n$ NO_Of_UNITS_SE          <dbl> 115.0315, 120.5914, 134.6531, 154.6652, 159.35…\n$ FAMILY_FRIENDLY_SE      <dbl> 63749.63, 63330.87, 68943.15, 84243.61, 89889.…\n$ FREEHOLD_SE             <dbl> 60488.78, 58495.20, 64687.76, 85117.81, 106640…\n$ Intercept_TV            <dbl> 5.761872, 2.054979, 4.493104, -1.903512, 5.806…\n$ AREA_SQM_TV             <dbl> 34.593844, 38.737398, 35.358420, 35.463216, 8.…\n$ AGE_TV                  <dbl> -7.887907, -13.613957, -10.543182, -14.759492,…\n$ PROX_CBD_TV             <dbl> -9.445885, -8.365104, -9.108895, -3.586236, -3…\n$ PROX_CHILDCARE_TV       <dbl> -1.0426006580, -0.1603888336, 1.7132839681, 1.…\n$ PROX_ELDERLYCARE_TV     <dbl> 1.9285363, 5.8531418, 4.6531475, 4.5246167, 1.…\n$ PROX_URA_GROWTH_AREA_TV <dbl> -1.45270116, -3.20297185, -3.70778827, -1.1941…\n$ PROX_MRT_TV             <dbl> -4.1140992, -9.1590040, -6.4496729, -9.7388614…\n$ PROX_PARK_TV            <dbl> 6.6577765, 8.5618012, 6.3924618, 5.1837329, -1…\n$ PROX_PRIMARY_SCH_TV     <dbl> 2.77558853, 7.90048937, 5.67327875, 11.3355649…\n$ PROX_SHOPPING_MALL_TV   <dbl> -4.29810305, -2.94951807, -2.47117312, -4.4049…\n$ PROX_BUS_STOP_TV        <dbl> 5.0623369, 5.9792784, 5.8988574, 9.0951095, 0.…\n$ NO_Of_UNITS_TV          <dbl> -4.7413979, -4.9021611, -4.9854476, -4.3739168…\n$ FAMILY_FRIENDLY_TV      <dbl> 3.7558672, 7.2407072, 6.5350009, 9.9667328, 0.…\n$ FREEHOLD_TV             <dbl> 5.4694716, 6.3521793, 5.4691990, 8.2761244, 2.…\n$ Local_R2                <dbl> 0.6165668, 0.7738609, 0.7457216, 0.8053114, 0.…\n$ geometry                <POINT [m]> POINT (22085.12 29951.54), POINT (25656.…\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(gwr.adaptive$SDF$yhat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n  -66495  1082525  1401799  1770312  2035795 13292193 \n```\n\n\n:::\n:::\n\n\n\n## 6.4 Visualising local R2\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\ntm_shape(mpsz_svy21)+\n  tm_polygons(fill_alpha = 0.1) +\ntm_shape(condo_resale.sf.adaptive) +  \n  tm_dots(col = \"Local_R2\",\n          border.col = \"gray60\",\n          border.lwd = 1) +\n  tm_view(set.zoom.limits = c(11,14))\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-54-1.png){width=672}\n:::\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n```\n:::\n\n\n\n## 6.5 Thematic Mapping\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filtering dataset for only Local R² values between 0.85 and 0.9\ncondo_resale_filtered <- condo_resale.sf.adaptive %>%\n  filter(Local_R2 >= 0.85 & Local_R2 <= 0.9)\n\n# Switching to static map mode\ntmap_mode(\"plot\")\n\n# Plotting\ntm_shape(mpsz_svy21) +\n  tm_polygons(fill = \"gray90\", border.col = \"white\") +\ntm_shape(condo_resale_filtered) +\n  tm_dots(col = \"Local_R2\",\n          size = 0.08,\n          border.col = \"gray50\",\n          border.lwd = 0.5,\n          palette = \"-RdYlBu\",\n          title = \"Local R² (0.85 – 0.9)\") +\n  tm_compass(type = \"8star\", size = 2) +\n  tm_scale_bar() +\n  tm_credits(\"Source: URA MP 2019, Condo Resale Data, GWR Results\",\n             position = c(\"left\", \"bottom\")) +\n  tm_layout(title = \"Spatial Cluster of High Local R² (0.85 – 0.9)\",\n            legend.outside = TRUE,\n            frame = TRUE,\n            bg.color = \"white\")\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-55-1.png){width=672}\n:::\n:::\n\n\n\n## Analyzing R² Distribution in Jurong East Planning Area\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extracting Jurong East Data\n\n# Extract Jurong East planning area boundary\nJurongEast_boundary <- mpsz_svy21 %>%\n filter(PLN_AREA_N == \"JURONG EAST\")\n# Filter GWR results for Jurong East area\nJurongEast_gwr <- condo_resale.sf.adaptive %>%\n st_join(JurongEast_boundary) %>%\n filter(!is.na(PLN_AREA_N))\n# Checking the number of observations in Jurong East\nnrow(JurongEast_gwr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 15\n```\n\n\n:::\n\n```{.r .cell-code}\n# Summary Statistics of R² in Jurong East\n# Summary of Local R² in Jurong East\nJurongEast_r2_summary <- summary(JurongEast_gwr$Local_R2)\nJurongEast_r2_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.7247  0.7486  0.7624  0.7570  0.7679  0.7720 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Additional statistics\nJurongEast_r2_stats <- JurongEast_gwr %>%\n st_drop_geometry() %>%\n summarise(\n   n = n(),\n   mean_r2 = mean(Local_R2),\n   median_r2 = median(Local_R2),\n   sd_r2 = sd(Local_R2),\n   min_r2 = min(Local_R2),\n   max_r2 = max(Local_R2),\n   q1_r2 = quantile(Local_R2, 0.25),\n   q3_r2 = quantile(Local_R2, 0.75)\n )\nJurongEast_r2_stats\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   n   mean_r2 median_r2      sd_r2    min_r2    max_r2     q1_r2     q3_r2\n1 15 0.7570286 0.7624288 0.01566552 0.7246578 0.7720285 0.7486432 0.7678689\n```\n\n\n:::\n\n```{.r .cell-code}\n# Visualizing R² Distribution in Jurong East\n# Histogram of Local R² in Jurong East\nggplot(JurongEast_gwr, aes(x = Local_R2)) +\n geom_histogram(bins = 15, fill = \"lightblue\", color = \"black\", alpha = 0.7) +\n geom_vline(aes(xintercept = mean(Local_R2)), color = \"red\", linetype = \"dashed\", size = 1) +\n labs(title = \"Distribution of Local R² in Jurong East Planning Area\",\n      x = \"Local R²\",\n      y = \"Frequency\") +\n theme_minimal()\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-56-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Spatial Distribution of R² in Jurong East\n# Map of Local R² in Jurong East\ntm_shape(JurongEast_boundary) +\n tm_polygons(alpha = 0.3, col = \"lightgray\") +\ntm_shape(JurongEast_gwr) +\n tm_dots(col = \"Local_R2\",\n         palette = \"RdYlBu\",\n         style = \"quantile\",\n         size = 0.8,\n         title = \"Local R²\") +\n tm_layout(main.title = \"Local R² Distribution in Jurong East Planning Area\",\n           legend.outside = TRUE)\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-56-2.png){width=672}\n:::\n\n```{.r .cell-code}\n# Comparison with Overall R² Distribution\n# Compare Jurong East with overall distribution\noverall_r2_stats <- condo_resale.sf.adaptive %>%\n st_drop_geometry() %>%\n summarise(\n   n = n(),\n   mean_r2 = mean(Local_R2),\n   median_r2 = median(Local_R2),\n   sd_r2 = sd(Local_R2)\n )\ncomparison <- data.frame(\n Area = c(\"Jurong East\", \"Overall\"),\n Mean_R2 = c(JurongEast_r2_stats$mean_r2, overall_r2_stats$mean_r2),\n Median_R2 = c(JurongEast_r2_stats$median_r2, overall_r2_stats$median_r2),\n SD_R2 = c(JurongEast_r2_stats$sd_r2, overall_r2_stats$sd_r2)\n)\ncomparison\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Area   Mean_R2 Median_R2      SD_R2\n1 Jurong East 0.7570286 0.7624288 0.01566552\n2     Overall 0.7801275 0.7796238 0.07250616\n```\n\n\n:::\n:::\n",
    "supporting": [
      "In-class_Ex07_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}